### ISSUE TITLE
System.MissingMethodException: No parameterless constructor defined for this object.

### ISSUE THREAD

**Issue by reminvestor** [HangfireIO/Hangfire#1052]
My jobs are running successfully but I get this error on all of them. I am using  Autofac Activator. 
GlobalConfiguration.Configuration.UseAutofacActivator(container); Here is what my constructor looks like for the job and it works but I do get an error.

        private readonly ICacheClient _cache;
        private readonly IOnBaseService _onBaseService;
        private readonly ILogger _logger;
        private readonly IDocumentCommands _documentCommands;

        public OnBase(IDocumentCommands documentCommands, ILogger logger, IOnBaseService onBaseService, ICacheClient cache)
        {
            _documentCommands = documentCommands;
            _logger = logger;
            _onBaseService = onBaseService;
             _cache = cache;
        }

No parameterless constructor defined for this object.

System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Hangfire.JobActivator.ActivateJob(Type jobType)
   at Hangfire.JobActivator.SimpleJobActivatorScope.Resolve(Type type)
   at Hangfire.Server.CoreBackgroundJobPerformer.Perform(PerformContext context)
   at Hangfire.Server.BackgroundJobPerformer.<>c__DisplayClass8_0.<PerformJobWithFilters>b__0()
   at Hangfire.Server.BackgroundJobPerformer.InvokePerformFilter(IServerFilter filter, PerformingContext preContext, Func`1 continuation)
   at Hangfire.Server.BackgroundJobPerformer.<>c__DisplayClass8_1.<PerformJobWithFilters>b__2()
   at Hangfire.Server.BackgroundJobPerformer.PerformJobWithFilters(PerformContext context, IEnumerable`1 filters)
   at Hangfire.Server.BackgroundJobPerformer.Perform(PerformContext context)
   at Hangfire.Server.Worker.PerformJob(BackgroundProcessContext context, IStorageConnection connection, String jobId)

**Comment by burningice2866** [comment]
Somehow Hangfire is not using your Autofac Activator - you can see on this line that it falls back to SimpleJobActivatorScope

`at Hangfire.JobActivator.SimpleJobActivatorScope.Resolve(Type type)`

this activator only supports parameterless constructors.
