### ISSUE TITLE
[QUESTION] Database with custom user 

### ISSUE THREAD

**Issue by vdecristofaro** [HangfireIO/Hangfire#1065]
I have a database where I have enabled Hangfire server. Actually in the database there are two different schemas:
- `dbo` under which my application tables resides
- `hangfire` under which Hangfire is installed and working

To lock down application user right I have created a sql user and configured this user in my connection string with the following sql instructions:

```
CREATE USER myappuser WITH PASSWORD = 'supersecret';
EXEC sp_addrolemember N'db_datareader', N'myappuser'
EXEC sp_addrolemember N'db_datawriter', N'myappuser'
```

This works correctly for my application but, from time to time, I am experiencing Hangfire exceptions during the execution of a Job.

```
2017-11-20 23:18:47,001 [Worker #34e520f6] DEBUG Hangfire.Server.Worker - Error occurred during execution of 'Worker #34e520f6' process. Execution will be retried (attempt #1) in 00:00:00 seconds.
System.Data.SqlClient.SqlException (0x80131904): Login failed for user 'myappuser'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
   at Hangfire.SqlServer.SqlServerJobQueue.DequeueUsingTransaction(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:1c949348-a260-4757-b905-9cbeae694dc4
Error Number:18456,State:1,Class:14
ClientConnectionId before routing:07e64004-5d09-4168-9328-31c774bdbc22
Routing Destination:x.y.z.worker.database.windows.net,11198
```

Do I need to setup specific user rights for `myappuser` to works with Hangfire?

**Comment by vdecristofaro** [comment]
I have been able to solve the problem by using suggestions on the linked page.
This was exactly the missing authorization

```
ALTER AUTHORIZATION ON SCHEMA::[HangFire] TO [HangFire]
GO
```
