### ISSUE TITLE
LoggerFactory throws ObjectDisposedException in integration tests

### ISSUE THREAD

**Issue by MovGP0** [HangfireIO/Hangfire#1099]
When unit testing I create a new logger on each test. The method `Hangfire.AspNetCore.AspNetCoreLogProvider.GetLogger(string name)` throws an exception on subsequent unit tests, because it tries to access the already disposed logger instead of accessing the new one. 

**Tests**
All tests have the following format: 
```csharp
using (var server = IntegrationTestHelper.CreateDisposableTestServer())
using (var client = server.CreateClient())
{
    // ...
} // logger is disposed here
```

**Test Setup**
There is a new logger created for every test: 
```csharp
public static TestServer CreateDisposableTestServer()
{
    Log.Logger = new LoggerConfiguration()
        .MinimumLevel.Debug()
        .MinimumLevel.Override("System", LogEventLevel.Warning)
        .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
        .MinimumLevel.Override("Microsoft.AspNetCore", LogEventLevel.Warning)
        .MinimumLevel.Override("Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware", LogEventLevel.Fatal)
        .MinimumLevel.Override("LoggingConnectionAdapter", LogEventLevel.Warning)
        .MinimumLevel.Warning()
        .Enrich.FromLogContext()
        .WriteTo.Console(LogEventLevel.Verbose, OutputTemplate, theme: AnsiConsoleTheme.Literate)
        .CreateLogger();

    var directory = Directory.GetCurrentDirectory();
    var builder = new WebHostBuilder()
        .UseContentRoot(directory)
        .UseStartup<Startup>();

    return new TestServer(builder);
}
```

**Startup.cs**
Hangfire is using the memory storage for testing: 
```csharp
public static IServiceCollection AddHangfire(this IServiceCollection services)
{
    services.AddHangfire(configuration => configuration.UseMemoryStorage());
    services.AddTransient<IMonitoringApi, MemoryStorageMonitoringApi>();
    return services;
}

public static void UseHangfire(this IApplicationBuilder app)
{
    app.UseHangfireDashboard("/api/hangfire", new DashboardOptions
    {
        Authorization = new[] { new HangfireAuthorizationFilter() }
    });
    app.UseHangfireServer();
}
```

**Stacktrace**
The first test works, but Hangfire tries to access the already disposed logger on subsequent tests:
```
System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'LoggerFactory'.
   at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)
   at Hangfire.AspNetCore.AspNetCoreLogProvider.GetLogger(String name)
   at Hangfire.Logging.LogProvider.GetLogger(String name)
   at Hangfire.Server.AutomaticRetryProcess..ctor(IServerProcess innerProcess)
   at Hangfire.Server.BackgroundProcessingServer..ctor(JobStorage storage, IEnumerable`1 processes, IDictionary`2 properties, BackgroundProcessingServerOptions options)
   at Hangfire.BackgroundJobServer..ctor(BackgroundJobServerOptions options, JobStorage storage, IEnumerable`1 additionalProcesses)
   at Hangfire.HangfireApplicationBuilderExtensions.UseHangfireServer(IApplicationBuilder app, BackgroundJobServerOptions options, IEnumerable`1 additionalProcesses, JobStorage storage)
```

**Comment by MovGP0** [comment]
Solved: I was missing the `.AddSerilog()` extension on the `WebHostBuilder`: 

Instead of: 
```csharp
    var directory = Directory.GetCurrentDirectory();
    var builder = new WebHostBuilder()
        .UseContentRoot(directory)
        .UseStartup<Startup>();

    return new TestServer(builder);
```

I now use 
```csharp
    var directory = Directory.GetCurrentDirectory();
    var builder = new WebHostBuilder()
        .UseContentRoot(directory)
        .UseSerilog();
        .UseStartup<Startup>();

    return new TestServer(builder);
```
