### ISSUE TITLE
support for generic jobs

### ISSUE THREAD

**Issue by MrMuMu** [HangfireIO/Hangfire#1168]
```
public interface IJob<T> //Job interface
{
    Task Execute<U>();
}

public abstract class Job<T> : IJob<T> // base job class
{
    public async Task Execute<U>()
    {
        object item = new object();
        BackgroundJob.Enqueue<IWorkerService<U>>(x => x.WorkerTask(item));
    }
}

public class MyJob: Job<MyJob> // a job
{
    //some other stuff
}

public class MyWorkerService: IWorkerService<MyWorkerService>
{
    public async Task WorkerTask(object id)
    {
        //some implementation
    }
}

public interface IWorkerService<T>
{
    Task WorkerTask(object item);
}

// I register the class as this
services.AddScoped<IJob<MyJob>, MyJob>();
//services.AddScoped<IJob<MyJob2>, MyJob2>();
services.AddScoped<IWorkerService<MyWorkerService>, MyWorkerService>();
//services.AddScoped<IWorkerService<MyWorkerService2>, MyWorkerService2>();

// register recurring myjob as recurring job
RecurringJob.AddOrUpdate<IJob<OutboxInvoiceTaskJob>>("myJob", c => c.Execute<MyWorkerService>(), Cron.Minutely(), TimeZoneInfo.Local);
//RecurringJob.AddOrUpdate<IJob<OutboxInvoiceTaskJob>>("myJob2", c => c.Execute<MyWorkerService2>(), Cron.Minutely(), TimeZoneInfo.Local);
```

What I am trying in here is to create a base job that can be extended easily as recurring jobs and these recurring jobs create background jobs based on the given type, however I get this exception:

System.ArgumentNullException: Value cannot be null.
    at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
    at Hangfire.Common.TypeExtensions.GetNonOpenMatchingMethod(Type type, String name, Type[] parameterTypes)
    at Hangfire.Storage.InvocationData.Deserialize()

https://discuss.hangfire.io/t/recurring-job-that-executes-a-generic-type-function/4517

I get the answer from the above link that it is not supported, do you have any plans on putting this feature. It would decrease the redundant code.

**Comment by gottscj** [comment]
@MrMuMu,

It seems the validation for the job is not capturing unused generic type arguments.
Hangfire is not persisting the generic type arguments. only the argument types.

I wasn't allowed to create a PR, but if @odinserj, you added the below unit test in "InvocationDataFacts"
You would be able to reproduce the issue. I would suggest failing the job *before* being serialized as the error is thrown when trying to deserialize. (or you could persist the generic type args)

        [Fact]
        public void Deserialize_HandlesUnusedGenericTypeArgs()
        {
            var serializedData = InvocationData.Serialize(
                Job.FromExpression(() => GenericMethod<string>()));

            var job = serializedData.Deserialize();

            Assert.False(job.Type.GetTypeInfo().ContainsGenericParameters);
            Assert.Equal(typeof(string), job.Type.GetGenericArguments()[0]);
        }
        
        public static void GenericMethod<T>()
        {
            
        }
