### ISSUE TITLE
MSDTC on server 'XXX' is unavailable exception when trying to open Queues page

### ISSUE THREAD

**Issue by odinserj** [HangfireIO/Hangfire#120]
Please see the bug report: http://discuss.hangfire.io/t/msdtc-on-server-servername-is-unavailable/51

**Comment by fakhrulhilal** [comment]
I still this issue on v1.7.9. I also use [Hangfire.Console](https://github.com/pieceofsummer/Hangfire.Console). It fails when writing message to hangfire dashboard. Below is the stacktrace:
```
MSDTC on server 'COMPUTER' is unavailable.

System.Data.SqlClient.SqlException (0x80131904): MSDTC on server 'COMPUTER' is unavailable.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.TdsParser.TdsExecuteTransactionManagerRequest(Byte[] buffer, TransactionManagerRequestType request, String transactionName, TransactionManagerIsolationLevel isoLevel, Int32 timeout, SqlInternalTransaction transaction, TdsParserStateObject stateObj, Boolean isDelegateControlRequest)
   at System.Data.SqlClient.TdsParser.GetDTCAddress(Int32 timeout, TdsParserStateObject stateObj)
   at System.Data.SqlClient.SqlInternalConnectionTds.GetDTCAddress()
   at System.Data.SqlClient.SqlInternalConnection.EnlistNonNull(Transaction tx)
   at System.Data.SqlClient.SqlInternalConnection.Enlist(Transaction tx)
   at System.Data.SqlClient.SqlInternalConnection.EnlistTransaction(Transaction transaction)
   at System.Data.SqlClient.SqlConnection.EnlistTransaction(Transaction transaction)
   at Hangfire.SqlServer.SqlServerStorage.<>c__DisplayClass35_0`1.<UseTransaction>b__0(DbConnection connection)
   at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](DbConnection dedicatedConnection, Func`2 func)
   at Hangfire.SqlServer.SqlServerStorage.UseTransaction[T](DbConnection dedicatedConnection, Func`3 func, Nullable`1 isolationLevel)
   at Hangfire.SqlServer.SqlServerStorage.UseTransaction(DbConnection dedicatedConnection, Action`2 action)
   at Hangfire.SqlServer.SqlServerWriteOnlyTransaction.Commit()
   at Hangfire.Console.Storage.ConsoleStorage.AddLine(ConsoleId consoleId, ConsoleLine line)
   at Hangfire.Console.Server.ConsoleContext.AddLine(ConsoleLine line)
   at PakPos.Job.EmailImportJob.OnProcessedAction(PerformContext context, DateTime startExecutionTime, Int64 batchNumber, ReceivingAccount account, EmailImportError error, List`1 results) in C:\Sources\PakPos\PakPos.WebApi\Job\EmailImportJob.cs:line 208
   at PakPos.WebApi.Job.EmailImportJob.<>c__DisplayClass12_0.<ExecuteAsync>b__1(ReceivingAccount account, EmailImportError error, List`1 results) in C:\Sources\PakPos\PakPos.WebApi\Job\EmailImportJob.cs:line 67
   at PakPos.Domain.EmailImport.EmailImport.<>c__DisplayClass18_1.<<ExecuteAsync>b__3>d.MoveNext() in C:\Sources\PakPos\PakPos.Domain\EmailImport\EmailImport.cs:line 161
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PakPos.Domain.EmailImport.EmailImport.<ExecuteAsync>d__18.MoveNext() in C:\Sources\PakPos\PakPos.Domain\EmailImport\EmailImport.cs:line 204
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PakPos.WebApi.Job.EmailImportJob.<ExecuteAsync>d__12.MoveNext() in C:\Sources\PakPos\PakPos.WebApi\Job\EmailImportJob.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
```
Any idea how to solve this?

**Comment by icesasoftcorp** [comment]
Hi resolved this problem?
