### ISSUE TITLE
Console is already initialized

### ISSUE THREAD

**Issue by kamran-pervaiz** [HangfireIO/Hangfire#1200]
I am setting up test project and when I am running my tests I get below error.

```
System.InvalidOperationException : Console is already initialized
   at Hangfire.Console.GlobalConfigurationExtensions.UseConsole(IGlobalConfiguration configuration, ConsoleOptions options)
   at Service.Content.Reverter.WindowsService.Infrastructure.Hangfire.HangfireConfiguration.ConfigureHangfireDashboardServer(IApplicationBuilder app)
   at Service.Content.Reverter.WindowsService.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.<StartAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.TestHost.TestServer..ctor(IWebHostBuilder builder, IFeatureCollection featureCollection)
   at Microsoft.AspNetCore.TestHost.TestServer..ctor(IWebHostBuilder builder)
   at Bbc.Ww.WindowsService.IntegrationTests.API.WebserverTestsBase.BeforeEachTestBaseSetup() in C:\Projects\service-content-reverter\src\WindowsService.IntegrationTests\API\ProcessStatusControllerTests.cs:line 80

Running test with root C:\Projects\service-content-reverter\src\WindowsService
Application startup exception: System.InvalidOperationException: Console is already initialized
   at Hangfire.Console.GlobalConfigurationExtensions.UseConsole(IGlobalConfiguration configuration, ConsoleOptions options)
   at Service.Content.Reverter.WindowsService.Infrastructure.Hangfire.HangfireConfiguration.ConfigureHangfireDashboardServer(IApplicationBuilder app)
   at Service.Content.Reverter.WindowsService.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
System.InvalidOperationException: Console is already initialized
   at Hangfire.Console.GlobalConfigurationExtensions.UseConsole(IGlobalConfiguration configuration, ConsoleOptions options)
   at Service.Content.Reverter.WindowsService.Infrastructure.Hangfire.HangfireConfiguration.ConfigureHangfireDashboardServer(IApplicationBuilder app)
   at Service.Content.Reverter.WindowsService.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

I know the issue lies in below code:

`GlobalConfiguration.Configuration.UseConsole();`

but not sure what is elegant way to stop calling UseConsole() more than once. This code is written as part of HangFireConfiguration class.

**Comment by kamran-pervaiz** [comment]
I have fixed it with below code but it would be great if we have the ability to clear GlobalConfiguration for HangFire.

```
if (AlreadyConfiguredHangFireConsole) return;
            GlobalConfiguration.Configuration
                .UseConsole();
            AlreadyConfiguredHangFireConsole = true;
```

**Comment by mkwieci2** [comment]
I solved this problem by using the singleton pattern.  My singleton is called `HangfireGlobalConfiguration` and I simply call `HangfireGlobalConfiguration.GetInstance()` in my `OwinStartup` method.  Inside that class I setup sql server storage and console.

The benefits of using that pattern is you can make it thread safe and lazy, where your above code is not.

**Comment by ffMathy** [comment]
But why rely on statics in the first place? It makes it a pain to test.

**Comment by mack0196** [comment]
Is there any progress on refactoring out the static state store?

**Comment by TripleEmcoder** [comment]
Hangfire and its extensions, as useful as they are, do rely too much on static state in GlobalConfiguration.Configuration, JobStorage.Current, JobActivator.Current, causing problems when multiple IServiceCollections are initialized. The actual issue is tracked in #821, I believe.
