### ISSUE TITLE
System.MissingMethodException: Method not found: 'Void Newtonsoft.Json.JsonSerializerSettings.set_TypeNameAssemblyFormat(System.Runtime.Serialization.Formatters.FormatterAssemblyStyle)'.

### ISSUE THREAD

**Issue by hermanho** [HangfireIO/Hangfire#1217]
**Hangfire** version 1.7.0-beta1
**Newtonsoft.Json** version 11.0.3

```
Hangfire.BackgroundJobClientException: Background job creation failed. See inner exception for details. ---> System.MissingMethodException: Method not found: 'Void Newtonsoft.Json.JsonSerializerSettings.set_TypeNameAssemblyFormat(System.Runtime.Serialization.Formatters.FormatterAssemblyStyle)'.
   at Hangfire.States.AwaitingState.SerializeData()
   at Hangfire.SqlServer.SqlServerWriteOnlyTransaction.SetJobState(String jobId, IState state)
   at Hangfire.States.CoreStateMachine.ApplyState(ApplyStateContext context)
   at Hangfire.Client.CoreBackgroundJobFactory.Create(CreateContext context)
   at Hangfire.Client.BackgroundJobFactory.<>c__DisplayClass7_0.<CreateWithFilters>b__0()
   at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation)
   at Hangfire.Client.BackgroundJobFactory.Create(CreateContext context)
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
   --- End of inner exception stack trace ---
```

https://github.com/HangfireIO/Hangfire/blob/5ab7e98221b4d31480dd6c105d86635694f41781/src/Hangfire.Core/States/AwaitingState.cs#L211

Newtonsoft.Json has made a change after v10 that the property is obsoleted.

Reference https://github.com/JamesNK/Newtonsoft.Json/issues/1671

https://github.com/JamesNK/Newtonsoft.Json/blob/c4af75c8e91ca0d75aa6c335e8c106780c4f7712/Src/Newtonsoft.Json/JsonSerializerSettings.cs#L193

**Comment by pieceofsummer** [comment]
Fixed in #1151.

@odinserj this one is a show stopper for .NET Core 2.1 projects, and also .NET Core 2.0 projects explicitly referencing Newtonsoft.Json 11.x. I suggest merging this and releasing beta2 before adopting changes from `master` branch. What do you think?
