### ISSUE TITLE
System.IO.FileLoadException Can't Load Assembly?

### ISSUE THREAD

**Issue by RocherKong** [HangfireIO/Hangfire#1228]
Does anyone know why this is a problem? It has not been found for a long time.
``` c#
Failed
Can not change the state to 'Processing': target method was not found.
System.IO.FileLoadException

Could not load file or assembly 'MaiDao.TaskManager, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

System.IO.FileLoadException: Could not load file or assembly 'MaiDao.TaskManager, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'MaiDao.TaskManager, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
   at Hangfire.Storage.InvocationData.Deserialize()
```

**Comment by RocherKong** [comment]
Solved.it's a bug of hangfire.

**Comment by provanguard** [comment]
How was this solved? Was it failing all the time, or only on selected jobs?

**Comment by RocherKong** [comment]
use other db rather than redis as default db.
