### ISSUE TITLE
Execution Timeout Expired. The timeout period elapsed prior to completion of the operation or the server is not responding.

### ISSUE THREAD

**Issue by tm-peyton-dent** [HangfireIO/Hangfire#1250]
We have an issue currently with running background jobs - intermittently, they will be stuck in the Processing state until the job times out. When this happens, we can see our code running to enqueue the job, but it never actually begins the execution. It looks like the job state change is timing out. Here is the stack trace on failure:

```
System.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at Dapper.SqlMapper.ExecuteScalarImpl[T](IDbConnection cnn, CommandDefinition& command)
   at Hangfire.SqlServer.SqlServerConnection.<>c__DisplayClass11_0.<GetJobParameter>b__0(DbConnection connection)
   at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](DbConnection dedicatedConnection, Func`2 func)
   at Hangfire.SqlServer.SqlServerConnection.GetJobParameter(String id, String name)
   at Hangfire.States.ElectStateContext.GetJobParameter[T](String name)
   at Hangfire.AutomaticRetryAttribute.OnStateElection(ElectStateContext context)
   at Hangfire.States.StateMachine.ApplyState(ApplyStateContext initialContext)
   at Hangfire.States.BackgroundJobStateChanger.ChangeState(StateChangeContext context, BackgroundJob backgroundJob, IState toState, String oldStateName)
```

**Comment by matkarasiewicz** [comment]
@tm-peyton-dent What was the issue here? Did you resolve it? I have a similar problem.

**Comment by carey-bishop** [comment]
I have the same problem here too

**Comment by matkarasiewicz** [comment]
@carey-bishop Eventually for me it was related to MultipleActiveResultSets=true setting in connection string. There was a bug in EF reletaed to it but I can't find it right now.

**Comment by carey-bishop** [comment]
@MaksimSimkin That's interesting as we do set `MultipleActiveResultSets` in our connection string, so I'll see if we can take that out. Thanks
