### ISSUE TITLE
Antiforgery Error

### ISSUE THREAD

**Issue by poumup** [HangfireIO/Hangfire#1293]
With package 1.6.20 in .net core 2.1. 
I run my app in 3 hangfire servers containers.
When the conatiner start, i have this error : 

`fail: Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery[7]
      An exception was thrown while deserializing the token.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted. ---> System.Security.Cryptography.CryptographicException: The key {c9565b76-6df6-4bd0-a634-967e93a0d08c} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)`

**Comment by pieceofsummer** [comment]
Have you configured your containers to use identical keys for Data Protection, as stated in [documentation](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-2.1&tabs=aspnetcore2x#persisting-keys-when-hosting-in-a-docker-container)?

**Comment by poumup** [comment]
Thank

**Comment by ClementeGao** [comment]
@pieceofsummer  how configured containers to use identical keys for data protection
