### ISSUE TITLE
This SqlTransaction has completed; it is no longer usable.

### ISSUE THREAD

**Issue by vbenedichuk** [HangfireIO/Hangfire#1304]
Application works with Azure SQL.
At some point hangfire fails with following errors:

```
2018-11-21 06:02:35.6082 +00:00||ERROR|Hangfire.Server.Worker|An exception occurred while processing a job. It will be re-queued. System.InvalidOperationException: This SqlTransaction has completed; it is no longer usable.
   at System.Data.SqlClient.SqlTransaction.ZombieCheck()
   at System.Data.SqlClient.SqlTransaction.Commit()
   at Hangfire.SqlServer.SqlServerTransactionJob.RemoveFromQueue()
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
2018-11-21 06:02:35.6082 +00:00||WARN|Hangfire.Server.Worker|Failed to immediately re-queue the background job '249'. Next invocation may be delayed, if invisibility timeout is used System.InvalidOperationException: This SqlTransaction has completed; it is no longer usable.
   at System.Data.SqlClient.SqlTransaction.ZombieCheck()
   at System.Data.SqlClient.SqlTransaction.Rollback()
   at Hangfire.SqlServer.SqlServerTransactionJob.Requeue()
   at Hangfire.Server.Worker.Requeue(IFetchedJob fetchedJob)
2018-11-21 06:02:35.6132 +00:00||DEBUG|Hangfire.Server.Worker|Error occurred during execution of 'Worker #f219e7a3' process. Execution will be retried (attempt #1) in 00:00:01 seconds. System.InvalidOperationException: This SqlTransaction has completed; it is no longer usable.
   at System.Data.SqlClient.SqlTransaction.ZombieCheck()
   at System.Data.SqlClient.SqlTransaction.Commit()
   at Hangfire.SqlServer.SqlServerTransactionJob.RemoveFromQueue()
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)```

**Comment by vbenedichuk** [comment]
Hangfire version 1.6.21

**Comment by odinserj** [comment]
Thanks for reporting this, @vbenedichuk. There should be some more checks to prevent double-commit of the `SqlServerTransactionJob` instance.

**Comment by mattkwiecien** [comment]
@odinserj Just created a PR to fix this based on your comment.
