### ISSUE TITLE
Random deadlock issues and sql timeouts created by hangfire queries

### ISSUE THREAD

**Issue by gertgjoka** [HangfireIO/Hangfire#1307]
Hello, 

we are intermittently getting timeouts and our web application becomes unavailable  until we forcly restart it. Each time it happens we notice that hangfire queries are the culprit as they are the only ones running at that time (checking with transaction lock queries). 

This is one of the queries which is there locked
`(@queues1 nvarchar(4000),@queues2 nvarchar(4000),@queues3 nvarchar(4000),@queues4 nvarchar(4000),@queues5 nvarchar(4000),@queues6 nvarchar(4000),@timeout float)delete top (1) JQ output DELETED.Id, DELETED.JobId, DELETED.Queue FROM [HangFire].JobQueue JQ WITH (READPAST, UPDLOCK, ROWLOCK, FORCESEEK) WHERE Queue IN (@queues1,@queues2,@queues3,@queues4,@queues5,@queues6) AND (FetchedAt IS NULL OR FetchedAt < DATEADD(SECOND, @timeout, GETUTCDATE()))`

Another logged error is:
```
Failed to process the job '18495': an exception occurred. Retry attempt 1 of 15 will be performed in 00:00:33.
 Hangfire.Storage.DistributedLockTimeoutException: Timeout expired. The timeout elapsed prior to obtaining a distributed lock on the 'HangFire:WebTaskFramework.TaskExecutionHandler' resource.
 at Hangfire.SqlServer.SqlServerDistributedLock.Acquire(IDbConnection connection, String resource, TimeSpan timeout)
 at Hangfire.SqlServer.SqlServerConnection.AcquireLock(String resource, TimeSpan timeout)
 at Hangfire.SqlServer.SqlServerConnection.AcquireDistributedLock(String resource, TimeSpan timeout)
 at Hangfire.DisableConcurrentExecutionAttribute.OnPerforming(PerformingContext filterContext)
 at Hangfire.Server.BackgroundJobPerformer.InvokePerformFilter(IServerFilter filter, PerformingContext preContext, Func`1 continuation).
```
This is what we get when our web app is locked and each request fails, and only resumes afet restart
`Timeout expired. The timeout period elapsed prior to obtaining a connection from the pool. This may have occurred because all pooled connections were in use and max pool size was reached.`

We are on latest hangfire libraries.
Thanks!

**Comment by odinserj** [comment]
Try to use the new fetching implementation available since the release of the 1.6.14 version (will be default in 1.7.0) as shown below. It doesn't use long-running transactions and doesn't cause a connection to be consumed while background job is executed.

```csharp
GlobalConfiguration.Configuration
    .UseSqlServerStorage("connection_string", new SqlServerStorageOptions
    {
        SlidingInvisibilityTimeout = TimeSpan.FromMinutes(5)
    })
```

Or you can simply increase the connection pool size to fit your scenario. By default there are 100 connections maximum, but you can increase it to a larger value.

```csharp
var connectionString = "server=localhost;database=mydb;Max Pool Size=200;";
```

**Comment by gertgjoka** [comment]
Thanks for your help. I applied both of your hints, and waited for some days to check the longer term change.

We are still getting timeouts and exceptions related to hangfire:
`Timeout expired. The timeout period elapsed prior to obtaining a connection from the pool. This may have occurred because all pooled connections were in use and max pool size was reached.`

`Failed to process the job '59371': an exception occurred. Retry attempt 1 of 15 will be performed in 00:00:27.
 Hangfire.Storage.DistributedLockTimeoutException: Timeout expired. The timeout elapsed prior to obtaining a distributed lock on the 'HangFire:WebTaskFramework.TaskExecutionHandler' resource.
 at Hangfire.SqlServer.SqlServerDistributedLock.Acquire(IDbConnection connection, String resource, TimeSpan timeout)
 at Hangfire.SqlServer.SqlServerConnection.AcquireLock(String resource, TimeSpan timeout)
 at Hangfire.SqlServer.SqlServerConnection.AcquireDistributedLock(String resource, TimeSpan timeout)
 at Hangfire.DisableConcurrentExecutionAttribute.OnPerforming(PerformingContext filterContext)
 at Hangfire.Server.BackgroundJobPerformer.InvokePerformFilter(IServerFilter filter, PerformingContext preContext, Func`1 continuation)`

**Comment by gertgjoka** [comment]
As a side note, now I identify this query of Hangfire staying asleep for several minutes:

`(@queues1 nvarchar(4000),@queues2 nvarchar(4000),@queues3 nvarchar(4000),@queues4 nvarchar(4000),@queues5 nvarchar(4000),@queues6 nvarchar(4000),@timeout float)
set transaction isolation level read committed
update top (1) JQ
set FetchedAt = GETUTCDATE()
output INSERTED.Id, INSERTED.JobId, INSERTED.Queue
from [HangFire].JobQueue JQ with (readpast, updlock, rowlock, forceseek)
where Queue in (@queues1,@queues2,@queues3,@queues4,@queues5,@queues6) and
(FetchedAt is null or FetchedAt < DATEADD(second, @timeout, GETUTCDATE()))`

**Comment by odinserj** [comment]
If you still encounter this problem, try increasing the connection pool size by adding the following line to your connection string. Looks like you are using large number of workers, and hit the limit with the default pool size (100 connections).

```csharp
UseSqlServerStorage("Database=...;Max Pool Size=200");
```

**Comment by gertgjoka** [comment]
I have already done that since you first recommended it to me. Right now I have it set to 200.

**Comment by sopatel** [comment]
Hello,
We are also facing the same issue with our product, currently we are in 1.6.17.0. Is there any alternative fix which we can suggest to our customer. Apart form upgrade to 1.7.0.. as our product is already in production.
