### ISSUE TITLE
Hangfire Dashboard: Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException

### ISSUE THREAD

**Issue by dzduniak** [HangfireIO/Hangfire#1357]
Hangfire Dashboard background AJAX call to "http://HOST_NAME/APP_NAME/hangfire/stats" fails with code 500 (Internal Server Error). The same is also true for other AJAX calls (like manual task triggering button).
.NET Core application throws the following exception:

```
Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery:Error: An exception was thrown while deserializing the token.

Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted. ---> System.Security.Cryptography.CryptographicException: The key {8689ba02-7f31-4d3f-8e2a-330dcfb2e72b} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery:Error: An exception was thrown while deserializing the token.
```

When browsing from the local host the exception does not occur (AJAX calls complete successfully).

**Comment by odinserj** [comment]
This may be caused by switch to the different server in load balanced scenarios. Have you seen https://github.com/aspnet/AspNetCore/issues/3540?

**Comment by dzduniak** [comment]
Will look at it at work, tomorrow. The thing is I’m not using a load balancer just a single instance hosted with IIS.
Still maybe it will help...

**Comment by dzduniak** [comment]
Weird, tested on other user's computer - noticed that problem is not occurring... Cleared my browser cache and it fixed the issue for me as well.
Oh well, sorry for bothering you and thank you.

**Comment by iberodev** [comment]
I am having the same problem.
In local my application works fine and I'm able to see the UI at /hangfire
When I deploy to AWS (with OpenShift in a linux-containerized app in case that's relevant somehow) I get the same error.
Just one node.

**Comment by Jeff-Tian** [comment]
Worked locally but met the same issue when deployed to k8s with multiple pods running. By keeping only 1 pod running fixed the issue (Workround).
