### ISSUE TITLE
500 (Internal Server Error)

### ISSUE THREAD

**Issue by zsy619** [HangfireIO/Hangfire#1367]
call tengxin-jobs/jobs/actions/delete/505331 500 (Internal Server Error)

<TargetFramework>netcoreapp2.2</TargetFramework>
    <PackageReference Include="Hangfire.AspNetCore" Version="1.6.22" />
    <PackageReference Include="Hangfire.Console" Version="1.4.2" />
    <PackageReference Include="Hangfire.Core" Version="1.6.22" />

**Comment by zsy619** [comment]
<TargetFramework>netcoreapp2.2</TargetFramework>
    <PackageReference Include="Hangfire.AspNetCore" Version="1.6.22" />

**Comment by zsy619** [comment]
"Hangfire.AspNetCore" "1.6.22"

**Comment by zsy619** [comment]
call: /tengxin-jobs/jobs/actions/delete/1
result: This page isn’t working If the problem continues, contact the site owner.
HTTP ERROR 405

**Comment by zsy619** [comment]
@atifaziz help me

**Comment by odinserj** [comment]
We couldn't tell you anything regarding this generic exception without more details. At least you can add ASP.NET Core's `UseErrorPage` method call before registering the dashboard to get complete stack traces on errors to see what exactly happened.

**Comment by zsy619** [comment]
@odinserj hello, hangfire.mysql.core：：：
MySql.Data.MySqlClient.MySqlException (0x80004005): The table does not comply with the requirements by an external plugin.
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in C:\projects\dapper\Dapper\SqlMapper.cs:line 2836
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in C:\projects\dapper\Dapper\SqlMapper.cs:line 570
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 443
   at Hangfire.MySql.Core.MySqlDistributedLock.AcquireLock(String resource, TimeSpan timeout) in E:\sms2018\Hangfire.MySql.Core\Hangfire.MySql\MySqlDistributedLock.cs:line 56
   at Hangfire.MySql.Core.MySqlDistributedLock.Acquire() in E:\sms2018\Hangfire.MySql.Core\Hangfire.MySql\MySqlDistributedLock.cs:line 93
   at Hangfire.MySql.Core.MySqlStorageConnection.AcquireDistributedLock(String resource, TimeSpan timeout) in E:\sms2018\Hangfire.MySql.Core\Hangfire.MySql\MySqlStorageConnection.cs:line 35
   at Hangfire.RecurringJobExtensions.AcquireDistributedRecurringJobLock(IStorageConnection connection, String recurringJobId, TimeSpan timeout)
   at Hangfire.RecurringJobManager.AddOrUpdate(String recurringJobId, Job job, String cronExpression, RecurringJobOptions options)
   at Hangfire.RecurringJobManagerExtensions.AddOrUpdate(IRecurringJobManager manager, String recurringJobId, Job job, String cronExpression, TimeZoneInfo timeZone, String queue)
   at Hangfire.RecurringJob.AddOrUpdate(Expression`1 methodCall, String cronExpression, TimeZoneInfo timeZone, String queue)
   at TxSms.Timed.Startup.<>c.<Configure>b__1_81(HttpContext context) in E:\sms2018\TxSms.DP\src\TxSms.Timed\Startup.cs:line 464

**Comment by zsy619** [comment]
private int AcquireLock(string resource, TimeSpan timeout)
        {
            return
                _connection
                    .Execute(
                        $"INSERT INTO {_options.TablePrefix}_DistributedLock (Resource, CreatedAt) " +
                        "  SELECT @resource, @now " +
                        "  FROM dual " +
                        "  WHERE NOT EXISTS ( " +
                        $"  		SELECT * FROM {_options.TablePrefix}_DistributedLock " +
                        "     	WHERE Resource = @resource " +
                        "       AND CreatedAt > @expired)", 
                        new
                        {
                            resource,
                            now = DateTime.UtcNow, 
                            expired = DateTime.UtcNow.Add(timeout.Negate())
                        });
        }

想请教一下，这个方法是什么作用，而且这个表dual在库里也不存在

**Comment by odinserj** [comment]
This error is related to `MySqlClient` itself, don't know what advice to give you other than report at least to `Hangfire.MySql` repository, but its URL depends on the package you are using (since there are multiple Hangfire.MySql packages on NuGet). 

```
at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
```

**Comment by capcom923** [comment]
> ```
>     private int AcquireLock(string resource, TimeSpan timeout)
>     {
>         return
>             _connection
>                 .Execute(
>                     $"INSERT INTO {_options.TablePrefix}_DistributedLock (Resource, CreatedAt) " +
>                     "  SELECT @resource, @now " +
>                     "  FROM dual " +
>                     "  WHERE NOT EXISTS ( " +
>                     $"  		SELECT * FROM {_options.TablePrefix}_DistributedLock " +
>                     "     	WHERE Resource = @resource " +
>                     "       AND CreatedAt > @expired)", 
>                     new
>                     {
>                         resource,
>                         now = DateTime.UtcNow, 
>                         expired = DateTime.UtcNow.Add(timeout.Negate())
>                     });
>     }
> ```
> 
> 想请教一下，这个方法是什么作用，而且这个表dual在库里也不存在

dual is just a key word in mySql but not a real table. The only use is to provide a  something after the from clause to make the syntax correct. you can execute select 1 from dual where 1=1.

**Comment by capcom923** [comment]
I fixed this same error after debugging 4 hours.

You need to recreate the distributedlock with a PRIMARY KEY as below SQL.

CREATE TABLE `hangfire.distributedlock` (
  `Resource` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `CreatedAt` datetime(6) NOT NULL,
  PRIMARY KEY (`Resource`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

The reason why you got that error is that your mysql server does not allow insert value to a table without key.
However, the Hangfire.MySqlStorage just hit this bomb.

Happy coding
