### ISSUE TITLE
1.7.0-RC2 - .Net Framework 4.7.1 Issue

### ISSUE THREAD

**Issue by twurm** [HangfireIO/Hangfire#1381]
We've run into an issue with 1.7.0-RC2 and .Net Framework 4.7.1.  We have an application that can either run as a .Net Standard 2.2 Console application or .Net Framework 4.7.1 Windows Service.  The Console application runs fine and does exactly what we expect.  

The Windows Service on the other hand fails to start with the following exception:

```
Service cannot be started. System.MissingMethodException: Method not found: 'Void Hangfire.SqlServer.SqlServerStorageOptions.set_TransactionIsolationLevel(System.Nullable`1<System.Data.IsolationLevel>)'.
   at Mx.DataLoad.Server.App.ConfigureServices(ServiceRegistry services)
   at Mx.DataLoad.Server.App.Start(String instanceName) in C:\Agent\_work\4\s\src\Mx.DataLoad\Server\App.cs:line 107
   at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)
```

### Configuration
```csharp
// configure hangfire sql server storage
GlobalConfiguration.Configuration.UseSqlServerStorage(mxConnectionString, new SqlServerStorageOptions
   {
      SlidingInvisibilityTimeout = TimeSpan.FromMinutes(5), // To enable Sliding invisibility fetching
      CommandBatchMaxTimeout = TimeSpan.FromMinutes(5), // To enable command pipelining
      QueuePollInterval = TimeSpan.Zero // To reduce processing delays to minimum
      TransactionIsolationLevel = IsolationLevel.ReadCommitted
   });
GlobalConfiguration.Configuration.UseFilter(new PreserveOriginalQueueAttribute());
GlobalConfiguration.Configuration.SetDataCompatibilityLevel(CompatibilityLevel.Version_170);
GlobalConfiguration.Configuration.UseRecommendedSerializerSettings();
```

```xml
<PackageReference Include="HangFire.Core" Version="1.7.0-rc2" />
<PackageReference Include="Hangfire.Heartbeat" Version="0.3.4" />
<PackageReference Include="Hangfire.Lamar" Version="1.0.0" />
<PackageReference Include="HangFire.SqlServer" Version="1.7.0-rc2" />
```

**Comment by odinserj** [comment]
Thanks for reporting this! Please upgrade to version 1.7.0 and use `UseRecommendedIsolationLevel` option instead of `TransactionIsolationLevel`:

```csharp
GlobalConfiguration.Configuration.UseSqlServerStorage(mxConnectionString, new SqlServerStorageOptions
   {
      SlidingInvisibilityTimeout = TimeSpan.FromMinutes(5), // To enable Sliding invisibility fetching
      CommandBatchMaxTimeout = TimeSpan.FromMinutes(5), // To enable command pipelining
      QueuePollInterval = TimeSpan.Zero // To reduce processing delays to minimum
      UseRecommendedIsolationLevel = true
   });
```

By the way, you can chain multiple calls to configuration together:

```csharp
GlobalConfiguration.Configuration
    .SetDataCompatibilityLevel(...)
    .UseSqlServerStorage(...)
    .UseFilter(new PreserveOriginalQueueAttribute());
    .SetDataCompatibilityLevel(CompatibilityLevel.Version_170);
    .UseRecommendedSerializerSettings();
```
