### ISSUE TITLE
Scheduled jobs fail randomly with System.IO.FileLoadException

### ISSUE THREAD

**Issue by provanguard** [HangfireIO/Hangfire#1395]
On my development environment there are scheduled jobs randomly failing with the error below:

```
System.IO.FileLoadException
Could not load file or assembly 'DeploymentCore, Version=1.0.273.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

System.IO.FileLoadException: Could not load file or assembly 'DeploymentCore, Version=1.0.273.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'DeploymentCore, Version=1.0.273.0, Culture=neutral, PublicKeyToken=null'
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
   at Hangfire.Storage.InvocationData.DefaultTypeResolver(String typeName)
   at Hangfire.Storage.InvocationData.Deserialize()
```
Around 600 out of 1600 jobs failed in this way. Around 300 out of the failed 600 managed to get success on the second attempt. So all in all there is around 300 out of 1600 that failed.

I am on Hangfire version 1.6.22. Also tried 1.6.23 and 1.6.24, without improvement. I am using Hangfire.Mongo for database access. The database was cleared. The dll is there with the expected version. The solution is running dotnet core 2.2 in Azure Web Apps for Containers.
My production environment is running stable, on the same version as development, 1.6.22.

Any input will be appreciated.

**Comment by odinserj** [comment]
Try to upgrade to Hangfire 1.7.0, and if it doesn't help, ensure that multiple code bases don't use the same job storage.

**Comment by provanguard** [comment]
The error went away, after ensuring that only one instance of the application accesses the database. From that perspective, are mutliple servers (as visible on the dashboard) really supported?

**Comment by odinserj** [comment]
They are supported, but all of them should have access to the same code base. You can use multiple applications, but put code that relate to background jobs to a shared assembly. Better isolation will be supported to use the same storage for multiple applications, but not now.

**Comment by provanguard** [comment]
OK. Then the issue can be closed I suppose.
