### ISSUE TITLE
Intermittent object null exception

### ISSUE THREAD

**Issue by styxington** [HangfireIO/Hangfire#1494]
We have a newly set up Hangfire BackgroundJobServer running inside a Windows Service (using .NET Core).  Our data is in SQL Server.

This is to support a new system which is not yet being used, so the service is just sitting there with no jobs to process.

We are intermittently - once every 2 or 3 days - getting the following exceptions from the service:

```
Execution Worker is in the Failed state now due to an exception, execution will be retried no more than in 00:00:04
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Data.SqlClient.SqlInternalTransaction.Rollback()
   at System.Data.SqlClient.SqlTransaction.Dispose(Boolean disposing)
   at Hangfire.SqlServer.SqlServerJobQueue.DequeueUsingTransaction(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.BackgroundProcessDispatcherBuilder.ExecuteProcess(Guid executionId, Object state)
   at Hangfire.Processing.BackgroundExecution.Run(Action`2 callback, Object state)"
```

I have tried searching for other people with a similar issue but have yet to find anything helpful.   Does anyone have any ideas as to why this may be happening?

**Comment by odinserj** [comment]
Exception is appearing somewhere in the `SqlInternalTransaction` class. Try upgrading `System.Data.SqlClient` version to the latest version and let us know if it helps.

**Comment by styxington** [comment]
Thank you for your quick reply.  
We have been using System.Data.SqlClient 4.6.1 which is the latest available via Visual Studio NuGet.   There was a small upgrade of the Hangfire dlls, from 1.7.3 to 1.7.6, available so I have changed those.  Sadly we haven't yet spotted a way of forcing the error, so we just have to wait and see if it happens again.

**Comment by odinserj** [comment]
After a quick search, I've found a similar issue described here – https://github.com/aspnet/EntityFrameworkCore/issues/12864 – but without any resolution.

**Comment by styxington** [comment]
Thanks again.  Just for information, we are still getting the error, even with everything on the latest versions.  For the time being we are not noticing any related issues from the error occurring, we would just prefer to understand why, and stop it happening, but need to focus on other things in the short term.

**Comment by ljfraney** [comment]
Any word on this? I'm hosting Hangfire in a .Net Core 3.1 Worker process. I'm using Hangfire.SqlServer 1.7.11 and System.Data.SqlClient 4.8.1, and I'm seeing this issue every time an exception bubbles up (i.e. every time a job fails). I can wrap everything in Try...Catch... but then it will appear that the job succeeded, which isn't ideal. If no solution, is there a good workaround for this?
`System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.Data.SqlClient
  StackTrace:
   at Microsoft.Data.SqlClient.SqlInternalTransaction.Rollback()`

**Comment by odinserj** [comment]
@ljfraney what's the full stack trace of this exception?

**Comment by ljfraney** [comment]
@odinserj Unfortunately, that is the entire StackTrace.
`($exception).StackTrace = "   at Microsoft.Data.SqlClient.SqlInternalTransaction.Rollback()"`

**Comment by ljfraney** [comment]
@odinserj Disregard this. The transaction that was being rolled back turned out to be a different connection than Hangfire. The symptoms were oddly similar, but it was a total red herring. I appreciate the time you took to look at it.

**Comment by jasonslemons** [comment]
I have seen this error as well, similar stack trace but not exactly the same. and its from a server that shouldnt be doing any jobs.
Id Date Thread Level Logger Message Exception Source HostName
27767524 2020-12-06 19:33:04.207 Worker #4 DEBUG Hangfire.Processing.BackgroundExecution Execution Worker is in the Faulted state now due to an exception, execution will be retried no more than in 00:00:01 System.Data.DataException: Error parsing column 1 (JobId=0 - Int32) ---> System.InvalidCastException: Specified cast is not valid.
   at Deserialize285fb3b6-a730-48e2-8df8-e2a63b08ebd1(IDataReader )
   --- End of inner exception stack trace ---
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value)
   at Deserialize285fb3b6-a730-48e2-8df8-e2a63b08ebd1(IDataReader )
   at Dapper.SqlMapper.GridReader.<ReadDeferred>d__52`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.GridReader.ReadImpl[T](Type type, Boolean buffered)
   at Hangfire.SqlServer.SqlServerJobQueue.<>c__DisplayClass9_0.<DequeueUsingSlidingInvisibilityTimeout>b__1(DbConnection connection)
   at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](DbConnection dedicatedConnection, Func`2 func)
   at Hangfire.SqlServer.SqlServerJobQueue.DequeueUsingSlidingInvisibilityTimeout(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.BackgroundProcessDispatcherBuilder.ExecuteProcess(Guid executionId, Object state)
   at Hangfire.Processing.BackgroundExecution.Run(Action`2 callback, Object state) API ACANC-IISP3
