### ISSUE TITLE
Hangfire 1.7.x Can not find the target method.

### ISSUE THREAD

**Issue by schmitch** [HangfireIO/Hangfire#1512]
Currently I get the following error when upgrading from 1.6.27 to 1.7.x:

```
System.ArgumentNullException

Value cannot be null. Parameter name: values

System.ArgumentNullException: Value cannot be null.
Parameter name: values
   at System.String.Join(String separator, IEnumerable`1 values)
   at Hangfire.Storage.InvocationData.DeserializeJob()
```

Currently these methods work on 1.6.x:
```
    [AutomaticRetry(Attempts = 0)]
    public class MailJob
    {
        private readonly SharedMailerClient _sharedMailerClient;

        public MailJob(SharedMailerClient sharedMailerClient)
        {
            _sharedMailerClient = sharedMailerClient;
        }

        public async Task CallFull(int clientId, int documentId, NotificationType type, int? userId)
        {
            await _sharedMailerClient.CreateAndSendFullMailAsync(clientId, documentId, type, userId);
        }

        public async Task CallSystem<T>(Guid? guid, int clientId, T mail)
            where T : ISystemMail
        {
            await _sharedMailerClient.CreateAndSendSystemMailAsync(guid, clientId, mail);
        }
    }
```
Called via:
- `BackgroundJob.Enqueue<MailJob>(mj => mj.CallFull(clientId, documentId, type, userId));`
- ` BackgroundJob.Enqueue<MailJob>(mj => mj.CallSystem(guid, clientId, mail));`

I'm using the following dependencies 1.6.27:
- Hangfire.Core 1.6.27
- Hangfire.AspNetCore 1.6.27
- Hangfire.PostgreSql.ahydrax 1.6.1.1

I'm using the following dependencies 1.7.x:
- Hangfire.Core 1.7.6
- Hangfire.AspNetCore 1.7.6
- Hangfire.PostgreSql.ahydrax 1.7.0

Hangfire is registered with:
```
            app.UseHangfireServer(new BackgroundJobServerOptions
            {
                ServerName = $"{Environment.MachineName}-Background",
                Activator = new AspNetCoreJobActivator(app.ApplicationServices.GetService<IServiceScopeFactory>()),
            });

            var options = new DashboardOptions
            {
                Authorization = new[]
                {
                    app.ApplicationServices.GetService<DashboardAuthorizationFilter>(),
                },
            };

            app.UseHangfireDashboard(options: options);
```

and

```
            GlobalConfiguration.Configuration.UseDashboardMetric(PostgreSqlDashboardMetrics.MaxConnections);
            GlobalConfiguration.Configuration.UseDashboardMetric(PostgreSqlDashboardMetrics.ActiveConnections);
            GlobalConfiguration.Configuration.UseDashboardMetric(PostgreSqlDashboardMetrics.DistributedLocksCount);
            GlobalConfiguration.Configuration.UseDashboardMetric(PostgreSqlDashboardMetrics.PostgreSqlLocksCount);
            GlobalConfiguration.Configuration.UseDashboardMetric(PostgreSqlDashboardMetrics.PostgreSqlServerVersion);
            GlobalConfiguration.Configuration.UseDashboardMetric(PostgreSqlDashboardMetrics.ConnectionUsageRatio);
            services.AddHangfire(config =>
            {
                config.UsePostgreSqlStorage(
                    $"{connectionString};Maximum Pool Size=10;Search Path = {Constants.HangfireSchemaName};Application Name=Finder.Hangfire",
                    new PostgreSqlStorageOptions { InvisibilityTimeout = TimeSpan.FromDays(1.0) });
            });
            services.AddTransient<DashboardAuthorizationFilter>();
```

**Comment by Azhe403** [comment]
up, same issue

**Comment by vblain** [comment]
same issue here

**Comment by jeancasulo** [comment]
same issue here

**Comment by odinserj** [comment]
I still can't reproduce the issue, may be because of missing configuration logic for serialization, such as `JobHelper.SetSerializerSettings` method call and missing source code for `NotificationType` type. The best way is to create a repository with two projects, one of which targets 1.6.X (creates jobs) and other one targets 1.7.X (spawns a server).

**Comment by odinserj** [comment]
And the best way to understand what's going on is to also provide contents of the corresponding record in the database.
