### ISSUE TITLE
HostBuilder setup with .net core 2.2 console app to run hangfire server to process jobs

### ISSUE THREAD

**Issue by netbitshift** [HangfireIO/Hangfire#1524]
I seen this issue, but I don't understand the solution, as it mentions calling .Configure() yet there is no such method on HostBuilder.  
https://github.com/HangfireIO/Hangfire/issues/1303

Likewise, I am in the same spot, trying to setup Hangfire server from within a .net core console app, which is to run as a windows service.

Its fairly straightforward when using both the server and client within a asp.net core web app, but not so when pulling the server over into a .net core console app.

 There is a method in the "BusinessMgr" class that is setup via a web app where its setup as a scheduled job, eg.<br/>
In Startup.cs
`    RecurringJob.AddOrUpdate<IBusinessMgrJob>("BusinessMgr", j => j.RunOrder(), GetJobSchedule("BusinessMgr"), TimeZoneInfo.Local);`

Below is the 'Main method in the console app.
```
private static async Task Main(string[] args)
        {
            var isService = !(Debugger.IsAttached || args.Contains("--console"));

            var hostBuilder = new HostBuilder()
             .ConfigureHostConfiguration(configHost => { configHost.AddCommandLine(args); })
             .ConfigureAppConfiguration((hostingContext, config) =>
             {

                 var env = hostingContext.HostingEnvironment;
                 config.AddCommandLine(args);
                 config.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true);
             })
             .ConfigureServices((hostContext, services) =>
             {
                 //Inject additional services as needed
                 services.AddSingleton(Log.Logger);
                 services.AddHostedService<JobRunner>();
                 services.AddScoped<IBusinessMgr, BusinessMgr>();
                 string JobsDbConStr = "my-db-conn-string-here";
                 services.AddHangfire(c => c.UseSqlServerStorage(JobsDbConStr));
                 services.AddHangfireServer();
             });
             
             
            if (isService)
            {
                await hostBuilder.RunAsServiceAsync();
            }
            else
            {
                await hostBuilder.RunConsoleAsync();
            }
        }   
```

The actual jobs are scheduled via a .net core web app, but when I startup a job via the dashboard, the service blows chunks and I get an exception.

```
Cannot create an instance of an interface.
System.MissingMethodException: Cannot create an instance of an interface.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at Hangfire.JobActivator.ActivateJob(Type jobType)
   at Hangfire.JobActivator.SimpleJobActivatorScope.Resolve(Type type)
   at Hangfire.Server.CoreBackgroundJobPerformer.Perform(PerformContext context)
   at Hangfire.Server.BackgroundJobPerformer.<>c__DisplayClass9_0.<PerformJobWithFilters>b__0()
   at Hangfire.Server.BackgroundJobPerformer.InvokePerformFilter(IServerFilter filter, PerformingContext preContext, Func`1 continuation)
   at Hangfire.Server.BackgroundJobPerformer.<>c__DisplayClass9_1.<PerformJobWithFilters>b__2()
   at Hangfire.Server.BackgroundJobPerformer.PerformJobWithFilters(PerformContext context, IEnumerable`1 filters)
   at Hangfire.Server.BackgroundJobPerformer.Perform(PerformContext context)
   at Hangfire.Server.Worker.PerformJob(BackgroundProcessContext context, IStorageConnection connection, String jobId)
```

**Comment by pieceofsummer** [comment]
It feels like the wrong activator is used for some reason. Try adding `services.AddSingleton<JobActivator, AspNetCoreJobActivator>();` and see if it helps.
