### ISSUE TITLE
The required antiforgery cookie token must be provided. Parameter name: cookieToken

### ISSUE THREAD

**Issue by ClementeGao** [HangfireIO/Hangfire#1538]
System.ArgumentNullException: The required antiforgery cookie token must be provided.
Parameter name: cookieToken
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenGenerator.TryValidateTokenSet(HttpContext httpContext, AntiforgeryToken cookieToken, AntiforgeryToken requestToken, String& message)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.IsRequestValidAsync(HttpContext httpContext)
   at Hangfire.Dashboard.AspNetCoreDashboardMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by ClementeGao** [comment]
@dsincl12  can you see this question

**Comment by kg6zgj** [comment]
This is an issue for me too. any work arounds yet?
