### ISSUE TITLE
ContinueWithJob fails: Input string was not in a correct format

### ISSUE THREAD

**Issue by sommmen** [HangfireIO/Hangfire#1574]
Hi guys, i can't wrap my head around this exception:

I am running version hangfire 1.7.7 with hangfire.sqlserver

```
Input string was not in a correct format.

   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt64(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int64.Parse(String s)
   at Hangfire.SqlServer.SqlServerConnection.<>c__DisplayClass11_0.<GetJobParameter>b__0(DbConnection connection)
   at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](DbConnection dedicatedConnection, Func`2 func)
   at Hangfire.SqlServer.SqlServerConnection.GetJobParameter(String id, String name)
   at Hangfire.ContinuationsSupportAttribute.GetContinuations(IStorageConnection connection, String jobId)
   at Hangfire.ContinuationsSupportAttribute.AddContinuation(ElectStateContext context, AwaitingState awaitingState)
   at Hangfire.ContinuationsSupportAttribute.OnStateElection(ElectStateContext context)
   at Hangfire.States.StateMachine.<>c__DisplayClass4_0.<ApplyState>b__0(IElectStateFilter x)
   at Hangfire.Profiling.ProfilerExtensions.InvokeAction[TInstance](InstanceAction`1 tuple)
   at Hangfire.Profiling.EmptyProfiler.InvokeMeasured[TInstance,TResult](TInstance instance, Func`2 action, String message)
   at Hangfire.Profiling.ProfilerExtensions.InvokeMeasured[TInstance](IProfiler profiler, TInstance instance, Action`1 action, String message)
   at Hangfire.States.StateMachine.ApplyState(ApplyStateContext initialContext)
   at Hangfire.Client.CoreBackgroundJobFactory.<>c__DisplayClass14_0.<Create>b__3(Int32 attempt)
   at Hangfire.Client.CoreBackgroundJobFactory.<>c__DisplayClass15_0.<RetryOnException>b__0(Int32 attempt)
   at Hangfire.Client.CoreBackgroundJobFactory.RetryOnException[T](Int32& attemptsLeft, Func`2 action)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Hangfire.Client.CoreBackgroundJobFactory.RetryOnException[T](Int32& attemptsLeft, Func`2 action)
   at Hangfire.Client.CoreBackgroundJobFactory.RetryOnException(Int32& attemptsLeft, Action`1 action)
   at Hangfire.Client.CoreBackgroundJobFactory.Create(CreateContext context)
   at Hangfire.Client.BackgroundJobFactory.<>c__DisplayClass12_0.<CreateWithFilters>b__0()
   at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation)
   at Hangfire.Client.BackgroundJobFactory.<>c__DisplayClass12_1.<CreateWithFilters>b__2()
   at Hangfire.Client.BackgroundJobFactory.CreateWithFilters(CreateContext context, IEnumerable`1 filters)
   at Hangfire.Client.BackgroundJobFactory.Create(CreateContext context)
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
```

Pops up at this line:

                var continueJobWith = BackgroundJob.ContinueJobWith<RemoteDataFilePuller>(HangfireJobIdRegistry.FilePullingRecurring, puller => puller.OnProcessedAllEwonsSuccessfullyHook(), JobContinuationOptions.OnlyOnSucceededState);

Extra info:
HangfireJobIdRegistry.FilePullingRecurring gives the string "FilePullingRecurring" which revers to a recurring job
Following SQL gets executed succesfully:
```
exec sp_executesql N'
set xact_abort on; set nocount on; declare @jobId bigint;
begin tran;
insert into [HangFire].Job (InvocationData, Arguments, CreatedAt, ExpireAt) values (@invocationData, @arguments, @createdAt, @expireAt);
select @jobId = scope_identity(); select @jobId;
insert into [HangFire].JobParameter (JobId, Name, Value) values (@jobId, @name1, @value1), (@jobId, @name2, @value2);
commit tran;',N'@invocationData nvarchar(max) ,@arguments nvarchar(max) ,@createdAt datetime,@expireAt datetime,@name1 nvarchar(40),@value1 nvarchar(max) ,@name2 nvarchar(40),@value2 nvarchar(max) ',@invocationData=N'{"t":"Tdc.GenesisMachine.RemoteData.Shared.HangFireJobs.RemoteDataFilePuller, Tdc.GenesisMachine.RemoteData.Shared","m":"OnProcessedAllEwonsSuccessfullyHook"}',@arguments=N'[]',@createdAt='2019-11-29 10:42:22.883',@expireAt='2019-12-29 10:42:22.883',@name1=N'CurrentCulture',@value1=N'"en-US"',@name2=N'CurrentUICulture',@value2=N'"en-US"'
```
Also visible in database:
`6	NULL	NULL	{"t":"Tdc.GenesisMachine.RemoteData.Shared.HangFireJobs.RemoteDataFilePuller, Tdc.GenesisMachine.RemoteData.Shared","m":"OnProcessedAllEwonsSuccessfullyHook"}	[]	2019-11-29 10:42:22.883	2019-12-29 10:42:22.883`

**Comment by sommmen** [comment]
Both the parent job (FilePullingRecurring) and the continuation have the attribute '[DisableConcurrentExecution(3600)]'

**Comment by sommmen** [comment]
I tried to use http://www.symbolsource.org/Public/Wiki/Using to debug but i could not get it to work.

**Comment by odinserj** [comment]
Please post here all the rows from the `JobParameter` table that relate to your both antecedent and continuation job.

**Comment by odinserj** [comment]
Recurring jobs aren't supported as antecedent job for continuations, but you can create the whole chain in the recurring job itself:

```csharp
public void MyRecurringJob()
{
    var antecedentId = BackgroundJob.Enqueue(() => ...);
    BackgroundJob.ContinueJobWith(antecedentId, () => ...);
}
```

**Comment by sommmen** [comment]
> 
> 
> Recurring jobs aren't supported as antecedent job for continuations, but you can create the whole chain in the recurring job itself:
> 
> ```cs
> public void MyRecurringJob()
> {
>     var antecedentId = BackgroundJob.Enqueue(() => ...);
>     BackgroundJob.ContinueJobWith(antecedentId, () => ...);
> }
> ```

.....

Okay - I feel like that should be mentioned in the docs somewhere though.
Unfortunately i did not wrap the actual logic in something like AHangFireJob meaning at this time i do not want to call any hangfire items (meaning i don't want the dependency) in the job. I thought i could do that outside the actual logic with continuations.
Do you reckon support for continuations on recurring jobs will ever be implemented or?
