### ISSUE TITLE
Create Hangfire tables only if not exists option.

### ISSUE THREAD

**Issue by TanvirArjel** [HangfireIO/Hangfire#1586]
Every time I run my ASP.NET Core application I am getting the following exception as Hangfire is trying to create Hangfire tables on application startup.

Actually there should be an option that tables will be created only if not exists in the database.

There is option as follows:

     var sqlServerStorageOptions = new SqlServerStorageOptions
      {
                PrepareSchemaIfNecessary = false
       };

But this would not create table if not exists in the database.

```
Database schema [HangFire] already exists
Table [HangFire].[Schema] already exists
Current Hangfire schema version: none
Enabling HEAVY_MIGRATIONS, because we are installing objects from scratch
Installing schema version 1
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader)
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command)
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType)
   at Hangfire.SqlServer.SqlServerObjectsInstaller.Install(DbConnection connection, String schema, Boolean enableHeavyMigrations)
   at Hangfire.SqlServer.SqlServerStorage.<>c__DisplayClass32_0.<UseConnection>b__0(DbConnection connection)
   at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](DbConnection dedicatedConnection, Func`2 func)
   at Hangfire.SqlServer.SqlServerStorage.UseConnection(DbConnection dedicatedConnection, Action`1 action)
   at Hangfire.SqlServer.SqlServerStorage.Initialize()
ClientConnectionId:35976027-aaa5-467e-b3ed-5b09f16d92f6
Error Number:2714,State:6,Class:16
Hangfire.SqlServer.SqlServerObjectsInstaller:Warning: An exception occurred while trying to perform the migration. Retrying...

```

**Comment by pieceofsummer** [comment]
You seem to already have `[HangFire].[Schema]` table but it doesn't contain a valid schema version, hence migration script couldn't be applied successfully. Try dropping all the tables in `[HangFire]` schema to re-create them from scratch.

Not creating table if it already exists is a bad option, because the existing table may have a very different schema. This would result in various runtime errors later.

If you're clearing the database by truncating all Hangfire tables, please leave the `[HangFire].[Schema]` data untouched so the actual schema version is retained for migrations to succeed.

**Comment by stephanedenis** [comment]
Il faut détruire toutes les tables HangFire à cause d'un confit de version et de la gestion en Code First.
