### ISSUE TITLE
DI with RecurringJob and CancellationToken fails on 1.7.x

### ISSUE THREAD

**Issue by schmitch** [HangfireIO/Hangfire#1621]
Hello, currently having a method that gets invoked via DI:
```
            RecurringJob.AddOrUpdate<JobClass>(
                $"job-{id}",
                x => x.Call(id, CancellationToken.None),
                cron,
                TimeZoneInfo.Local);
```

```
public class JobClass
{
private readonly DbContext _context;

public async Task Call(int jobId, CancellationToken token) {}

}
```

does actually fail with:
```
Recurring job 'job-12' can't be scheduled due to an error and will be retried in 00:00:15.
Hangfire.Common.JobLoadException: Could not load the job. See inner exception for the details.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'values')
   at System.String.Join(String separator, IEnumerable`1 values)
   at Hangfire.Storage.InvocationData.DeserializeJob()
   --- End of inner exception stack trace ---
   at Hangfire.Storage.InvocationData.DeserializeJob()
   at Hangfire.RecurringJobEntity..ctor(String recurringJobId, IDictionary`2 recurringJob, ITimeZoneResolver timeZoneResolver, DateTime now)
```

btw. this worked in 1.6.x

**Comment by odinserj** [comment]
Hello @schmitch, thank you for reporting this problem. I was unable to reproduce it by creating the recurring job in 1.6.9 and execute it in either 1.7.0 or 1.7.9, but traced the possible reason to wrong parameter type deserialization.

Could you tell me whether you are using any custom serializers and give me the contents of the corresponding recurring job hash? If you are using SQL Server or Redis, please use the following queries.

```sql
SELECT * FROM [HangFire].[Hash] WHERE [Key] = N'recurring-job:job-12'
```

```
HGETALL hangfire:recurring-job:job-12
```

**Comment by Azhe403** [comment]
what about fixes?
this issue happen on mysql too

**Comment by luisgepeto** [comment]
I'm facing this same issue too, do we have a fix soon? https://stackoverflow.com/questions/72222732/hangfire-recurringjob-does-not-contain-a-method-with-signature
