### ISSUE TITLE
System.PlatformNotSupportedException: System.Data.SqlClient is not supported on this platform.

### ISSUE THREAD

**Issue by redxeagle** [HangfireIO/Hangfire#1636]
Hi,

I wanted to upgrade from .net core 2.2 to 3.1.
But I running into issues with Hangfire.SqlServer.

I always got this exception after start:```

[10:38:04 DBG] Execution loop BackgroundServerProcess:3c9a0ccf caught an exception and will be retried in 00:00:15
System.PlatformNotSupportedException: System.Data.SqlClient is not supported on this platform.
   at System.Data.SqlClient.SqlConnection..ctor(String connectionString)
   at Hangfire.SqlServer.SqlServerStorage.<.ctor>b__6_0()
   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
   at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](DbConnection dedicatedConnection, Func`2 func)
   at Hangfire.SqlServer.SqlServerStorage.UseConnection(DbConnection dedicatedConnection, Action`1 action)
   at Hangfire.Server.BackgroundServerProcess.CreateServer(BackgroundServerContext context)
   at Hangfire.Server.BackgroundServerProcess.Execute(Guid executionId, BackgroundExecution execution, CancellationToken stoppingToken, CancellationToken stoppedToken, CancellationToken shutdownToken)
   at Hangfire.Server.BackgroundProcessingServer.RunServer(Guid executionId, Object state)
   at Hangfire.Processing.BackgroundExecution.Run(Action`2 callback, Object state)
```

I have no ideas anymore how to solve this.

**Comment by sablank725** [comment]
@redxeagle 
We ran into this same issue when trying to run a published version of the app and were able to resolve it by specifying the Publish Settings Configuration to `Release | x64` instead of `Release | Any CPU`.

I'll be honest, I'm not exactly sure why that fixed our issue, but it did. One thing we did noticed was that the System.Data.SqlClient.dll included in the x64 release was ~4x the size of the Any CPU dll. Again, not sure why, but that's something that stood out.

Hope this helps!

**Comment by mateso** [comment]
I ran into the same problem. I tried @sablank725 solution but it didn't work. Hangfire works well in VS2019 but not in IIS when published. I'm using .net core 3.1 and hangfire 1.7.11.
Any help please

**Comment by odinserj** [comment]
Try to utilise the [Microsoft.Data.SqlClient](https://www.nuget.org/packages/Microsoft.Data.SqlClient) package of the latest version for this case. Looks like it will be used by default in 1.8.0 version (when it is finally released), but we can’t change the defaults in 1.7.X, because of recent changes in MD.SqlClient 4.0 that forces authentication to be used by default and requires to change connection string sometimes.

```csharp
GlobalConfiguration.Configuration
    .UseSqlServerStorage(
        () => new Microsoft.Data.SqlClient.SqlConnection(@"Server=.\;Database=Hangfire.Sample;Trusted_Connection=True;"));
```

**Comment by michalhainc** [comment]
Helped, thanks
