### ISSUE TITLE
[Refit] Hangfire asp.net core refit

### ISSUE THREAD

**Issue by tienvd1994** [HangfireIO/Hangfire#1641]
I use refit (https://github.com/reactiveui/refit) inside BackgroundJob.Enqueue to call request from service other. But return status code 400. Sorry my english is very bad. Pls support me this error.
`Refit.ApiException: Response status code does not indicate success: 400 (Bad Request).
   at Refit.RequestBuilderImplementation.<>c__DisplayClass20_0.<<BuildVoidTaskFuncForMethod>b__0>d.MoveNext() in d:\a\1\s\Refit\RequestBuilderImplementation.cs:line 773
--- End of stack trace from previous location where exception was thrown ---
   at INKA.Order.Infrastructure.Mediators.NotificationHandlers.OrderDeliveryReminderNotificationHandler.Handle(OrderDeliveryReminderNotification notification, CancellationToken cancellationToken) in E:\Works\Projects\inka_saas\INKA.Order.Infrastructure\Mediators\NotificationHandlers\OrderDeliveryReminderNotificationHandler.cs:line 74
   at MediatR.Mediator.PublishCore(IEnumerable`1 allHandlers, INotification notification, CancellationToken cancellationToken)
   at INKA.Order.Infrastructure.Handlers.Order.OrderInsertCommandHandler.SendNotification(String orderId, String orderCode, List`1 installations, List`1 shippings) in E:\Works\Projects\inka_saas\INKA.Order.Infrastructure\Handlers\Order\OrderCommandHandler.cs:line 533
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()`

**Comment by MikelThief** [comment]
You should rather contact your API owner rather than reporting issue here. This has nothing to do with Hangfire. Your API request contains wrong data.
