### ISSUE TITLE
Randomly occurring issue: 'Unable to resolve service for type (...)'

### ISSUE THREAD

**Issue by XardasLord** [HangfireIO/Hangfire#1653]
I encountered a strange issue. I'm getting **sometimes** (totally randomly) error about `Unable to resolve service for type 'AW.Services.Interfaces.ISmsService' while attempting to activate 'AW.Services.Jobs.SendSmsJob'.` When I click requeue on dashboard on this failed job it either fails again or finish with success. It happens really randomly and I don't have any idea what is happening. 

I have registered my interface in IoC of course like this: `services.AddTransient<ISmsService, SmsService>();`.

I'm using the following packages versions:

- .NET Core 3.1
- Hangfire 1.7.9
- Hangfire.AspNetCore 1.7.9
- Hangfire.Console 1.4.2
- Hangfire.PostgreSql 1.6.4.1

My hangfire's configuration in startup.cs is the following:
```
services.AddHangfire(config =>
{
	config.UsePostgreSqlStorage(Configuration["AW_API_DB_CONNECTIONSTRING"]);
	config.UseConsole();
});
GlobalConfiguration.Configuration.UseSerializerSettings
(
	new JsonSerializerSettings
	{
		ReferenceLoopHandling = ReferenceLoopHandling.Ignore
	}
);

(...)

app.UseHangfireServer(new BackgroundJobServerOptions
{
       WorkerCount = backgroundProcessingWorkersCount
});

app.UseHangfireServer(new BackgroundJobServerOptions
{
	WorkerCount = backgroundProcessingWorkersCount,
	Queues = new[] { JobQueueTypes.Transactions }
});
app.UseHangfireDashboard("/dashboard", new DashboardOptions
{
	Authorization = new[] { new AgriWalletDashboardAuthFilter() },
	IgnoreAntiforgeryToken = true
});
```

Below I've copied the entire log from hangfire's dashboard:

> Unable to resolve service for type 'AgriWallet.Services.Interfaces.ISmsService' while attempting to activate 'AgriWallet.Services.Jobs.SendSmsJob'.
> 
> System.InvalidOperationException: Unable to resolve service for type 'AW.Services.Interfaces.ISmsService' while attempting to activate 'AW.Services.Jobs.SendSmsJob'.
>    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
>    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
>    at Hangfire.Server.CoreBackgroundJobPerformer.Perform(PerformContext context)
>    at Hangfire.Server.BackgroundJobPerformer.<>c__DisplayClass9_0.<PerformJobWithFilters>b__0()
>    at Hangfire.Server.BackgroundJobPerformer.InvokePerformFilter(IServerFilter filter, PerformingContext preContext, Func`1 continuation)
>    at Hangfire.Server.BackgroundJobPerformer.InvokePerformFilter(IServerFilter filter, PerformingContext preContext, Func`1 continuation)
>    at Hangfire.Server.BackgroundJobPerformer.PerformJobWithFilters(PerformContext context, IEnumerable`1 filters)
>    at Hangfire.Server.BackgroundJobPerformer.Perform(PerformContext context)
>    at Hangfire.Server.Worker.PerformJob(BackgroundProcessContext context, IStorageConnection connection, String jobId)

**Comment by mjdudzic** [comment]
Migration from netcore 2 to net core 3 may cause issues with Dependency Injection. Please verify the project Program.cs and Startup.cs classes

https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio

**Comment by mjdudzic** [comment]
EDIT to https://github.com/HangfireIO/Hangfire/issues/1653#issuecomment-621020029
DI issues may still occur even after replacing IWebHostBuilder with IHostBuilder. In the Hangfire source code there are some preprocessor rules defined e.g. to use specific library for NETCOREAPP3_0. I did not analyse the code deeply but it seems that something may still work incorrectly as now we have NETCOREAPP3_1.
In this case the question is whether Hangfire should work in netcore 3.1 ?

**Comment by odinserj** [comment]
Hangfire doesn't have builds that produce binaries for the `netcoreapp3.1` target, so everything is fine with those defines – external application that targets `netcoreapp3.1` will use Hangfire.AspNetCore or Hangfire.NetCore of the `netcoreapp3.0` target, so those defines work as expected.

Where do you host your application? Any chance there's another instance running with older code without the registration, like deployment slot?

**Comment by mtwarowski** [comment]
I'm seeing the same issue on my application on multiple servers. We do have proper versioning in place and I am confident that it is not an old version of the application. 

 It seems that Hangfire is randomly failing to resolve dependencies     

- .NET Core 3.1
- Hangfire 1.7.9
- Hangfire.AspNetCore 1.7.11
- Hangfire.Core 1.7.11
- Hangfire.SqlServer 1.7.11

`Failed

An exception occurred during processing of a background job.
System.InvalidOperationException

Unable to resolve service for type 'System.Func`1[xyz]' while attempting to activate 'xyz'.

System.InvalidOperationException: Unable to resolve service for type 'System.Func`1[xyz]' while attempting to activate 'xyz'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Hangfire.Server.CoreBackgroundJobPerformer.Perform(PerformContext context)
   at Hangfire.Server.BackgroundJobPerformer.<>c__DisplayClass9_0.<PerformJobWithFilters>b__0()
   at Hangfire.Server.BackgroundJobPerformer.InvokePerformFilter(IServerFilter filter, PerformingContext preContext, Func`1 continuation)
   at Hangfire.Server.BackgroundJobPerformer.PerformJobWithFilters(PerformContext context, IEnumerable`1 filters)
   at Hangfire.Server.BackgroundJobPerformer.Perform(PerformContext context)
   at Hangfire.Server.Worker.PerformJob(BackgroundProcessContext context, IStorageConnection connection, String jobId)`

**Comment by XardasLord** [comment]
@mtwarowski Do you have one common Hangfire database for multiple services?

**Comment by mtwarowski** [comment]
@XardasLord yea we share a single sql server database across all instances of this micro service.

**Comment by XardasLord** [comment]
@mtwarowski This may cause problems as it was our case. If e.g. your first microservice creates a job and then your second microservice tries to execute it - you can have 'unable to resolve service...' issue. 
The solution in our case was to have separate databases for each hangfire's instance.

**Comment by mtwarowski** [comment]
Sounds like an expensive solution. Our microservice is currently running on 10 instances this means 9 more instances of sql server. Also we do have this king of setup in other services that are full .Net framework and they seems to be fine.
