### ISSUE TITLE
ASP.NET Core - Hangfire dashboard - routing configuration

### ISSUE THREAD

**Issue by klinki** [HangfireIO/Hangfire#1729]
Hello,

I have problem with Hangfire dashboard returning error 500 for invalid routes. 

It throws following exception:
>> System.InvalidOperationException: The request reached the end of the pipeline without executing the endpoint: '/hangfire/{**path}'. Please register the EndpointMid
dleware using 'IApplicationBuilder.UseEndpoints(...)' if using routing.
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.<>c.<Build>b__18_0(HttpContext context)
   at Hangfire.Dashboard.AspNetCoreDashboardMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Inviser.Middlewares.ExceptionHandler.InvokeAsync(HttpContext context, RequestDelegate next) in C:\projects\inviser\Inviser\Middlewares\ExceptionHandler.cs:li
ne 58

I believe it should return HTTP 404 not found instead and not throw any exception.

I'm using ASP.NET Core and I'm configuring dashboard with `app.UseEndpoints(endpoints => endpoints.MapHangfireDashboard())`

**Comment by udlose** [comment]
Are you using `app.UseHangfireDashboard()` in your `Configure(IApplicationBuilder app)` method in `Startup`?

**Comment by ogazioglu** [comment]
I was getting same error in .NET Core 3.1 with routing, and have fixed the problem by removing all `app.UseHangfireXXX(...)` methods in my `Configure()` block as mentioned [here](https://docs.hangfire.io/en/latest/getting-started/aspnet-core-applications.html#registering-services) and [here](https://docs.hangfire.io/en/latest/getting-started/aspnet-core-applications.html#adding-dashboard-ui). My working solution with authorization has the lines below:

    public IServiceProvider ConfigureServices(IServiceCollection services, ...)
    {
        ...
        services.Configure<AuthorizationOptions>(options =>
        {
            options.AddPolicy("somePolicy", policy =>
            {
                policy.RequireAuthenticatedUser();
            });
        });
        services.AddHangfire(....);
        services.AddHangfireServer(....);
        ...
    }

    public void Configure(IApplicationBuilder app, IBackgroundJobClient backgroundJobs, ...)
    {
        ...
        backgroundJobs.Enqueue(() => Console.WriteLine("Hello world from Hangfire!"));
        app.UseCookiePolicy();
        app.UseSession();
        app.UseRouting();
        app.UseAuthentication();
        app.UseAuthorization();
        app.UseEndpoints(endpoints =>
        {
            ...
            endpoints.MapDefaultControllerRoute();
            endpoints.MapHangfireDashboard("", new DashboardOptions
            {
                Authorization = new[] { new HangfireAuthorizationFilter("somePolicy"), },
                ...
            });
            ...
        });
    }
    public class HangfireAuthorizationFilter : IDashboardAuthorizationFilter
    {
        private string PolicyName { get; }

        public HangfireAuthorizationFilter(string policyName)
        {
            this.PolicyName = policyName;
        }
        public bool Authorize(DashboardContext context)
        {
            var httpContext = context.GetHttpContext();
            var authService = httpContext.RequestServices.GetRequiredService<IAuthorizationService>();
            var authorizationResult = authService.AuthorizeAsync(httpContext.User, this.PolicyName).ConfigureAwait(false).GetAwaiter().GetResult();
            var isAuthorized = authorizationResult.Succeeded;

            if (!isAuthorized)
            {
                httpContext.ChallengeAsync().ConfigureAwait(false).GetAwaiter().GetResult();
            }
            return true; //always return true
        }
    }

**Comment by maksimnarkevichdp** [comment]
Any updates on this? I am getting the same error while using following configuration: 
`endpoints.MapHangfireDashboard(
                    string.Empty,
                    new DashboardOptions { Authorization = new List<IDashboardAuthorizationFilter>(), StatsPollingInterval = 60000 }).RequireAuthorization();`
