### ISSUE TITLE
Issues running on alpine-linux with .NET 5.0

### ISSUE THREAD

**Issue by formlesstree4** [HangfireIO/Hangfire#1767]
Hey guys! I'm not quite sure what combination of changes happened to make this issue arise, but I'm having an issue running a Background Job as of .NET 5.0 but _only_ when running my application in a container. For reference, I code, build, and test on an ArchLinux VM in Visual Studio Code.

Context: I am building a Discord bot that runs scheduled jobs on an interval (using the RecurringJob class) and occasionally responds with the BackgroundJob class. The RecurringJob tasks seem to be working as expected. It's ONLY the BackgroundJob class that seems to be failing to work correctly.

The job that throws the error is this:
```cs
BackgroundJob.Schedule(() => SendMessageToUser(/*User ID [as a ulong]*/, "Ping"), TimeSpan.FromSeconds(1));
```

Scheduling the Job is no problem. And running the application on my local archlinux box is also fine! But when I deploy it to the container... this is what I see printed to the logs:

```
System.IO.FileNotFoundException: Could not load file or assembly 'mscorlib, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.

File name: 'mscorlib, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Hangfire.Common.TypeHelper.AssemblyResolver(String assemblyString)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Hangfire.Common.TypeHelper.CachedAssemblyResolver(AssemblyName assemblyName)
   at System.TypeNameParser.ResolveAssembly(String asmName, Func`2 assemblyResolver, Boolean throwOnError, StackCrawlMark& stackMark)
   at System.TypeNameParser.ConstructType(Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.TypeNameParser.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError)
   at Hangfire.Common.TypeHelper.DefaultTypeResolver(String typeName)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at Hangfire.Storage.InvocationData.DeserializeJob()
```

With some assistance, [this](https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.Core/Common/TypeHelper.cs#L31) was found in the core library but I don't know if it's relevant or not. Given that the class is in the stacktrace, it might be a lead.

And lastly, here's my Dockerfile that I'm using to build the container with:

```dockerfile
FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine AS build
WORKDIR /source

# copy and publish app and libraries
COPY . .
RUN dotnet restore -r linux-musl-x64
RUN dotnet publish source/Bot -c release -o /app -r linux-musl-x64 --self-contained true --no-restore /p:PublishTrimmed=true /p:PublishReadyToRun=true

# final stage/image
FROM mcr.microsoft.com/dotnet/runtime-deps:5.0-alpine
WORKDIR /app
COPY --from=build /app .

ENV RavenIP ""
EXPOSE 5000

ENTRYPOINT ["./Bot"]
```

If there's anything else I can provide, please let me know! For now, I'll just be running the app out of my VM.

EDIT:
I am using the following libraries:
- Hangfire.Core 1.7.18
- Hangfire.AspNetCore 1.7.18
- Hangfire.PostgreSql 1.8.0

**Comment by formlesstree4** [comment]
After getting some assistance from a Docker person, I realized two things:
1. I should not be using `runtime-deps` but `runtime`.
1. Since I am trimming the executable, I should ensure that I don't trim out mscorlib.

Adding the following to my csproj file alleviated the issue entirely:
```xml
  <ItemGroup>
    <TrimmerRootAssembly Include="mscorlib" />
  </ItemGroup>
```

Not sure why this just now was working but here we are. I'll go ahead and close this issue out.
