### ISSUE TITLE
Custom schema name - error message 

### ISSUE THREAD

**Issue by lucianoscastro** [HangfireIO/Hangfire#1768]
Hi everyone.. 
I make same testes with hangfire to migrade my web.api to .net 5.0, and i have a error situation  

My web.api configure:
services.AddHangfire(hangFireConfiguration =>
{
                   hangFireConfiguration.UsePostgreSqlStorage(pgConnection, new PostgreSqlStorageOptions
                    {
                        PrepareSchemaIfNecessary = true,
                        SchemaName = "MY_SCHEMA_NAME_TO_JOBS"
                    });
});

When execute de API some error occurred:

[00:39:49 ERR] Error while executing install/upgrade
Npgsql.PostgresException (0x80004005): 3F000: schema "hangfire" does not exist
   at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Hangfire.PostgreSql.PostgreSqlObjectsInstaller.Install(NpgsqlConnection connection, String schemaName)
  Exception data:
    Severity: ERROR
    SqlState: 3F000
    MessageText: schema "hangfire" does not exist
    File: namespace.c
    Line: 3044
    Routine: get_namespace_oid
[00:39:50 INF] Hangfire SQL objects installed.

Any one can help me???

**Comment by gertcominotto** [comment]
Having the same issue:
"HangFire" Version="1.7.18" 
"Hangfire.AspNetCore" Version="1.7.18" 
"Hangfire.PostgreSql" Version="1.8.0" 
"Hangfire.Console" Version="1.4.2"
