### ISSUE TITLE
JobActivator in NET Core 3.1

### ISSUE THREAD

**Issue by Blennouill** [HangfireIO/Hangfire#1774]
### Context
I'm migrating an Asp Net Core 2.1 web app to 3.1 web app and Net Core app 2.1 to 3.1 too.

The Hangfire server is currently running using a console app that we run as a Windows service in production.

The used Hangfire version is 1.7.18.

### What is the trouble ?
As per Microsoft guidelines, I am now using the new BackgroundService implementation to start the Windows service as opposed to a custom-made class. A breaking-change in 3.1 causes a problem when using IServiceProvider alongside IHostedService. Indeed, it is no longer possible to inject the IServiceProvider directly. I stumbled upon a post on the Hangfire forums that I thought would fix my problem but to no avail (see [https://discuss.hangfire.io/t/jobactivator-not-working-in-net-core-2-x/4847/2](https://discuss.hangfire.io/t/jobactivator-not-working-in-net-core-2-x/4847/2))

When trying to activate any of the background jobs, the same exception is thrown :

> JobActivator returned NULL instance of the 'iDatech.InjectionEngine.Infrastructure.Hangfire.Tasks.MissingReturnsAlertTask' type.
> 
> System.InvalidOperationException: JobActivator returned NULL instance of the '*.Tasks.MissingReturnsAlertTask' type.
>    at Hangfire.Server.CoreBackgroundJobPerformer.Perform(PerformContext context)
>    at Hangfire.Server.BackgroundJobPerformer.<>c__DisplayClass9_0.<PerformJobWithFilters>b__0()
>    at Hangfire.Server.BackgroundJobPerformer.InvokePerformFilter(IServerFilter filter, PerformingContext preContext, Func`1 continuation)
>    at Hangfire.Server.BackgroundJobPerformer.<>c__DisplayClass9_1.<PerformJobWithFilters>b__2()
>    at Hangfire.Server.BackgroundJobPerformer.InvokePerformFilter(IServerFilter filter, PerformingContext preContext, Func`1 continuation)
>    at Hangfire.Server.BackgroundJobPerformer.<>c__DisplayClass9_1.<PerformJobWithFilters>b__2()
>    at Hangfire.Server.BackgroundJobPerformer.PerformJobWithFilters(PerformContext context, IEnumerable`1 filters)
>    at Hangfire.Server.BackgroundJobPerformer.Perform(PerformContext context)
>    at Hangfire.Server.Worker.PerformJob(BackgroundProcessContext context, IStorageConnection connection, String jobId)

Below is the 2.1 config vs the 3.1 conf.

````
/// <summary>
    /// This configuration class allow Hangfire to use .NET Core original DI.
    /// </summary>
    sealed public class HangfireActivator : JobActivator
    {
        #region Instance variables

        /// <summary>
        /// <see cref="IServiceProvider"/>
        /// </summary>
        readonly private IServiceProvider m_ServiceProvider;

        #endregion Instance variables

        #region Constructors

        /// <summary>
        /// Default constructor.
        /// </summary>
        /// <param name="serviceProvider"><see cref="IServiceProvider"/></param>
        public HangfireActivator(IServiceProvider serviceProvider)
        {
            m_ServiceProvider = serviceProvider;
        }

        #endregion Constructors

        #region Methods

        /// <summary>
        /// <see cref="JobActivator.ActivateJob(Type)"/>
        /// </summary>
        public override object ActivateJob(Type jobType)
        {
            return m_ServiceProvider.GetRequiredService(jobType);
        }

        #endregion Methods
    }
````

````
    /// <summary>
    /// This configuration class allow Hangfire to use .NET Core original DI.
    /// </summary>
    sealed public class HangfireActivator : JobActivator
    {
        #region Instance variables

        readonly private IServiceScopeFactory m_ServiceScopeFactory;

        #endregion Instance variables

        #region Constructors

        /// <summary>
        /// Default constructor.
        /// </summary>
        /// <param name="serviceScopeFactory"><see cref="IServiceScopeFactory"/></param>
        public HangfireActivator(IServiceScopeFactory serviceScopeFactory)
        {
            m_ServiceScopeFactory = serviceScopeFactory;
        }

        #endregion Constructors

        #region Methods

        /// <summary>
        /// <see cref="JobActivator.BeginScope(JobActivatorContext)"/>
        /// </summary>
        public override JobActivatorScope BeginScope(JobActivatorContext context)
        {
            return new ServiceJobActivatorScope(m_ServiceScopeFactory.CreateScope());
        }

        #endregion Methods
    }

    /// <summary>
    /// Specific implementation of <see cref="JobActivatorScope"/> to allow .NET Core 3+ console app to work with Hangfire.
    /// </summary>
    sealed internal class ServiceJobActivatorScope : JobActivatorScope
    {
        #region Instance variables

        readonly private IServiceScope _serviceScope;

        #endregion Instance variables

        /// <summary>
        /// Default constructor.
        /// </summary>
        /// <param name="serviceScope"><see cref="IServiceScope"/></param>
        public ServiceJobActivatorScope(IServiceScope serviceScope)
        {
            _serviceScope = serviceScope ?? throw new ArgumentNullException(nameof(serviceScope));
        }

        /// <summary>
        /// Resolving using the current service scope instance variable.
        /// </summary>
        public override object Resolve(Type type)
        {
            return _serviceScope.ServiceProvider.GetService(type);
        }
    }
````

The activator is used as below 

````
/// <summary>
    /// Initiate hangfire launch.
    /// </summary>
    internal class HangfireLaunching : BackgroundService
    {
        #region Instance variables

        private readonly IServiceScopeFactory m_ServiceScopeFactory;

        /// <summary>
        /// <see cref="ILogger"/>
        /// </summary>
        readonly private ILogger m_Logger;

        /// <summary>
        /// <see cref="IConfiguration"/>
        /// </summary>
        readonly private IConfiguration m_Configuration;

        /// <summary>
        /// <see cref="BackgroundJobServer"/>
        /// </summary>
        private BackgroundJobServer m_HangfireServer;

        #endregion Instance variables

        #region Constructors

        /// <summary>
        /// Default constructor.
        /// </summary>
        public HangfireLaunching(
            IConfiguration configuration,
            ILogger<HangfireLaunching> logger,
            IServiceScopeFactory serviceScopeFactory)
            : base()
        {
            m_Logger = logger;
            m_Configuration = configuration;
            m_ServiceScopeFactory = serviceScopeFactory;
        }

        #endregion Constructors

        #region Methods

        protected override Task ExecuteAsync(CancellationToken stoppingToken)
        {
            if (!stoppingToken.IsCancellationRequested)
            {
                GlobalConfiguration.Configuration.UseSimpleAssemblyNameTypeSerializer()
                                    .UseRecommendedSerializerSettings()
                                    .UseSqlServerStorage(m_Configuration.GetConnectionString("Hangfire"), new SqlServerStorageOptions
                                    {
                                        CommandBatchMaxTimeout = TimeSpan.FromMinutes(5),
                                        SlidingInvisibilityTimeout = TimeSpan.FromMinutes(5),
                                        QueuePollInterval = TimeSpan.Zero,
                                        UseRecommendedIsolationLevel = true,
                                        UsePageLocksOnDequeue = true,
                                        DisableGlobalLocks = true
                                    });

                BackgroundJobServerOptions backgroundJobServerOptions = new BackgroundJobServerOptions
                {
                    Activator = new HangfireActivator(m_ServiceScopeFactory),
                    ServerName = "Moteur d'injection - Serveur Hangfire"
                };

                // Create an instance of Hangfire Server and start it.
                m_HangfireServer = new BackgroundJobServer(backgroundJobServerOptions);
                m_Logger.LogInformation("Hangfire Server started.");

                ConfigureRecurringTasks();
            }

            return Task.CompletedTask;
        }

        public override Task StopAsync(CancellationToken cancellationToken)
        {
            m_HangfireServer.Dispose();

            m_Logger.LogInformation("Hangfire Server stopped.");

            return base.StopAsync(cancellationToken);
        }

        /// <summary>
        /// Is used to configure recurring tasks in Hangfire.
        /// </summary>
        private void ConfigureRecurringTasks()
        {
            IEnumerable<IRecurringBackgroundTask> recurringTasks = m_ServiceScopeFactory.CreateScope().ServiceProvider.GetServices<IRecurringBackgroundTask>();
            var recurringTasksDescriptions = recurringTasks.Select(x => x.Name).ToList();

            // Clear existing background tasks that don't exist anymore
            using (IStorageConnection connection = JobStorage.Current.GetConnection())
            {
                foreach (RecurringJobDto recurringJob in connection.GetRecurringJobs().Where(recurringJob => !recurringTasksDescriptions.Contains(recurringJob.Id)))
                {
                    RecurringJob.RemoveIfExists(recurringJob.Id);
                }
            }

            // Append or update all registered background tasks to Hangfire's configuration
            foreach (IRecurringBackgroundTask task in recurringTasks)
            {
                RecurringJob.AddOrUpdate(task.Name,
                                        () => task.Execute(JobCancellationToken.Null),
                                        task.CronExpression,
                                        TimeZoneInfo.Local);
            }
        }

        #endregion Methods
    }
````

What is wrong with my code ?

Regards 😃

**Comment by Blennouill** [comment]
The problem was coming for the developer ... 😃 ! My bad..

The solution here is perfect [https://discuss.hangfire.io/t/jobactivator-not-working-in-net-core-2-x/4847/2](https://discuss.hangfire.io/t/jobactivator-not-working-in-net-core-2-x/4847/2)
