### ISSUE TITLE
Hangfire server becomes idle after exception

### ISSUE THREAD

**Issue by gkralj** [HangfireIO/Hangfire#1781]
I have installed latest hangfire on asp.net core project on postgresql database.

I have received an exception 
`Server XXX encountered an exception while sending heartbeat.
`
Server becomes idle an shutdown event is called:
`Server XXX successfully reported itself as stopped in 30,391 ms.
`
I am wondering we have setup application pool to be always running,
also using this [post](https://discuss.hangfire.io/t/make-hangfire-always-in-running-mode-for-asp-net-core/5937/3)

I mean i try to recycle manually application pool, start/stop and in log i see its running again.

BUT after this exception application has not started running again !
What is the problem?

Exception.
`Npgsql.NpgsqlException (0x80004005): Exception while connecting
 ---> System.TimeoutException: Timeout during connection attempt
   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnection.Open()
   at Hangfire.PostgreSql.PostgreSqlStorage.CreateAndOpenConnection()
   at Hangfire.PostgreSql.PostgreSqlStorage.GetConnection()
   at Hangfire.Server.ServerHeartbeatProcess.Execute(BackgroundProcessContext context)`

**Comment by gkralj** [comment]
![image](https://user-images.githubusercontent.com/4538327/104279968-75f40800-54ab-11eb-9c76-e9c49d8f5135.png)

Looks like feature Application Initialization needs to be installed in Web Server > Application Development.
