### ISSUE TITLE
Item has already been added. Key in dictionary: 'OriginalStackTrace' Key being added: 'OriginalStackTrace'

### ISSUE THREAD

**Issue by Deantwo** [HangfireIO/Hangfire#1789]
```
System.ArgumentException
Item has already been added. Key in dictionary: 'OriginalStackTrace' Key being added: 'OriginalStackTrace'

System.ArgumentException: Item has already been added. Key in dictionary: 'OriginalStackTrace'  Key being added: 'OriginalStackTrace'
   at System.Collections.ListDictionaryInternal.Add(Object key, Object value)
   at Hangfire.Common.ShallowExceptionHelper.PreserveOriginalStackTrace(Exception exception)
   at Hangfire.States.StateMachine.InvokeOnStateApplied(Tuple`2 x)
   at Hangfire.Profiling.ProfilerExtensions.InvokeAction[TInstance](InstanceAction`1 tuple)
   at Hangfire.Profiling.SlowLogProfiler.InvokeMeasured[TInstance,TResult](TInstance instance, Func`2 action, String message)
   at Hangfire.Profiling.ProfilerExtensions.InvokeMeasured[TInstance](IProfiler profiler, TInstance instance, Action`1 action, String message)
   at Hangfire.States.StateMachine.ApplyState(ApplyStateContext initialContext)
   at Hangfire.States.BackgroundJobStateChanger.ChangeState(StateChangeContext context)
   at Hangfire.Server.Worker.TryChangeState(BackgroundProcessContext context, IStorageConnection connection, IFetchedJob fetchedJob, IState state, String[] expectedStates, CancellationToken initializeToken, CancellationToken abortToken)
```

**Comment by odinserj** [comment]
Thanks @Deantwo will fix this and release 1.7.19 as soon as possible!
