### ISSUE TITLE
net 5.0 docker  hangfire can't start up 

### ISSUE THREAD

**Issue by gzh4455** [HangfireIO/Hangfire#1819]
The Log Message:
INFO Hangfire.SqlServer.SqlServerObjectsInstaller Start installing Hangfire SQL objects...

There isn't any error message . and It is still stuck  and can't start the web application .

The Environment is Docker + Net 5.0 

the  docker file looks below .

#FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
#FROM mcr.microsoft.com/dotnet/aspnet:5.0 
FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim

 
COPY . /var/www/Centralism.Web

#database  connection allow from  tls 1.2 to tls 1.0
RUN sed -i 's/TLSv1.2/TLSv1.0/g' /etc/ssl/openssl.cnf

#time zone
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /var/www/Centralism.Web 
    

ENV ASPNETCORE_URLS http://+:50001

EXPOSE 50001
EXPOSE 443

#运行dotnet命令,参数是你的程序集的入口dll--就是你的Web程序dll
ENTRYPOINT ["dotnet", "Centralism.Web.dll"]

**Comment by odinserj** [comment]
Any chance you are upgrading Hangfire from 1.6.X to 1.7.X and set `SqlServerStorageOptions.EnableHeavyMigrations` to `true`? In this case you can switch `SqlServerStorageOptions.EnableHeavyMigrations` to `false` and upgrade database schema manually as written here – https://docs.hangfire.io/en/latest/upgrade-guides/upgrading-to-hangfire-1.7.html#migrating-the-schema.

**Comment by gzh4455** [comment]
The issue is still existing after I  add the SQL options . for example as below 
  context.Services.AddHangfire(config =>
            {
                config.UseSqlServerStorage(configuration.GetConnectionString("HangFire"),new SqlServerStorageOptions() { 
                    EnableHeavyMigrations=true,
                    DisableGlobalLocks = true
                });
            });

It will work well when  I debug in the visual studio 2019.  The issue occurs in then deployment.  I deploy in the centos 7.5 with the docker

**Comment by gzh4455** [comment]
It works well  and deploy well when web application use the net core 3.1 .

**Comment by odinserj** [comment]
Please try to apply the following settings to disable automatic schema migration to see whether it's the reason for the behavior you get.

```csharp
context.Services.AddHangfire(config =>
{
    config.UseSqlServerStorage(configuration.GetConnectionString("HangFire"),new SqlServerStorageOptions() {
        PrepareSchemaIfNecessary = false
    });
});
```

**Comment by gzh4455** [comment]
It causes another issue. 

Hangfire.BackgroundJobClientException: Background job creation failed. See inner exception for details.
 ---> System.InvalidOperationException: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.

I make sure that the sql database works well and the connection pool is not full .

**Comment by odinserj** [comment]
Please try also to install the latest version of [System.Data.SqlClient](https://www.nuget.org/packages/System.Data.SqlClient/) explicitly into your application project and post here the full stack trace of InvalidOperationException with all the methods shown.

**Comment by gzh4455** [comment]
I use the latest system.data.sqlclient. 

it occurs another error. it  seems the docker or centos environment error 

2021-02-24 20:06:28.7103|6|FATAL Microsoft.AspNetCore.Hosting.Diagnostics Application startup exception Volo.Abp.AbpInitializationException: An error occurred during the initialize Volo.Abp.Modularity.OnApplicationInitializationModuleLifecycleContributor phase of the module Centralism.ULMP.Web.ULMPWebModule, Centralism.ULMP.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: Background job creation failed. See inner exception for details.. See the inner exception for details.
 ---> Hangfire.BackgroundJobClientException: Background job creation failed. See inner exception for details.
 ---> System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: SSL Provider, error: 31 - Encryption(ssl/tls) handshake failed)
 ---> System.IO.EndOfStreamException: End of stream reached
   at System.Data.SqlClient.SNI.SslOverTdsStream.ReadInternal(Byte[] buffer, Int32 offset, Int32 count, CancellationToken token, Boolean async)
   at System.Data.SqlClient.SNI.SslOverTdsStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.Read(Span`1 buffer)
   at System.Net.Security.SslStream.FillHandshakeBufferAsync[TIOAdapter](TIOAdapter adapter, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Security.SslStream.ProcessAuthentication(Boolean isAsync, Boolean isApm, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost)
   at System.Data.SqlClient.SNI.SNITCPHandle.EnableSsl(UInt32 options)
   at System.Data.SqlClient.SNI.SNIProxy.EnableSsl(SNIHandle handle, UInt32 options)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)

**Comment by odinserj** [comment]
So the issues relates to `System.Data.SqlClient` package, please see this GitHub issue – https://github.com/dotnet/SqlClient/issues/820.

**Comment by gzh4455** [comment]
I have solved this problem. 

I install the latest system.data.sqlclient .  the version is 4.8.2

I add the below code in the Dockerfile. my environment is centos 7.5 + docker +net 5.0
RUN sed -i 's/MinProtocol = TLSv1.2/MinProtocol = TLSv1/g' /etc/ssl/openssl.cnf
RUN sed -i 's/MinProtocol = TLSv1.2/MinProtocol = TLSv1/g' /usr/lib/ssl/openssl.cnf

if you environment is centos 7.5 +docker +netcore 3.1. please add below code
RUN sed -i 's/TLSv1.2/TLSv1.0/g' /etc/ssl/openssl.cnf

Thanks odinserj




> So the issues relates to `System.Data.SqlClient` package, please see this GitHub issue – [dotnet/SqlClient#820](https://github.com/dotnet/SqlClient/issues/820).
