### ISSUE TITLE
This may have occurred because all pooled connections were in use and max pool size was reached.

### ISSUE THREAD

**Issue by zhongqingshen** [HangfireIO/Hangfire#1835]
ERROR Message:`System.InvalidOperationException: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
   at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](DbConnection dedicatedConnection, Func`2 func)
   at Hangfire.SqlServer.SqlServerStorage.UseConnection(DbConnection dedicatedConnection, Action`1 action)
   at Hangfire.SqlServer.SqlServerConnection.Heartbeat(String serverId)
   at Hangfire.Server.ServerHeartbeatProcess.Execute(BackgroundProcessContext context)`

I have modified the Hangfire source code. The database password will be changed from time to time, so the project needs to dynamically obtain the database password. change code as below:
`   internal DbConnection CreateAndOpenConnection()
        {
            using (_options.ImpersonationFunc?.Invoke())
            {
                DbConnection connection = null;

                try
                {
                    connection = new SqlConnection(ConnectionString); //_existingConnection ?? _connectionFactory();

                    if (connection.State == ConnectionState.Closed)
                    {
                        connection.Open();
                    }

                    return connection;
                }
                catch
                {
                    ReleaseConnection(connection);
                    throw;
                }
            }
        }`
When adding doWork to a project, this is done every 2 minutes. A connection pooling error occurs after 5 hours. Do not know where is not releasing the connection, please help me

**Comment by kgrosvenor** [comment]
Same issue, we have a long running system and after about 7 days of automated testing it happens. How come the pools continually grow and never cleaned up?
