### ISSUE TITLE
CreateBatchFailedException in production

### ISSUE THREAD

**Issue by andrewdavey** [HangfireIO/Hangfire#1842]
I've recently moved my Hangfire database to a different AWS region. It seemed to be working fine, but an overnight batch is now failing to start.

Stack trace

```
Hangfire.CreateBatchFailedException: An exception occurred while creating the batch. See the inner exception for details. ---> System.InvalidOperationException: The transaction associated with the current connection has completed but has not been disposed.  The transaction must be disposed before the connection can be used to execute SQL statements.
   at System.Data.SqlClient.TdsParser.TdsExecuteRPC(SqlCommand cmd, _SqlRPC[] rpcArray, Int32 timeout, Boolean inSchema, SqlNotificationRequest notificationRequest, TdsParserStateObject stateObj, Boolean isCommandProc, Boolean sync, TaskCompletionSource`1 completion, Int32 startRpc, Int32 startParam)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Hangfire.SqlServer.SqlCommandBatch.ExecuteNonQuery()
   at Hangfire.SqlServer.SqlServerWriteOnlyTransaction.<Commit>b__12_0(DbConnection connection, DbTransaction transaction)
   at Hangfire.SqlServer.SqlServerStorage.<>c__DisplayClass34_0.<UseTransaction>b__0(DbConnection connection, DbTransaction transaction)
   at Hangfire.SqlServer.SqlServerStorage.<>c__DisplayClass35_0`1.<UseTransaction>b__0(DbConnection connection)
   at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](DbConnection dedicatedConnection, Func`2 func)
   at Hangfire.SqlServer.SqlServerStorage.UseTransaction[T](DbConnection dedicatedConnection, Func`3 func, Nullable`1 isolationLevel)
   at Hangfire.SqlServer.SqlServerStorage.UseTransaction(DbConnection dedicatedConnection, Action`2 action)
   at Hangfire.SqlServer.SqlServerWriteOnlyTransaction.Commit()
   at Hangfire.BatchJobClient.Create(Action`1 createAction, IBatchState state, String description) in C:\projects\hangfire-pro\src\Hangfire.Pro\BatchJobClient.cs:line 98
   --- End of inner exception stack trace ---
   at Hangfire.BatchJobClient.Create(Action`1 createAction, IBatchState state, String description) in C:\projects\hangfire-pro\src\Hangfire.Pro\BatchJobClient.cs:line 105
   at Hangfire.BatchJobClientExtensions.StartNew(IBatchJobClient client, Action`1 createAction, String description) in C:\projects\hangfire-pro\src\Hangfire.Pro\BatchJobClientExtensions.cs:line 27
   at Insight.Services.SubscriptionService.EnqueueUpdateForAllSubscriptions(DateTime utcNow) in D:\temp\q1mv4jec.fqg\input\Insight\Services\SubscriptionService.cs:line 441
   at Insight.Services.SubscriptionService.EnqueueUpdateForAllSubscriptions() in D:\temp\q1mv4jec.fqg\input\Insight\Services\SubscriptionService.cs:line 420
```

The simplified code is like this:

```
    public void EnqueueUpdateForAllSubscriptions(DateTime utcNow)
    {
        using (var session = documentStore.OpenSession())
        {
            var count = 0;
            var batchId = batchJobClient.StartNew(batch =>
            {
                var q = session.Query<Subscription, SubscriptionsIndex>();
                using (var stream = session.Advanced.Stream(q))
                {
                    while (stream.MoveNext())
                    {
                        var schoolId = stream.Current.Document.SchoolId;
                        batch.Enqueue<SubscriptionService>(
                            s => s.UpdateSubscription(schoolId, utcNow));
                        count++;
                    }
                }
            }, "UpdateAllSubscriptions");
        }
    }
```

This is running on v1.7.20

**Comment by odinserj** [comment]
Hi Andrew, can you tell me what version of .NET Core/.NET Framework you are using?

**Comment by andrewdavey** [comment]
.NET Framework 4.8

Also, having just looked at the database the Hangfire schema is still on version 5. So there is a migration to be done at some point. However, it was working fine before the DB move.

Another point to note: I updated SQL Server from v13 to v15 - I'm not sure if that changed any defaults.

**Comment by odinserj** [comment]
Thanks. Can you also show me how `batchJobClient` instance is created? I need to ensure that it doesn't use an explicit connection instance.

**Comment by odinserj** [comment]
**UPD.** Please also show me configuration logic related to Hangfire, especially to `SqlServerStorage`.

**Comment by andrewdavey** [comment]
BatchJobClient is coming from IoC container, registered like this:

```
builder.RegisterType<BatchJobClient>().As<IBatchJobClient>();
```

And the app start up has this:

```
            Hangfire.GlobalConfiguration.Configuration.UseSqlServerStorage(ConnectionStrings.Hangfire);

            app.UseHangfireDashboard("/hangfire", new DashboardOptions
            {
                AppPath = "/sysadmin",
                Authorization = new[] { new HangfireSysAdminAuthFilter() }
            });
            Hangfire.GlobalConfiguration.Configuration.UseBatches();
```

**Comment by odinserj** [comment]
Some problems like this in the past were related to the `System.Data.SqlClient` package itself and some problems disappeared when it was upgraded to the latest version. But they could be explained by the nature of .NET Core (some code was completely rewritten for this platform, including portions of `System.Data.SqlClient`). But .NET Framework is expected to be more stable and we can't blame it without any evidences.

However it's theoretically possible that something is going bad for long-running connections like those with default settings in Hangfire. And new version of SQL Server can theoretically work with connections in a different way (due to different keep alive settings, firewall configurations, etc.). But I still don't understand how this can happen, and Hangfire wraps everything with `using` statements or carefully ensures that everything will be disposed.

So I will recommend you to upgrade `System.Data.SqlClient` first to the latest version (or install it explicitly to your project) and use [recommended settings](https://docs.hangfire.io/en/latest/configuration/using-sql-server.html#configuration) for Hangfire.SqlServer. I will try to re-consider the problem once again, and if the problem persists and/or you have more details, please let me know.

**Comment by andrewdavey** [comment]
Thanks for all the suggestions (and very rapid responses!)

I've installed `System.Data.SqlClient` version 4.8.2 from nuget.

My configuration is now like this:

```
            Hangfire.GlobalConfiguration.Configuration.UseSqlServerStorage(
                ConnectionStrings.Hangfire,
                new Hangfire.SqlServer.SqlServerStorageOptions
                {
                    TransactionTimeout = TimeSpan.FromMinutes(5),
                    CommandTimeout = TimeSpan.FromMinutes(5),
                    CommandBatchMaxTimeout = TimeSpan.FromMinutes(5),
                    SlidingInvisibilityTimeout = TimeSpan.FromMinutes(5),
                    QueuePollInterval = TimeSpan.Zero,
                    UseRecommendedIsolationLevel = true,
                }
            );
```

The batch I'm trying to start contains 2474 jobs.

I tried it a few times and I could see the jobs getting enqueued in the Hangfire UI, but at about 1600 it would fail and rollback. This was after about a minute.

I tried it once again and it succeeded. So I'll see if tomorrow's batch fails or not.

The SQL Server is running in AWS RDS on a db.t3.small instance, so 2 vCPU and 2GB RAM. The storage is 20GB. Monitoring the server resources didn't show any bad spikes.

**Comment by odinserj** [comment]
Ah sure, now I remember the original exception sometimes occur due to timeout due to the `TransactionScope` class that's still used by Hangfire.SqlServer on .NET Framework for backward compatibility reasons. You did the right thing with setting the `TransactionTiemout` option, please also note that it can't be more than 10 minutes by default ([config changes](https://stackoverflow.com/a/21274884) required).

> I tried it a few times and I could see the jobs getting enqueued in the Hangfire UI, but at about 1600 it would fail and rollback

What exception do you see in this case, is it the same?

**Comment by andrewdavey** [comment]
Same exception.

10 minutes should be plenty of time. I'll see how the next batch performs tonight and report back if I'm still having problems. Thanks for all the help.

**Comment by andrewdavey** [comment]
The changes seem to have to fixed the overnight batch. I'll close this issue. Thanks for all the help!
