### ISSUE TITLE
DI(Dependency Injection) Exception

### ISSUE THREAD

**Issue by AliRezaBeigy** [HangfireIO/Hangfire#1857]
I trying to create an example project to learn Hangfire in console application but i encounter with the following exception
```
Unhandled exception. System.InvalidOperationException: variable 's' of type 'HangfireTestApp.IService' referenced from scope '', but it is not defined
   at System.Linq.Expressions.Compiler.VariableBinder.Reference(ParameterExpression node, VariableStorageKind storage)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitParameter(ParameterExpression node)
...
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
   at System.Linq.Expressions.Expression`1.Compile()
   at Hangfire.Common.ExpressionUtil.CachedExpressionCompiler.Compiler`2.<>c__DisplayClass7_0.<CompileFromFingerprint>b__0(ExpressionFingerprintChain _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
...
   at Hangfire.Common.Job.GetExpressionValue(Expression expression)
   at System.Linq.Enumerable.SelectIListIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Hangfire.Common.Job.GetExpressionValues(IEnumerable`1 expressions)
...
   at Hangfire.BackgroundJobClientExtensions.Schedule[T](IBackgroundJobClient client, Expression`1 methodCall, TimeSpan delay)
   at Hangfire.BackgroundJob.Schedule[T](Expression`1 methodCall, TimeSpan delay)
   at HangfireTestApp.Program.Main(String[] args) in ...\HangfireTestApp\Program.cs:line 49
```

I'm trying to inject a service to background job but it's failed

Example Project:
https://github.com/AliRezaBeigy/HangfireTest

**Comment by bxjg1987** [comment]
Have you solved the problem? I encountered the same problem when using hangfire 1.7.33 in the asp.net core 3.1 project
