### ISSUE TITLE
When calling ContinueJobWith get SQL error - MSSQL storage

### ISSUE THREAD

**Issue by alexlightwarrior** [HangfireIO/Hangfire#1884]
Sometime I get such error : 
The INSERT statement conflicted with the FOREIGN KEY constraint "FK_HangFire_JobParameter_Job". The conflict occurred in database "master", table "HangFire.Job", column 'Id'.

I am confused because it looks like that we got jobId but did not save it but we try to save JobParameter.

```
Full exception : 
ExMessage Background job creation failed. See inner exception for details.
ExInnerException System.Data.SqlClient.SqlException (0x80131904): The INSERT statement conflicted with the FOREIGN KEY constraint "FK_HangFire_JobParameter_Job". The conflict occurred in database "master", table "HangFire.Job", column 'Id'.
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader)
at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command)
at Hangfire.SqlServer.SqlServerConnection.<>c__DisplayClass10_0.<SetJobParameter>b__0(DbConnection connection)
at Hangfire.SqlServer.SqlServerStorage.<>c__DisplayClass32_0.<UseConnection>b__0(DbConnection connection)
at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](DbConnection dedicatedConnection, Func`2 func)
at Hangfire.SqlServer.SqlServerStorage.UseConnection(DbConnection dedicatedConnection, Action`1 action)
at Hangfire.SqlServer.SqlServerConnection.SetJobParameter(String id, String name, String value)
at Hangfire.ContinuationsSupportAttribute.AddContinuation(ElectStateContext context, AwaitingState awaitingState)
at Hangfire.ContinuationsSupportAttribute.OnStateElection(ElectStateContext context)
at Hangfire.States.StateMachine.InvokeOnStateElection(Tuple`2 x)
at Hangfire.Profiling.ProfilerExtensions.InvokeAction[TInstance](InstanceAction`1 tuple)
at Hangfire.Profiling.EmptyProfiler.InvokeMeasured[TInstance,TResult](TInstance instance, Func`2 action, String message)
at Hangfire.Profiling.ProfilerExtensions.InvokeMeasured[TInstance](IProfiler profiler, TInstance instance, Action`1 action, String message)
at Hangfire.States.StateMachine.ApplyState(ApplyStateContext initialContext)
at Hangfire.Client.CoreBackgroundJobFactory.<>c__DisplayClass14_0.<Create>b__3(Int32 attempt)
at Hangfire.Client.CoreBackgroundJobFactory.<>c__DisplayClass15_0.<RetryOnException>b__0(Int32 attempt)
at Hangfire.Client.CoreBackgroundJobFactory.RetryOnException[T](Int32& attemptsLeft, Func`2 action)
--- End of stack trace from previous location where exception was thrown ---
at Hangfire.Client.CoreBackgroundJobFactory.RetryOnException[T](Int32& attemptsLeft, Func`2 action)
at Hangfire.Client.CoreBackgroundJobFactory.RetryOnException(Int32& attemptsLeft, Action`1 action)
at Hangfire.Client.CoreBackgroundJobFactory.Create(CreateContext context)
at Hangfire.Client.BackgroundJobFactory.<>c__DisplayClass12_0.<CreateWithFilters>b__0()
at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation)
at Hangfire.Client.BackgroundJobFactory.<>c__DisplayClass12_1.<CreateWithFilters>b__2()
at Hangfire.Client.BackgroundJobFactory.CreateWithFilters(CreateContext context, IEnumerable`1 filters)
at Hangfire.Client.BackgroundJobFactory.Create(CreateContext context)
at Hangfire.BackgroundJobClient.Create(Job job, IState state)
ClientConnectionId:a03238c1-04ed-4bc9-898f-5f36e636188b
Error Number:50000,State:0,Class:16
ExStackTrace at Hangfire.BackgroundJobClient.Create(Job job, IState state)
at Hangfire.BackgroundJobClientExtensions.ContinueJobWith[T](IBackgroundJobClient client, String parentId, Expression`1 methodCall, IState nextState, JobContinuationOptions options)
at Caas.OnSiteAgent.Service.Services.Processing.PublishProcessor.<>c__DisplayClass4_0.<ProcessHangfire>b__2(String k, String v) in D:\Projects\Rwe\caas-onsite-agent\Caas.OnSiteAgent.Service\Services\Processing\PublishProcessor.cs:line 84
at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, TValue addValue, Func`3 updateValueFactory)
at Caas.OnSiteAgent.Service.Services.Processing.PublishProcessor.ProcessHangfire(String sitename, String groupName, String groupMessageTopic, IDictionary`2 groupPostMetaData, Int32 deviceIDI, Double quality, IEnumerable`1 data, UpdateRule updateRule)
at Caas.OnSiteAgent.Service.Services.Processing.PublishProcessor.Process(PostOpcGroupDto group, IEnumerable`1 data, UpdateRule updateRule) in D:\Projects\Rwe\caas-onsite-agent\Caas.OnSiteAgent.Service\Services\Processing\PublishProcessor.cs:line 44
at Caas.OnSiteAgent.Service.Services.Processing.GroupUpdated.Invoke(PostOpcGroupDto group, IEnumerable`1 data, UpdateRule updateRule)
at Caas.OnSiteAgent.Service.Services.OpcDaService.GroupObjectOnDataReceived(PostOpcGroupDto group, IEnumerable`1 data) in D:\Projects\Rwe\caas-onsite-agent\Caas.OnSiteAgent.Service\Services\OpcDaService.cs:line 699
MessageTemplate XmlOpcDaService GroupObjectOnDataReceived: Background job creation failed. See inner exception for details.
Timestamp 24/05/2021 13:33:18 +01:00
```

**Comment by odinserj** [comment]
Thanks for reporting this exception. It is thrown when trying to add a continuation for already expired job. I'll make some changes to throw more friendly exception in this case, two blocks of code should be swapped.
