### ISSUE TITLE
Microsoft.Data.SqlClient - New transaction is not allowed because there are other threads running in the session.

### ISSUE THREAD

**Issue by dzerzi** [HangfireIO/Hangfire#1918]
Hi, we migrating our projects to use Microsoft.SqlClient instead of System.SqlClient which is still part of HF package. According to other topics which I've found it should be enaugh to establish connection using SqlConnection class from Microsoft namespace, however when we did it we are getting error when server tries to process Job - HF Server itself is starting up and does not crash.

SqlServer is initialized like that. 
`return new SqlServerStorage(new SqlConnection(connectionString), HangFireConstants.SqlServerStorageOptions);`

And there is one more thing - it does not work only on Docker configuration (linux)
sql img: microsoft/mssql-server-linux:2017-latest	

`[16:30:05 DBG] State change attempt 9 of 10 failed due to an error, see inner exception for details
2021-08-05T16:30:05.430583300Z Microsoft.Data.SqlClient.SqlException (0x80131904): New transaction is not allowed because there are other threads running in the session.
2021-08-05T16:30:05.430697900Z    at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
2021-08-05T16:30:05.430747700Z    at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
2021-08-05T16:30:05.430808800Z    at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
2021-08-05T16:30:05.430826000Z    at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
2021-08-05T16:30:05.430977700Z    at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
2021-08-05T16:30:05.431145600Z    at Microsoft.Data.SqlClient.TdsParser.TdsExecuteTransactionManagerRequest(Byte[] buffer, TransactionManagerRequestType request, String transactionName, TransactionManagerIsolationLevel isoLevel, Int32 timeout, SqlInternalTransaction transaction, TdsParserStateObject stateObj, Boolean isDelegateControlRequest)
2021-08-05T16:30:05.431155900Z    at Microsoft.Data.SqlClient.SqlInternalConnectionTds.ExecuteTransactionYukon(TransactionRequest transactionRequest, String transactionName, IsolationLevel iso, SqlInternalTransaction internalTransaction, Boolean isDelegateControlRequest)
2021-08-05T16:30:05.431160700Z    at Microsoft.Data.SqlClient.SqlInternalConnectionTds.ExecuteTransaction(TransactionRequest transactionRequest, String name, IsolationLevel iso, SqlInternalTransaction internalTransaction, Boolean isDelegateControlRequest)
2021-08-05T16:30:05.431165300Z    at Microsoft.Data.SqlClient.SqlInternalConnection.BeginSqlTransaction(IsolationLevel iso, String transactionName, Boolean shouldReconnect)
2021-08-05T16:30:05.431172500Z    at Microsoft.Data.SqlClient.SqlConnection.BeginTransaction(IsolationLevel iso, String transactionName)
2021-08-05T16:30:05.431182500Z    at Microsoft.Data.SqlClient.SqlConnection.BeginTransaction(IsolationLevel iso)
2021-08-05T16:30:05.431188900Z    at Microsoft.Data.SqlClient.SqlConnection.BeginDbTransaction(IsolationLevel isolationLevel)
2021-08-05T16:30:05.431194900Z    at System.Data.Common.DbConnection.BeginTransaction(IsolationLevel isolationLevel)
2021-08-05T16:30:05.431212600Z    at Hangfire.SqlServer.SqlServerStorage.<>c__DisplayClass35_0`1.<UseTransaction>b__0(DbConnection connection)
2021-08-05T16:30:05.431219400Z    at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](DbConnection dedicatedConnection, Func`2 func)
2021-08-05T16:30:05.431225300Z    at Hangfire.SqlServer.SqlServerStorage.UseTransaction[T](DbConnection dedicatedConnection, Func`3 func, Nullable`1 isolationLevel)
2021-08-05T16:30:05.431231500Z    at Hangfire.SqlServer.SqlServerStorage.UseTransaction(DbConnection dedicatedConnection, Action`2 action)
2021-08-05T16:30:05.431238300Z    at Hangfire.SqlServer.SqlServerWriteOnlyTransaction.Commit()
2021-08-05T16:30:05.431244000Z    at Hangfire.Batches.BatchJobSupportAttribute.OnStateApplied(ApplyStateContext context, IWriteOnlyTransaction outerTransaction)
2021-08-05T16:30:05.431249700Z    at Hangfire.States.StateMachine.InvokeOnStateApplied(Tuple`2 x)
2021-08-05T16:30:05.431254900Z    at Hangfire.Profiling.ProfilerExtensions.InvokeAction[TInstance](InstanceAction`1 tuple)
2021-08-05T16:30:05.431260500Z    at Hangfire.Profiling.SlowLogProfiler.InvokeMeasured[TInstance,TResult](TInstance instance, Func`2 action, String message)
2021-08-05T16:30:05.431267200Z    at Hangfire.Profiling.ProfilerExtensions.InvokeMeasured[TInstance](IProfiler profiler, TInstance instance, Action`1 action, String message)
2021-08-05T16:30:05.431273900Z    at Hangfire.States.StateMachine.ApplyState(ApplyStateContext initialContext)
2021-08-05T16:30:05.431279700Z    at Hangfire.States.BackgroundJobStateChanger.ChangeState(StateChangeContext context)
2021-08-05T16:30:05.431289500Z    at Hangfire.Server.Worker.TryChangeState(BackgroundProcessContext context, IStorageConnection connection, IFetchedJob fetchedJob, IState state, String[] expectedStates, CancellationToken initializeToken, CancellationToken abortToken)
2021-08-05T16:30:05.431296100Z `

**There is also similar issue when trying to enque job from Dashboard:**

`Hangfire.BackgroundJobClientException: State change of a background job failed. See inner exception for details
2021-08-06T07:09:14.498248400Z  ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
2021-08-06T07:09:14.498258600Z Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
2021-08-06T07:09:14.498344500Z The request failed to run because the batch is aborted, this can be caused by abort signal sent from client, or another request is running in the same session, which makes the session busy.
2021-08-06T07:09:14.498358200Z Operation cancelled by user.
2021-08-06T07:09:14.498361800Z  ---> System.ComponentModel.Win32Exception (258): Unknown error 258
2021-08-06T07:09:14.498365100Z    at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
2021-08-06T07:09:14.498368400Z    at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
2021-08-06T07:09:14.498371800Z    at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
2021-08-06T07:09:14.498375300Z    at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
2021-08-06T07:09:14.498378900Z    at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
2021-08-06T07:09:14.498383800Z    at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
2021-08-06T07:09:14.498466300Z    at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
2021-08-06T07:09:14.498470500Z    at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
2021-08-06T07:09:14.498473700Z    at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader)
2021-08-06T07:09:14.498476900Z    at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command)
2021-08-06T07:09:14.498480000Z    at Hangfire.SqlServer.SqlServerDistributedLock.Acquire(IDbConnection connection, String resource, TimeSpan timeout)
2021-08-06T07:09:14.498483700Z    at Hangfire.SqlServer.SqlServerConnection.AcquireLock(String resource, TimeSpan timeout)
2021-08-06T07:09:14.498486800Z    at Hangfire.SqlServer.SqlServerConnection.AcquireDistributedLock(String resource, TimeSpan timeout)
2021-08-06T07:09:14.498489900Z    at Hangfire.Storage.StorageConnectionExtensions.AcquireDistributedJobLock(IStorageConnection connection, String jobId, TimeSpan timeout)
2021-08-06T07:09:14.498497200Z    at Hangfire.States.BackgroundJobStateChanger.ChangeState(StateChangeContext context)
2021-08-06T07:09:14.498500500Z    at Hangfire.BackgroundJobClient.ChangeState(String jobId, IState state, String expectedState)
2021-08-06T07:09:14.498503600Z ClientConnectionId:738476ae-c62a-4480-8876-d1b72e32871f
2021-08-06T07:09:14.498506700Z Error Number:-2,State:0,Class:11
2021-08-06T07:09:14.498509600Z    --- End of inner exception stack trace ---
2021-08-06T07:09:14.498512600Z    at Hangfire.BackgroundJobClient.ChangeState(String jobId, IState state, String expectedState)
2021-08-06T07:09:14.498515700Z    at Hangfire.BackgroundJobClientExtensions.ChangeState(IBackgroundJobClient client, String jobId, IState state)
2021-08-06T07:09:14.498550100Z    at Hangfire.Dashboard.DashboardRoutes.<>c.<.cctor>b__2_22(DashboardContext context)
2021-08-06T07:09:14.498558200Z    at Hangfire.Dashboard.CommandDispatcher.Dispatch(DashboardContext context)
2021-08-06T07:09:14.498562000Z    at Hangfire.Dashboard.AspNetCoreDashboardMiddleware.Invoke(HttpContext httpContext)
2021-08-06T07:09:14.498565400Z    at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
2021-08-06T07:09:14.498568800Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)`

Edit:
Intalling System.Data.SqlClient with version 4.8.2 even when using Microsoft SqlConnection class works fine, so I assume there is some 'conflict' between  both packages. (microsoft is 2.1.3)

**Comment by odinserj** [comment]
Please use connection factory function instead of a specific connection, e.g. `() => new SqlConnection(...)` instead of `new SqlConnection(...)`:

```csharp
return new SqlServerStorage(() => new SqlConnection(connectionString), HangFireConstants.SqlServerStorageOptions);
```

**Comment by dzerzi** [comment]
> Please use connection factory function instead of a specific connection, e.g. `() => new SqlConnection(...)` instead of `new SqlConnection(...)`:
> 
> ```cs
> return new SqlServerStorage(() => new SqlConnection(connectionString), HangFireConstants.SqlServerStorageOptions);
> ```

It did the trick :-) 

So I'm closing this ticket since issue is solved and as far as I understand from other topics in some future there will be option to use Microsoft package without tricks ;-)
