### ISSUE TITLE
Hangfire.Pro.Redis fails if Redis has additional modules installed

### ISSUE THREAD

**Issue by v-zubritsky** [HangfireIO/Hangfire#2095]
### Environment

Redis: Docker `redis/redis-stack:latest`
Hangfire.Pro.Redis: 2.8.17

### Problem

`RedisStorage.GetInfoMetric` assumes that `server.Info()` returns unique entries only and tries to build dictionary out of them, but uniqueness isn't guaranteed. 

**Exception**
```
System.ArgumentException: An item with the same key has already been added. Key: module
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Hangfire.Pro.Redis.RedisStorage.<>c__DisplayClass29_0.<GetInfoMetric>b__0(RazorPage page)
   at Hangfire.Dashboard.Pages.BlockMetric.Execute()
   at Hangfire.Dashboard.RazorPage.TransformText(String body)
   at Hangfire.Dashboard.HtmlHelper.BlockMetric(DashboardMetric metric)
   at Hangfire.Dashboard.Pages.HomePage.Execute()
   at Hangfire.Dashboard.RazorPage.TransformText(String body)
   at Hangfire.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context)
   at Hangfire.Dashboard.AspNetCoreDashboardMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

`redis-cli info`
Note how `module:name` is repeated a few times. 
```
# Server
redis_version:6.2.7
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:adcdff4a0d295794
redis_mode:standalone
os:Linux 5.10.102.1-microsoft-standard-WSL2 x86_64
arch_bits:64
monotonic_clock:POSIX clock_gettime
multiplexing_api:epoll
atomicvar_api:c11-builtin
gcc_version:9.4.0
process_id:10
process_supervised:no
run_id:f660b0fa21432cb441008aa4b45ac615b85dbc71
tcp_port:6379
server_time_usec:1663861394209716
uptime_in_seconds:1030
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:2917010
executable:/opt/redis-stack/bin/redis-server
config_file:
io_threads_active:0

# Clients
connected_clients:7
cluster_connections:0
maxclients:10000
client_recent_max_input_buffer:48
client_recent_max_output_buffer:0
blocked_clients:0
tracking_clients:0
clients_in_timeout_table:0

# Memory
used_memory:1211408
used_memory_human:1.16M
used_memory_rss:21958656
used_memory_rss_human:20.94M
used_memory_peak:1249872
used_memory_peak_human:1.19M
used_memory_peak_perc:96.92%
used_memory_overhead:1134800
used_memory_startup:1006696
used_memory_dataset:76608
used_memory_dataset_perc:37.42%
allocator_allocated:1365624
allocator_active:1794048
allocator_resident:5214208
total_system_memory:14568165376
total_system_memory_human:13.57G
used_memory_lua:38912
used_memory_lua_human:38.00K
used_memory_scripts:848
used_memory_scripts_human:848B
number_of_cached_scripts:2
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.31
allocator_frag_bytes:428424
allocator_rss_ratio:2.91
allocator_rss_bytes:3420160
rss_overhead_ratio:4.21
rss_overhead_bytes:16744448
mem_fragmentation_ratio:18.47
mem_fragmentation_bytes:20770024
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:123040
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0
lazyfreed_objects:0

# Persistence
loading:0
current_cow_size:0
current_cow_size_age:0
current_fork_perc:0.00
current_save_keys_processed:0
current_save_keys_total:0
rdb_changes_since_last_save:110
rdb_bgsave_in_progress:0
rdb_last_save_time:1663861267
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:0
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:688128
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0

# Stats
total_connections_received:11
total_commands_processed:3826
instantaneous_ops_per_sec:0
total_net_input_bytes:266910
total_net_output_bytes:143982
instantaneous_input_kbps:0.01
instantaneous_output_kbps:2.82
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:17
evicted_keys:0
keyspace_hits:839
keyspace_misses:434
pubsub_channels:1
pubsub_patterns:0
latest_fork_usec:383
total_forks:3
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_error_replies:4
dump_payload_sanitizations:0
total_reads_processed:1189
total_writes_processed:1184
io_threaded_reads_processed:0
io_threaded_writes_processed:0

# Replication
role:master
connected_slaves:0
master_failover_state:no-failover
master_replid:5d794b378cda9ab2fcc6b4a0894a4aad32586682
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.763270
used_cpu_user:0.778442
used_cpu_sys_children:0.000000
used_cpu_user_children:0.006152
used_cpu_sys_main_thread:0.749092
used_cpu_user_main_thread:0.745805

# Modules
module:name=timeseries,ver=10617,api=1,filters=0,usedby=[],using=[],options=[handle-io-errors]
module:name=graph,ver=20819,api=1,filters=0,usedby=[],using=[ReJSON],options=[]
module:name=ReJSON,ver=20200,api=1,filters=0,usedby=[search|graph],using=[],options=[handle-io-errors]
module:name=search,ver=20414,api=1,filters=0,usedby=[],using=[ReJSON],options=[handle-io-errors]
module:name=bf,ver=20218,api=1,filters=0,usedby=[],using=[],options=[]

# Errorstats
errorstat_ERR:count=4

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=79,expires=0,avg_ttl=0
```

**Comment by odinserj** [comment]
Thank you for such a detailed description, I was able to identify and fix everything in minutes! The fix is coming in version 2.8.18 which will be released in an hour.

**Comment by v-zubritsky** [comment]
@odinserj Cool, thank you! We'll let you know, once checked.

**Comment by v-zubritsky** [comment]
@odinserj Works as intended. Thanks again!
