### ISSUE TITLE
Problem with a job that is enqueued multiple times on azure web app

### ISSUE THREAD

**Issue by NicolaiJee** [HangfireIO/Hangfire#2102]
I have a job that is defined like this:
```
RecurringJob.AddOrUpdate<ElasticSearchHelper>("Elastic_cleanup",
              e => e.DeleteInvalidDocuments(null!, CancellationToken.None), "* 3 * * *");
```
My hangfire setup in program.cs looks like this:
```
builder.Services.AddHangfire(configuration => configuration
            .SetDataCompatibilityLevel(CompatibilityLevel.Version_170)
            .UseSimpleAssemblyNameTypeSerializer()
            .UseRecommendedSerializerSettings()
            .UseConsole()
            .UseSqlServerStorage(builder.Configuration.GetConnectionString("AddressDatabase"))); ;

builder.Services.AddHangfireServer();

app.UseHangfireDashboard("/hangfire", new DashboardOptions
{
    Authorization = new[] { new HangfireAuthorizationFilter() }
});

```
The HangfireAuthorizationFilter is just a IP limiter.

I am running the latest versions of hangfire and hangfire.sqlserver.

My classes are injected as Transient

`builder.Services.AddTransient<ElasticSearchHelper>();`

I only have one server:
![image](https://user-images.githubusercontent.com/2285823/194247235-e3135748-b9d3-49c7-bd83-cd53a068c39d.png)

I only have one instance of the web app in Azure:
![image](https://user-images.githubusercontent.com/2285823/194247447-992b06be-b22f-4902-8a00-e392300404da.png)

Every morning my queue looks like this:
![image](https://user-images.githubusercontent.com/2285823/194246391-b51bc865-d228-430e-a938-1ec5767c3012.png)

Have I setup anything wrong or is this a bug ?
I am using the same setup other places, where I don't have any issues.
I hope you can help me.

**Comment by NicolaiJee** [comment]
I did further investigation into this and some of the jobs has this exception, but not all of them.
Hangfire.Storage.DistributedLockTimeoutException: Timeout expired. The timeout elapsed prior to obtaining a distributed lock on the 'HangFire:ElasticSearchHelper.DeleteInvalidDocuments' resource.
   at Hangfire.SqlServer.SqlServerDistributedLock.Acquire(IDbConnection connection, String resource, TimeSpan timeout)
   at Hangfire.SqlServer.SqlServerConnection.AcquireLock(String resource, TimeSpan timeout)
   at Hangfire.SqlServer.SqlServerConnection.AcquireDistributedLock(String resource, TimeSpan timeout)
   at Hangfire.DisableConcurrentExecutionAttribute.OnPerforming(PerformingContext filterContext)
   at Hangfire.Profiling.ProfilerExtensions.InvokeAction[TInstance](InstanceAction`1 tuple)
   at Hangfire.Profiling.SlowLogProfiler.InvokeMeasured[TInstance,TResult](TInstance instance, Func`2 action, String message)
   at Hangfire.Profiling.ProfilerExtensions.InvokeMeasured[TInstance](IProfiler profiler, TInstance instance, Action`1 action, String message)
   at Hangfire.Server.BackgroundJobPerformer.InvokePerformFilter(IServerFilter filter, PerformingContext preContext, Func`1 continuation)

I tried adding a semaphore and will see if that helps.

I also added disableconcurrent execution.
