### ISSUE TITLE
Cannot access a disposed object (LoggerFactory)

### ISSUE THREAD

**Issue by aleksvujic** [HangfireIO/Hangfire#2147]
We are using .NET 6, [Hangfire.AspNetCore 1.7.31](https://www.nuget.org/packages/Hangfire.AspNetCore/1.7.31) and [Hangfire.InMemory 0.3.4](https://github.com/HangfireIO/Hangfire.InMemory/). This is how we configure Hangfire in `Startup.cs`:

```cs
public void ConfigureServices(IServiceCollection services)
{
  // ...
  
  services.AddHangfire(configuration =>
  {
    configuration.UseInMemoryStorage();
  });

  services.AddHangfireServer(x =>
  {
    x.WorkerCount = 5;
  });
  
  // ...
}
```

We have a unit test which calls `RecurringJob.RemoveIfExists("jobId")` somewhere in its body. This test was working for a long time and failed randomly today. We re-ran the test multiple times but we were unable to reproduce the exception.

Error message:
```
System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'LoggerFactory'.
```

Stacktrace:
```
at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)
at Hangfire.AspNetCore.AspNetCoreLogProvider.GetLogger(String name)
at Hangfire.Logging.LogProvider.GetLogger(String name)
at Hangfire.Logging.LogProvider.GetLogger(Type type)
at Hangfire.Client.CoreBackgroundJobFactory..ctor(IStateMachine stateMachine)
at Hangfire.Client.BackgroundJobFactory..ctor(IJobFilterProvider filterProvider)
at Hangfire.RecurringJobManager..ctor(JobStorage storage, IJobFilterProvider filterProvider, ITimeZoneResolver timeZoneResolver, Func`1 nowFactory)
at Hangfire.RecurringJobManager..ctor(JobStorage storage, IJobFilterProvider filterProvider, ITimeZoneResolver timeZoneResolver)
at Hangfire.RecurringJobManager..ctor(JobStorage storage, IJobFilterProvider filterProvider)
at Hangfire.RecurringJobManager..ctor(JobStorage storage)
at Hangfire.RecurringJobManager..ctor()
at Hangfire.RecurringJob.<>c.<.cctor>b__21_0()
at System.Lazy`1.PublicationOnlyViaFactory(LazyHelper initializer)
at System.Lazy`1.CreateValue()
at Hangfire.RecurringJob.RemoveIfExists(String recurringJobId)
at OurApplication.Service.BL.Identity.OurServiceBL.DeleteHangfireRecurringJobIfHangfireIsEnabled(String jobId)
```

Why did the exception occur? How can we prevent it from happening again?

**Comment by maxcherednik** [comment]
We are experiencing the same issue since recently.

After looking into the codebase we have a guess that it is related to this line of code: 
![image](https://user-images.githubusercontent.com/4208513/211338832-af22c3c8-2fbe-447d-8a1f-a33dd2a1361f.png)

**What is happening:**
1. We are in the xUnit context
2. There are several integration tests running in parallel
3. They are stepping on each others toes around that shared static field

There were cases like this before: https://github.com/HangfireIO/Hangfire/issues/1099
I don't think it was actually fixed.

**Comment by odinserj** [comment]
For the original question, this exception is thrown likely because ASP.NET Core host is shutting down. And in this case we should understand why this happens, and especially why we are executing business logic after application is shutting down, because in this case it is expected that nothing will be called.

Regarding unit tests, Hangfire for historical reasons uses static fields for its configuration and perhaps the best way is to avoid running such tests in parallel.

**Comment by maxcherednik** [comment]
1. Within 1 test nothing is been executed after the server is disposed.
2. We can not run those test cases sequentially. It does not make any sense for us.

Something like this is happening:
![image](https://user-images.githubusercontent.com/4208513/211491935-dcfac1ab-f0f0-4bda-b803-42bdb4ca980e.png)

As a workaround, I had to disable the hangfire Hosted service from starting in the tests.

**Potential solution:**
Since LibLog is discontinued, maybe it is time to take the dependency on _Microsoft.Extensions.Logging_

**Comment by odinserj** [comment]
With serial tests you'll be able to call `LogProvider.SetCurrentLogProvider` before each test runs, so that each test will have a fresh logging provider instance. If you are using non-static `BackgroundJobClient` or `RecurringJobManager` classes instead of static `Background/RecurringJob` that you'll have no static logger references.

Or alternatively you can just use `NoOpLogProvider` to avoid using logger from .NET Core that throws exceptions after being disposed.

There are no problems with LibLog, exception is arising from Microsoft's log provider that was disposed.

**Comment by maxcherednik** [comment]
> There are no problems with LibLog, exception is arising from Microsoft's log provider that was disposed.

It is not a problem, it is a design limitation of the LibLog. It sets a static variable. The tests are in the common process space. Hence, overlapping.

> Microsoft's log provider that was disposed.
That is correct. I asked it to. That is what is happening when the test case is over. But the reference(the wrong one by the way) to the log provider got stuck in the static field.

**Comment by odinserj** [comment]
Static configuration unfortunately is the problem for Hangfire itself, not only for LibLog.

**Comment by mmigala** [comment]
I also disabled Hangfire from running in Integration tests for now...

Since we are using .NET 6 and NUnit for integration tests I've overridden implementation of Hangfire interface that does nothing.

Posting since maybe it will be useful for someone.

`public class CustomWebApplicationFactory : WebApplicationFactory<Program>
{
    protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        builder.ConfigureServices(OverrideExistingHangfireInterfaceImplementation);
    }

    private static void OverrideExistingHangfireInterfaceImplementation(IServiceCollection services)
    {
        // Find the existing registration and remove it
        var descriptor = services.SingleOrDefault(
            d => d.ServiceType ==
                 typeof(IHangfireRecurringJobManager));
        if (descriptor != null)
        {
            services.Remove(descriptor);
        }

        // Add a new registration
        services.AddTransient<IHangfireRecurringJobManager, StubHangfireRecurringJobManager>();
    }
}

public class StubHangfireRecurringJobManager : IHangfireRecurringJobManager
{
    public void AddOrUpdate(string recurringJobId, Expression<Action> methodCall, string cronExpression)
    {
    }

    public void AddOrUpdate(string recurringJobId, Expression<Func<Task>> methodCall, string cronExpression)
    {
    }

    public void RemoveIfExists(string recurringJobId)
    {
    }
}`

**Comment by rossknudsen** [comment]
I was experiencing an issue with using `AutomaticRetryAttribute` in my unit tests that produced the same issue as described by OP.  I found that in my case, I could provide an alternative implementation to the built in one, as a workaround:

```cs
internal class NoRetryAttribute : JobFilterAttribute, IElectStateFilter
{
    public void OnStateElection(ElectStateContext context)
    {
        // No-op overrides the default retry behaviour.
    }
}
```

I then use it in my unit test setup like:

```cs
// For testing purposes, we will not perform any retries.
GlobalConfiguration.Configuration.UseFilter(new NoRetryAttribute());
```

Note: I'm using AspNetCore, .Net 8.0 and implementing Integration tests along the lines of the [MS recommendations](https://learn.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-8.0#customize-webapplicationfactory).
