### ISSUE TITLE
Hangfire multiple servers, potentially lead to certain jobs unable to run on schedule

### ISSUE THREAD

**Issue by thye1997** [HangfireIO/Hangfire#2155]
Hi there, recently i deployed my hangfire app to one of the on premise server hosted with IIS and found the issue below.
![902b1a74-4fd1-47c3-9bb8-d74b11e7c6af](https://user-images.githubusercontent.com/53056194/211206137-f061be62-6301-434e-b124-b34e6b386ddd.jpg)
Some of my jobs hit "unable to load the job, see inner exception when trying to run." I looked for certain discussion online and i saw some of the people mentioning "Ghost app" that could possibly cause the hangfire job to hit error. May i know how to kill this "Ghos app"?

**Comment by wobbet** [comment]
I am seeing very similar issues... 

I'm running a .NET Core 8 WebAPI app. I have included Hangfire.AspNetCore 1.8.* in my NuGet library references. 

My code for Hangfire Service Configuration
```        #region Hangfire Service Configuration
        builder.Services.AddHangfire(config => config
            .UseSimpleAssemblyNameTypeSerializer()
            .UseRecommendedSerializerSettings()
            .UsePostgreSqlStorage(c => c.UseNpgsqlConnection(builder.Configuration.GetConnectionString("hangfire")))
        );
        builder.Services.AddHangfireServer((opts) => {
            opts.WorkerCount = 1;
            opts.Queues = ["atlasdatasyncqueue"];
            opts.ServerName = "AtlasDataSyncServer";
        });
        #endregion
```

My code to add the dashboard and start a recurring job...
```       _App.UseHangfireDashboard();

        var tab = "*/3 * * * *";
        RecurringJob.AddOrUpdate("Run Tenant Sync", "atlasdatasyncqueue", () => SyncApp.RunTenantSync(), tab);
```

In this image, ignore the server with the error. I killed it in a debug session and then started a new debug session. What is worrying to me is that there is a server that I did not intentionally create with the default of 20 workers using the default queue... 
![image](https://github.com/HangfireIO/Hangfire/assets/6975318/48abcc5c-bba9-4914-a1e3-6014fac90b28)

What will happen is that eventually I will get an error in my recurring job saying that Hangfire could not load my application code. From all appearance that is from the default server launching the recurring job even though the recurring job is supposed to be running in a non-default queue. Exception stack trace is below.

When this happens, the recurring job stops running because there are too many retries.

How can I prevent this from happening? I don't mind the "ghost" server being there, as long as it isn't interfering with my jobs running. I'd prefer that it NOT be there, but if it isn't causing issues I can live with it. But it IS causing issues.

How do I ensure this doesn't happen?

Thanks!



```Hangfire.Common.JobLoadException: Could not load the job. See inner exception for the details.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'atlas_sync, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'atlas_sync, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.<InternalLoad>g____PInvoke|49_0(NativeAssemblyNameParts* __pAssemblyNameParts_native, ObjectHandleOnStack __requestingAssembly_native, StackCrawlMarkHandle __stackMark_native, Int32 __throwOnFileNotFound_native, ObjectHandleOnStack __assemblyLoadContext_native, ObjectHandleOnStack __retAssembly_native)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Hangfire.Common.TypeHelper.AssemblyResolver(String assemblyString) in C:\projects\hangfire-525\src\Hangfire.Core\Common\TypeHelper.cs:line 217
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Hangfire.Common.TypeHelper.CachedAssemblyResolver(AssemblyName assemblyName) in C:\projects\hangfire-525\src\Hangfire.Core\Common\TypeHelper.cs:line 180
   at System.Reflection.TypeNameParser.ResolveAssembly(String assemblyName)
   at System.Reflection.TypeNameParser.GetType(String typeName, ReadOnlySpan`1 nestedTypeNames, String assemblyNameIfAny)
   at System.Reflection.TypeNameParser.NamespaceTypeName.ResolveType(TypeNameParser& parser, String containingAssemblyIfAny)
   at System.Type.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError)
   at Hangfire.Common.TypeHelper.DefaultTypeResolver(String typeName) in C:\projects\hangfire-525\src\Hangfire.Core\Common\TypeHelper.cs:line 78
   at Hangfire.Storage.InvocationData.DeserializeJob() in C:\projects\hangfire-525\src\Hangfire.Core\Storage\InvocationData.cs:line 96
   --- End of inner exception stack trace ---
   at Hangfire.Storage.InvocationData.DeserializeJob() in C:\projects\hangfire-525\src\Hangfire.Core\Storage\InvocationData.cs:line 120
   at Hangfire.RecurringJobExtensions.TriggerRecurringJob(IBackgroundJobFactory factory, JobStorage storage, IStorageConnection connection, IProfiler profiler, RecurringJobEntity recurringJob, DateTime now) in C:\projects\hangfire-525\src\Hangfire.Core\RecurringJobExtensions.cs:line 115
   at Hangfire.Server.RecurringJobScheduler.ScheduleRecurringJob(BackgroundProcessContext context, IStorageConnection connection, String recurringJobId, RecurringJobEntity recurringJob, DateTime now) in C:\projects\hangfire-525\src\Hangfire.Core\Server\RecurringJobScheduler.cs:line 333
```

**Comment by wobbet** [comment]
I finally got mine resolved.

Today I learned that the queue attribute for jobs does NOT mean the job will run only in servers that support that queue. Any server can pick it up. And if it gets picked up by a server that doesn't have the code for that job available, that server will give the stack trace above and cause the job to error out, preventing servers that do support the queue from servicing the job. 

That is... sub-optimal.

The workaround that I'm using is to create a new schema for each application that I'm running. Each application has a set of jobs that it is responsible for. So each app stores data in it's own schema, independent of the other applications. 

That still allows a single database to support multiple applications.

I really wish the Hangfire documentation was better.
