### ISSUE TITLE
(Included Example Code) "Value cannot be null. (Parameter 'method')" when using contravariant generic interface

### ISSUE THREAD

**Issue by RyanGaudion** [HangfireIO/Hangfire#2171]
I get the below exception:
StackTrace:
```
   at Hangfire.Common.Job..ctor(Type type, MethodInfo method, Object[] args)
   at Hangfire.Common.Job.FromExpression(LambdaExpression methodCall, Type explicitType)
   at Hangfire.Common.Job.FromExpression(Expression`1 methodCall)
   at Hangfire.BackgroundJobClientExtensions.Create(IBackgroundJobClient client, Expression`1 methodCall, IState state)
   at Hangfire.BackgroundJobClientExtensions.Enqueue(IBackgroundJobClient client, Expression`1 methodCall)
   at Hangfire.BackgroundJob.Enqueue(Expression`1 methodCall)
   at Program.<Main>$(String[] args) in ...
```
Message: `Value cannot be null. (Parameter 'method')`
Source: "Hangfire.Core"
ParamName: "Method"

I have made a Minimal Code Example that throws the exception using these versions:
Hangfire.Core: 1.7.33
Hangfire.InMemory: 0.3.6 (Same error occurs using other providers, just using this for demo below) 
DotNet: 7.0
```
using Hangfire;
using Microsoft.Extensions.DependencyInjection;

Console.WriteLine("Hello, World!");

ServiceCollection services = new ServiceCollection();
services.AddTransient<MyBaseClassService>();
services.AddTransient<IServiceInterface<MyBaseClass>>((s) => s.GetRequiredService<MyBaseClassService>());
services.AddTransient<IServiceInterface<MyDerivedClass>>((s) => s.GetRequiredService<MyBaseClassService>());

var sp = services.BuildServiceProvider();

GlobalConfiguration.Configuration.UseInMemoryStorage();

using (var server = new BackgroundJobServer())
{
    IServiceInterface<MyBaseClass> service = new MyBaseClassService();

    MyDerivedClass myClass = new MyDerivedClass();

    BackgroundJob.Enqueue(() => Console.WriteLine("Background!"));

    var classServices = sp.GetServices<IServiceInterface<MyDerivedClass>>();

    foreach(var myService in classServices)
    {
        myService.MyMethod(myClass); //This works
    }

    try
    {
        foreach (var myService in classServices)
        {
            BackgroundJob.Enqueue(() => myService.MyMethod(myClass)); //This fails
        }
    }
    catch(Exception ex)
    {

    }

    Console.ReadKey();
}

class MyBaseClass
{
    public string BaseProp { get; set; }
}

class MyDerivedClass : MyBaseClass
{
    public int MyProperty { get; set; }
}

interface IServiceInterface <in T> where T : MyBaseClass
{
    public Task MyMethod(T input);
}

class MyBaseClassService : IServiceInterface<MyBaseClass>
{
    public Task MyMethod(MyBaseClass input)
    {
        return Task.CompletedTask;
    }
}
```

Is there any reason why these method calls can't be enqueued to Hangfire?

**Comment by odinserj** [comment]
Hmm this is what I get after copy-pasting the source code above:

```
/usr/local/share/dotnet/dotnet /Users/odinserj/RiderProjects/WebApplication9/WebApplication9/bin/Debug/net7.0/WebApplication9.dll
Hello, World!
Background!
```

Can it be possible that something is missing?

```csharp
using Hangfire;

Console.WriteLine("Hello, World!");

ServiceCollection services = new ServiceCollection();
services.AddTransient<MyBaseClassService>();
services.AddTransient<IServiceInterface<MyBaseClass>>((s) => s.GetRequiredService<MyBaseClassService>());
services.AddTransient<IServiceInterface<MyDerivedClass>>((s) => s.GetRequiredService<MyBaseClassService>());

var sp = services.BuildServiceProvider();

GlobalConfiguration.Configuration.UseInMemoryStorage();

using (var server = new BackgroundJobServer())
{
    IServiceInterface<MyBaseClass> service = new MyBaseClassService();

    MyDerivedClass myClass = new MyDerivedClass();

    BackgroundJob.Enqueue(() => Console.WriteLine("Background!"));

    var classServices = sp.GetServices<IServiceInterface<MyDerivedClass>>();

    foreach(var myService in classServices)
    {
        myService.MyMethod(myClass); //This works
    }

    try
    {
        foreach (var myService in classServices)
        {
            BackgroundJob.Enqueue(() => myService.MyMethod(myClass)); //This fails
        }
    }
    catch(Exception ex)
    {

    }

    Console.ReadKey();
}

class MyBaseClass
{
    public string BaseProp { get; set; }
}

class MyDerivedClass : MyBaseClass
{
    public int MyProperty { get; set; }
}

interface IServiceInterface <in T> where T : MyBaseClass
{
    public Task MyMethod(T input);
}

class MyBaseClassService : IServiceInterface<MyBaseClass>
{
    public Task MyMethod(MyBaseClass input)
    {
        return Task.CompletedTask;
    }
}
```

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Hangfire.NetCore" Version="1.7.33" />
        <PackageReference Include="Hangfire.InMemory" Version="0.3.6" />
    </ItemGroup>

</Project>
```

**Comment by RyanGaudion** [comment]
@odinserj if you put a breakpoint in the catch below `//This fails` you'll see that when enqueuing the code throws an exception and doesn't actually enqueue. This should run however it throws an error instead (I've just caught the exception just to help with debugging).

To see the code fail, try without the try catch:

```
using Hangfire;
using Microsoft.Extensions.DependencyInjection;

Console.WriteLine("Hello, World!");

ServiceCollection services = new ServiceCollection();
services.AddTransient<MyBaseClassService>();
services.AddTransient<IServiceInterface<MyBaseClass>>((s) => s.GetRequiredService<MyBaseClassService>());
services.AddTransient<IServiceInterface<MyDerivedClass>>((s) => s.GetRequiredService<MyBaseClassService>());

var sp = services.BuildServiceProvider();

GlobalConfiguration.Configuration.UseInMemoryStorage();

using (var server = new BackgroundJobServer())
{
    IServiceInterface<MyBaseClass> service = new MyBaseClassService();

    MyDerivedClass myClass = new MyDerivedClass();

    BackgroundJob.Enqueue(() => Console.WriteLine("Background!"));

    var classServices = sp.GetServices<IServiceInterface<MyDerivedClass>>();

    foreach (var myService in classServices)
    {
        myService.MyMethod(myClass); //This works
    }

    foreach (var myService in classServices)
    {
        BackgroundJob.Enqueue(() => myService.MyMethod(myClass)); //This fails
    }

    Console.ReadKey();
}

class MyBaseClass
{
    public string BaseProp { get; set; }
}

class MyDerivedClass : MyBaseClass
{
    public int MyProperty { get; set; }
}

interface IServiceInterface<in T> where T : MyBaseClass
{
    public Task MyMethod(T input);
}

class MyBaseClassService : IServiceInterface<MyBaseClass>
{
    public Task MyMethod(MyBaseClass input)
    {
        return Task.CompletedTask;
    }
}
```

**Comment by RyanGaudion** [comment]
In the example above, I'm showing in the first foreach loop that the method works when called normally and in the second foreach loop how the method doesn't work when queued in the background using hangfire

**Comment by RyanGaudion** [comment]
@odinserj did the above example throw an exception for you?

**Comment by odinserj** [comment]
Thanks for helping to narrow down the issue! I've just committed the fix so that it will be released with 1.7.34 likely tomorrow.

**Comment by dehaaneric** [comment]
I have the same issue :(. Using Hangfire 1.7.36 (incl. Pro subscription)

Small app to repro the issue:

```
namespace HangfireGeneric.ConsoleApp
{
    internal class Program
    {
        static void Main(string[] args)
        {
            ServiceCollection services = new ServiceCollection();
            services.AddTransient<IFetchAndStoreTranslationJob, FetchAndStoreTranslationJob>();

            var sp = services.BuildServiceProvider();

            GlobalConfiguration.Configuration.UseMemoryStorage();

            var service = sp.GetRequiredService<IFetchAndStoreTranslationJob>();

            BackgroundJob.Enqueue(() => service.Execute<TranslatedResource>(new TranslatableResourceMeta("ea875444-ae15-4a23-bae4-b3175a7cfa80"), "fr"));
        }
    }

    public interface IFetchAndStoreTranslationJob
    {
        Task Execute<T>(TranslatableResourceMeta translatableResourceMeta, string language)
            where T : ITranslatedResource;
    }

    public sealed class FetchAndStoreTranslationJob : IFetchAndStoreTranslationJob
    {
        public async Task Execute<T>(TranslatableResourceMeta translatableResourceMeta, string language)
            where T : ITranslatedResource
        {
            // Fetch the Translation Strategy registered for type T
            // ITranslationStrategy<T>? translationStrategy =
            //    _serviceProvider.GetRequiredService<ITranslationStrategy<T>>();

            // Do stuff with the provided strategy
        }
    }

    public sealed class TranslatableResourceMeta
    {
        public TranslatableResourceMeta(string id) => Id = id;

        public string Id { get; }
    }

    public interface ITranslatedResource { }
    public class TranslatedResource : ITranslatedResource { }
}
```

This background Job `FetchAndStoreTranslationJob` uses the Type `<T>` to call the ServiceCollection. The ServiceCollection will return a registered Strategy for that type `<T>` to call methods on.

It does work if I move the Generic Type `<T>` to the Interface - except that my IDE is complaining that the `<T>` 'is not used in the Interface'.

**Comment by odinserj** [comment]
Hi, @dehaaneric! The original issue related to slightly another problem, related to contravariant generic interfaces. Unfortunately, Hangfire does not store generic arguments of a method directly, and it can deserialize a method back only when all the generic arguments are referenced in the parameters directly.

So, for example, the following method signature can't be used in Hangfire, because the generic argument `T` is not referenced in the parameters:

```csharp
public void MyMethod<T>(long arg) {}
```

But the following method signature will work just fine because the `T` argument is referenced in the first parameter:

```csharp
public void MyMethod<T>(T arg) {}
```

So I can recommend you to use the `ITranslatedResource` argument at a type level, in this case Hangfire will be able to record and deconstruct everything. Is it possible to implement this change?

```csharp
public interface IFetchAndStoreTranslationJob<T>
    where T : ITranslatedResource
{
    Task Execute(/* ... */);
}
```
