### ISSUE TITLE
Unique constraint error in Hangfire 

### ISSUE THREAD

**Issue by swetha28** [HangfireIO/Hangfire#2176]
The below mentioned error is thrown when calling `AddOrUpdate` method.
`23505: duplicate key value violates unique constraint "hash_pkey" DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information. 
23505: duplicate key value violates unique constraint "hash_pkey"

DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
Npgsql.PostgresException
   at Npgsql.Internal.NpgsqlConnector.g__ReadMessageLong|215_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in C:\projects\dapper\Dapper\SqlMapper.cs:line 2836
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in C:\projects\dapper\Dapper\SqlMapper.cs:line 570
   at Hangfire.PostgreSql.PostgreSqlWriteOnlyTransaction.<>c__DisplayClass23_1.b__0(NpgsqlConnection con)
   at Hangfire.PostgreSql.PostgreSqlWriteOnlyTransaction.Commit()
   at Hangfire.RecurringJobManager.AddOrUpdate(String recurringJobId, Job job, String cronExpression, RecurringJobOptions options)
   at UpdateReportSchedule(UserToken user, Guid reportConfigGuid, ReadershipReportConfigDto job) in /Services/ScheduleService.cs:line 109
`
Does anyone know why this happens and how to fix this?

**Comment by cihatsolak** [comment]
Hi, this error occurs when AddOrUpdate method is called in IRecurringJobManager interface in hangfire. The Npgsql.PostgresException error can occur when a duplicate key value violation is logged in the variable "hash_pkey", which is a unique constraint. So to sum it up, it could be due to the same duplicate job being added multiple times with the same ID or a problem in the database configuration.
