### ISSUE TITLE
Unexpected end of request content.

### ISSUE THREAD

**Issue by XaoGao** [HangfireIO/Hangfire#2234]
When I open the dashboard, sometimes the logger writes an error:

> Connection ID "0HMRT6GP3DO54", Request ID "0HMRT6GP3DO54:0000006D": The application threw an unhandled exception.

**Enrich:** 

- ConnectionId: 0HMRT6GP3DO54
- EnvironmentName: Prod
- EventId: {Id: 13, Name: 'ApplicationError'}
- RequestId: 0HMRT6GP3DO54:0000006D
- RequestPath: /hangfire/stats
- SourceContext: Microsoft.AspNetCore.Server.Kestrel
- TraceIdentifier: 0HMRT6GP3DO54:0000006D

**Trace:**
`
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at Hangfire.Dashboard.AspNetCoreDashboardRequest.GetFormValuesAsync(String key)
   at Hangfire.Dashboard.JsonStats.Dispatch(DashboardContext context)
   at Hangfire.Dashboard.AspNetCoreDashboardMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
`
**Versions**
Language Version:  C# 11
Target framework: net7.0
Hangfire 1.7.32
Hangfire.Core 1.7.32
Hangfire.AspNetCore 1.7.32

**Comment by nythma** [comment]
同样遇到这个问题了，怎么解决呢

**Comment by bbhxwl** [comment]
me too
