### ISSUE TITLE
[Hangfire.DynamicJobs] [Bug] Adding the AutomaticRetry attribute via DynamicRecurringJobOptions causes a serialization error

### ISSUE THREAD

**Issue by Malgefor** [HangfireIO/Hangfire#2258]
Hi! We are using the Hangfire.DynamicJobs package to allow multiple servers use the same SQL database. The documentation of the package says that Attributes should be added via DynamicRecurringJobOptions. However, when adding the `AutomaticRetry` attribute to the list, we get a serialization error when adding the job on application startup. This error doesn't occur with other standard attributes like DisableConcurrentExecution or setting a specific queue via the Queue-attribute.

```
new AutomaticRetryAttribute
{
    Attempts = 0
}
```

Stracktrace:
```
Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property 'ManifestModule' with type 'System.Reflection.RuntimeModule'. Path 'f[0].DelayInSecondsByAttemptFunc.Method.Module.Assembly'.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty con
tainerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract,
 Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containe
rProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerPr
operty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containe
rProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerPr
operty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containe
rProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerPr
operty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containe
rProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerPr
operty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containe
rProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerPr
operty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty conta
inerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerPr
operty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containe
rProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerPr
operty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Type type, Formatting formatting, JsonSerializerSettings settings)
   at Hangfire.Common.SerializationHelper.Serialize(Object value, Type type, SerializationOption option)
   at Hangfire.Storage.InvocationData.SerializeArguments(MethodInfo methodInfo, IReadOnlyList`1 arguments)
   at Hangfire.Storage.InvocationData.SerializeJob(Job job)
   at Hangfire.RecurringJobEntity.GetChangedFields(Nullable`1& nextExecution)
   at Hangfire.RecurringJobEntity.IsChanged(IReadOnlyDictionary`2& changedFields, Nullable`1& nextExecution)
   at Hangfire.RecurringJobManager.AddOrUpdate(String recurringJobId, Job job, String cronExpression, RecurringJobOptions options)
   at Hangfire.DynamicJobRecurringJobManagerExtensions.AddOrUpdateDynamic(IRecurringJobManager manager, String recurringJobId, Job job, String cronExpression, DynamicRecurringJobOptions options)
   at Hangfire.DynamicJobRecurringJobManagerExtensions.AddOrUpdateDynamic(IRecurringJobManager manager, String recurringJobId, Expression`1 methodCall, String cronExpression, DynamicRecurringJobOptions options)
```

**Comment by TvanderNol** [comment]
Got the same issue! Hopefully 1.8.5 gets released soon!

**Comment by TIMNXL** [comment]
@odinserj Do you have an estimation when 1.8.5 will be released?

**Comment by odinserj** [comment]
Just released, thanks for your patience.

**Comment by Malgefor** [comment]
@odinserj Thanks for releasing! However, I just tested 1.8.5 but the retry attribute still gives a serialization error (a different error though)

![image](https://github.com/HangfireIO/Hangfire/assets/9074275/5eeab5fa-0083-4b93-8b7e-b870faaf745b)
