### ISSUE TITLE
Violation of PRIMARY KEY constraint 'PK_HangFire_Set'.

### ISSUE THREAD

**Issue by micnyk** [HangfireIO/Hangfire#2280]
Hi, I have a few servers that use one database to run recurring jobs. Each server has it's own queue.
![image](https://github.com/HangfireIO/Hangfire/assets/13575087/78046cb8-a415-450d-86ed-29b83b28b65b)

Unfortunately, when I try to trigger any job on any server I'am always getting Violation of Primary Key exception. For example:

`Violation of PRIMARY KEY constraint 'PK_HangFire_Set'. Cannot insert duplicate key in object 'Portal.Set'. The duplicate key value is (recurring-jobs, THRESHOLDS_MONITORING-michal-2). The statement has been terminated.
`
```

System.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'PK_HangFire_Set'. Cannot insert duplicate key in object 'Portal.Set'. The duplicate key value is (recurring-jobs, THRESHOLDS_MONITORING-michal-2).
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at System.Data.SqlClient.SqlCommand.ExecuteBatchRPCCommand()
   at System.Data.SqlClient.SqlCommandSet.ExecuteNonQuery()
   at lambda_method22(Closure, Object)
   at Hangfire.SqlServer.SqlCommandSet.ExecuteNonQuery()
   at Hangfire.SqlServer.SqlCommandBatch.ExecuteNonQuery()
   at Hangfire.SqlServer.SqlServerWriteOnlyTransaction.<Commit>b__17_0(DbConnection connection, DbTransaction transaction)
   at Hangfire.SqlServer.SqlServerStorage.<>c__DisplayClass39_0.<UseTransaction>b__0(DbConnection connection, DbTransaction transaction)
   at Hangfire.SqlServer.SqlServerStorage.<>c__DisplayClass40_0`1.<UseTransaction>b__0(DbConnection connection)
   at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](DbConnection dedicatedConnection, Func`2 func)
   at Hangfire.SqlServer.SqlServerStorage.UseTransaction[T](DbConnection dedicatedConnection, Func`3 func, Nullable`1 isolationLevel)
   at Hangfire.SqlServer.SqlServerStorage.UseTransaction(DbConnection dedicatedConnection, Action`2 action)
   at Hangfire.SqlServer.SqlServerWriteOnlyTransaction.Commit()
   at Hangfire.RecurringJobManager.TriggerJob(String recurringJobId)
   at Hangfire.RecurringJobManager.Trigger(String recurringJobId)
   at Hangfire.Dashboard.DashboardRoutes.<>c.<.cctor>b__6_27(IRecurringJobManager manager, String jobId)
   at Hangfire.Dashboard.RouteCollectionExtensions.<>c__DisplayClass4_0.<AddRecurringBatchCommand>b__0(DashboardContext context, String jobId)
   at Hangfire.Dashboard.BatchCommandDispatcher.Dispatch(DashboardContext context)
   at Hangfire.Dashboard.AspNetCoreDashboardMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
ClientConnectionId:a0420f9d-786c-477a-a2fb-babfb5c49e71
Error Number:2627,State:1,Class:14
```

I'm running Hangfire 1.8.5 and SQL Server Schema version 9.

**Comment by odinserj** [comment]
Please try running the following scripts (but please update table names accordingly). It is included in Schema 8 migration, but looks like not present in your database, and thoughts why could this happen?

```sql
ALTER TABLE [HangFire].[Set] REBUILD WITH (IGNORE_DUP_KEY = ON);
PRINT 'Enabled IGNORE_DUP_KEY option for [HangFire].[Set] table';

ALTER TABLE [HangFire].[Hash] REBUILD WITH (IGNORE_DUP_KEY = ON);
PRINT 'Enabled IGNORE_DUP_KEY option for [HangFire].[Hash] table';
```

**Comment by micnyk** [comment]
Thanks, that worked.

It might be a problem that we have some complex pipelines to manage DBs schema and some migration could be not performed.
