### ISSUE TITLE
Jobs stuck in scheduled after failing to acquire semaphore

### ISSUE THREAD

**Issue by colinblaise** [HangfireIO/Hangfire#2317]
My jobs went to scheduled due to failing to acquire a semaphore, which is expected.

However, after the processing jobs have completed, I would expect the scheduled jobs to start getting processed.

This behavior is reproducible in my product.  Review the following screenshots to witness the behavior.

The maintenance semaphore allows for 250 jobs.

![image](https://github.com/HangfireIO/Hangfire/assets/6540262/6cd6d6ed-1fe8-4e30-b52d-9258555d9c44)

I have 20 processing

![image](https://github.com/HangfireIO/Hangfire/assets/6540262/15fd60f4-cea3-4a03-b58d-02cdd649f9b9)

All of the scheduled jobs are stuck in the scheduled state with the semaphore acquisition error.

![image](https://github.com/HangfireIO/Hangfire/assets/6540262/4b1b461e-c1b2-4e0d-99c9-cff19956ec1e)

Any thoughts on what would cause this behavior?

**Comment by colinblaise** [comment]
I'm working on getting a dump to help diagnose

**Comment by colinblaise** [comment]
I'm wondering if there is an issue with Redis. My redis instance's cpu/memory appear stable and I can connect successfully.

![image](https://github.com/HangfireIO/Hangfire/assets/6540262/77578dde-b598-489c-8927-0fb5eec95515)

**Comment by colinblaise** [comment]
I dug into our application logs and I am seeing this as well.

```c#
[19:49:08 ERR Hangfire.Server.DelayedJobScheduler] 5 state change attempt(s) failed due to an exception, moving job to the FailedState
  {}
System.InvalidOperationException: Transaction was discarded to prevent inconsistency: one or more of active distributed locks were abandoned. Are you hitting Redis memory limits?
   at Hangfire.Pro.Redis.RedisTransaction.Commit()
   at Hangfire.Server.DelayedJobScheduler.EnqueueBackgroundJob(BackgroundProcessContext context, IStorageConnection connection, String jobId)
```

**Comment by colinblaise** [comment]
Another piece of information:

If I click "enqueue now" in the hangfire dashboard, then the job kicks off successfully without issue.

**Comment by odinserj** [comment]
Can you please run the `INFO` command in Redis and post here the results? I'd like to understand your memory-related configuration settings and see how many keys were evicted.

**Comment by colinblaise** [comment]
I will run the command as soon as I am able to reproduce the issue again, thank you.

**Comment by odinserj** [comment]
Thank you for the details. How often do you see the "Transaction was discarded to prevent inconsistency" error in your logs? Also, did you face strangely looking jobs in the Dashboard UI whose type and method couldn't be found? And last but not least, is your Scheduled jobs not working all the time or they are recovered automagically after some period of time?

**Comment by colinblaise** [comment]
When the issue was occurring, I saw that log about once every 5 seconds.  

I did not see anything abnormal in the Dashboard UI where the type and method couldn't be found.

From what I can tell, the only jobs that were stuck belonged to a specific semaphore.  There was no automatic recovery, and the only solution was to manually re-enqueue the jobs from the Dashboard UI. 

The issue has not surfaced again yet so everything is working as expected for now.

**Comment by odinserj** [comment]
Thanks for all the information. I see that everything is normal with memory in Redis, that there were no evictions which theoretically could cause distributed locks keys to be evicted, and max memory policy is set to `noeviction` that disallows evictions at all.

Do you see any other exceptions in the log? Could you share all of them here or send them to support@hangfire.io?

**Comment by colinblaise** [comment]
I found the issue live again.

```
> info
# Server
redis_version:6.0.14
redis_mode:standalone
os:Windows  
arch_bits:64
multiplexing_api:winsock_IOCP
run_id:aaf31577de0cf0c1725badbe1894e0f1350399f8
uptime_in_seconds:580420
uptime_in_days:6
hz:10

# Clients
connected_clients:66
maxclients:256
client_recent_max_input_buffer:8
client_recent_max_output_buffer:0
client_total_writes_outstanding:0
client_total_sent_bytes_outstanding:0
blocked_clients:0
tracking_clients:0
clients_in_timeout_table:0

# Memory
used_memory:59463328
used_memory_human:56.71M
used_memory_rss:57434112
used_memory_rss_human:54.77M
used_memory_peak:64194296
used_memory_peak_human:61.22M
used_memory_peak_perc:92.63%
used_memory_overhead:44058904
used_memory_startup:287376
used_memory_dataset:15404424
used_memory_dataset_perc:26.03%
used_memory_lua:56320
maxmemory:285000000
maxmemory_reservation:30000000
maxfragmentationmemory_reservation:30000000
maxmemory_desired_reservation:30000000
maxfragmentationmemory_desired_reservation:30000000
maxmemory_human:271.80M
maxmemory_policy:noeviction
mem_allocator:jemalloc-4.0.3

# Stats
total_connections_received:6153406
total_commands_processed:174772021
instantaneous_ops_per_sec:233
bytes_received_per_sec:16917
bytes_sent_per_sec:21099
bytes_received_per_sec_human:16.52K
bytes_sent_per_sec_human:20.60K
rejected_connections:0
expired_keys:1086693
evicted_keys:0
keyspace_hits:28789085
keyspace_misses:8074166
pubsub_channels:13
pubsub_patterns:0
total_oom_messages:0

# Replication
role:master

# CPU
used_cpu_sys:2054.718750
used_cpu_user:2803.171875
used_cpu_avg_ms_per_sec:12
server_load:1.24
event_wait:109
event_no_wait:133
event_wait_count:119
event_no_wait_count:105

# Cluster
cluster_enabled:0
cluster_myself_name:

# Keyspace
db0:keys=89,expires=45,avg_ttl=378357697
db1:keys=73,expires=41,avg_ttl=728006364
db2:keys=55,expires=28,avg_ttl=310361091
db3:keys=117,expires=54,avg_ttl=276079124
db4:keys=157,expires=60,avg_ttl=529266541
db5:keys=45,expires=11,avg_ttl=525267847
db6:keys=50,expires=31,avg_ttl=298025991
db7:keys=136,expires=54,avg_ttl=573588579
db8:keys=75,expires=42,avg_ttl=412107464
db9:keys=70,expires=36,avg_ttl=526147186
db10:keys=47,expires=15,avg_ttl=233165684
db11:keys=5926,expires=60,avg_ttl=515367457
db12:keys=86,expires=35,avg_ttl=496958905
db13:keys=60,expires=28,avg_ttl=310154958
db14:keys=98,expires=47,avg_ttl=707934649
db15:keys=58,expires=31,avg_ttl=499694522
```

Here is the redis info.  The db with the issue is db11

**Comment by colinblaise** [comment]
More screenshots

All jobs are stuck in enqueued. Only one job is being processed at a time.

![image](https://github.com/HangfireIO/Hangfire/assets/6540262/c86ad864-a1f4-4478-8d2f-5d36a9a60628)

![image](https://github.com/HangfireIO/Hangfire/assets/6540262/4db62b9d-cc3c-405b-95f8-a3f4ccf3d8da)

![image](https://github.com/HangfireIO/Hangfire/assets/6540262/048dd154-e0f5-4521-a3e1-6ae9334a1301)

**Comment by colinblaise** [comment]
There are no error longs coming from Hangfire at all

**Comment by odinserj** [comment]
Sorry for the delayed response. Please tell me the following things:

1. Is processing restored after restarting the application.
2. Are there any other extension filters applied to your jobs?
3. What Hangfire.Pro.Redis version you are using?
4. Is your time on Redis server synchronized with your application server?

Please use support@hangfire.io for faster response time if you have an active Hangfire subscription. It is backed by help desk and each ticket is tracked, unlike GitHub ones.
