### ISSUE TITLE
Long Running Task - BackgroundJob.Enqueue fails with TaskCancelledException after 12 hours

### ISSUE THREAD

**Issue by OlegoO** [HangfireIO/Hangfire#2321]
The long running job always fails with a TaskCancelledException after 12 hours.
The task was started by calling BackgroundJob.Enqueue.

We use Hangfire 1.7.31 and default Sql Server configuration. 

I tried to find some timeout and could not find. Could you assist what is wrong?

**Error Message:**
System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at VirtoCommerce.SearchModule.Data.BackgroundJobs.IndexingJobs.RunIndexJobAsync(String currentUserName, String notificationId, Boolean suppressInsignificantNotifications, IEnumerable`1 allOptions, Func`3 indexationFunc, PerformContext context, IJobCancellationToken cancellationToken) in /home/runner/work/vc-module-search/vc-module-search/src/VirtoCommerce.SearchModule.Data/BackgroundJobs/IndexingJobs.cs:line 0
   at VirtoCommerce.SearchModule.Data.BackgroundJobs.IndexingJobs.<>c__DisplayClass9_0.
....

**Comment by OlegoO** [comment]
Thank you so much for your help. The update to the latest hangfire resolved the client issue and he ran the task over 12 hours.
