### ISSUE TITLE
Recurring Jobs JobLoadException due to Missing Assembly

### ISSUE THREAD

**Issue by nickschotaliya** [HangfireIO/Hangfire#2483]
![image](https://github.com/user-attachments/assets/bd51648e-4dbe-41f0-809d-26aa2d722abd)

I am encountering the following `Hangfire.Common.JobLoadException` while trying to load a recurring job. The exception details indicate that Hangfire is unable to resolve the assembly `admin.scheduler`. Here is the full error stack trace:

```
Hangfire.Common.JobLoadException: Could not load the job. See inner exception for the details. ---> System.IO.FileNotFoundException: Could not resolve assembly 'admin.scheduler'.
   at System.TypeNameParser.ResolveAssembly(String asmName, Func`2 assemblyResolver, Boolean throwOnError, StackCrawlMark& stackMark)
   at System.TypeNameParser.ConstructType(Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.TypeNameParser.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError)
   at Hangfire.Common.TypeHelper.<>c.<DefaultTypeResolver>b__20_0(String name)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Hangfire.Common.TypeHelper.DefaultTypeResolver(String typeName)
   at Hangfire.Common.TypeHelper.<>c.<IgnoredAssemblyVersionTypeResolver>b__21_0(String value)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Hangfire.Common.TypeHelper.IgnoredAssemblyVersionTypeResolver(String typeName)
   at Hangfire.Storage.InvocationData.<>c.<CachedDeserializeMethod>b__33_0(MethodDeserializerCacheKey key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Hangfire.Storage.InvocationData.CachedDeserializeMethod(Func`2 typeResolver, String typeName, String methodName, String parameterTypes, Type& type, MethodInfo& methodInfo)
   at Hangfire.Storage.InvocationData.DeserializeJob()

   --- End of inner exception stack trace ---
   at Hangfire.Storage.InvocationData.DeserializeJob()
   at Hangfire.RecurringJobExtensions.TriggerRecurringJob(IBackgroundJobFactory factory, JobStorage storage, IStorageConnection connection, IProfiler profiler, RecurringJobEntity recurringJob, DateTime now)
   at Hangfire.Server.RecurringJobScheduler.ScheduleRecurringJob(BackgroundProcessContext context, IStorageConnection connection, String recurringJobId, RecurringJobEntity recurringJob, DateTime now)

```

The exception occurs when Hangfire tries to load the job, and it seems like it cannot find the specified assembly admin.scheduler. This is causing the job to fail to load and trigger as expected.

**Steps to Reproduce:**
1. Create a recurring job in Hangfire referencing `admin.scheduler` assembly.
2. Attempt to run the job.
3. Observe the `JobLoadException` indicating the missing assembly.

**Expected Behavior:**
Hangfire should be able to resolve and load the assembly without issues.

**Actual Behavior:**
Hangfire fails to load the job with the following error: 
`System.IO.FileNotFoundException: Could not resolve assembly 'admin.scheduler'.`

**Additional Information:**

- The assembly admin.scheduler is included in the project references.
- The issue seems to occur only when the job is executed, not during job creation.
- Other assemblies are being resolved correctly without issues.

**Potential Fixes/Questions:**

- Could this issue be related to how Hangfire is resolving the job types and assemblies?
- Is there a way to ensure Hangfire is correctly finding the assembly during job execution?

Any guidance on resolving this issue would be appreciated. Thanks!

@odinserj Can you please check this? We are using hangfire pro with redis i am not sure this is bug or something else? We have one product which has 4 sub modules are using same hangfire database. `admin.scheduler` is console application and the error which is showing on dashboard it is in different websitre with same database connection. We never faced this issue with 1.6.17 or 1.6.30 but after upgrade to 1.8.17 with redis facing this issue. Nothing change other then version and database from sql server to redis.

**Comment by odinserj** [comment]
Is it possible you have another application with a different code base that uses Hangfire with the same database?

**Comment by nickschotaliya** [comment]
we have multiple application which are inter connected and using same database thats right. But code is always same. So we have like multiple servers with dynamic queue like appaname_machine so it will be unique always. Even i have try with `Hangfire.DynamicJobs` But when i try to use `Hangfire.DynamicJobs`  then always failing not sure what is wrong with it. Can you please test once like multiple apps with multiple dynamic queue like appaname_machine with multiple servers? @odinserj

**Comment by odinserj** [comment]
Hangfire doesn't support multiple different code bases with a single database. Recurring job schedule isn't based on queue names, and is the same for all of these applications. So when Application A tries to enqueue a recurring job of Application B, but doesn't have the corresponding assembly, it will fail.

> Hangfire.DynamicJobs But when i try to use Hangfire.DynamicJobs then always failing not sure what is wrong with it.

Hm, what is the exact message/exception you see? Can you send your configuration code with DynamicJobs enabled? Please note that DynamicJobs should be installed and configured in all of your application that use the same database in this case.

**Comment by nickschotaliya** [comment]
Hi sorry for late reply we are currently moving to sql server due to some other reason and also not facing this issue with dynamic jobs so for now closing this issue will reopen again if in future found this issue. Thank you
