### ISSUE TITLE
Hangfire throws ObjectDisposedException during twice Dispose for BackgroundProcessingServer

### ISSUE THREAD

**Issue by MiErnst** [HangfireIO/Hangfire#2488]
The last comment in #2097 mentions that it should be fixed, but I'm still running into this issue when executing integration tests with a custom `WebApplicationFactory`. The service was simply registered using the `WebApplicationBuilder` (`builder.Services.AddHangfireServer()`).

I'm using version 1.8.17.

```
[Test Class Cleanup Failure (Foo.Tests.MyTest)]: System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'Hangfire.Server.BackgroundProcessingServer'.
at Hangfire.Server.BackgroundProcessingServer.ThrowIfDisposed() in C:\projects\hangfire-525\src\Hangfire.Core\Server\BackgroundProcessingServer.cs:line 265
   at Hangfire.Server.BackgroundProcessingServer.SendStop() in C:\projects\hangfire-525\src\Hangfire.Core\Server\BackgroundProcessingServer.cs:line 128
   at Hangfire.BackgroundJobServer.SendStop() in C:\projects\hangfire-525\src\Hangfire.Core\BackgroundJobServer.cs:line 150
   at Hangfire.BackgroundJobServerHostedService.StopAsync(CancellationToken cancellationToken) in C:\projects\hangfire-525\src\Hangfire.NetCore\BackgroundJobServerHostedService.cs:line 128
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.DisposeAsync()
   at Foo.Tests.IntegrationTests.Tests.Base.TestApplicationFactory`1.DisposeAsync() in /azp/_work/1/s/tests/Foo.Tests/IntegrationTests/Tests/Base/TestApplicationFactory.cs:line 29
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.Dispose(Boolean disposing)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.Dispose()
```

**Comment by wrakocy** [comment]
Also just hit up against this in 1.8.17. Stack looks nearly identical to @MiErnst 's:

```
[Test Class Cleanup Failure (XXX.***.XXX.XXX.XXX.XXX)]: System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'Hangfire.Server.BackgroundProcessingServer'.
  Stack Trace:
     at Hangfire.Server.BackgroundProcessingServer.ThrowIfDisposed() in C:\projects\hangfire-525\src\Hangfire.Core\Server\BackgroundProcessingServer.cs:line 265
   at Hangfire.Server.BackgroundProcessingServer.SendStop() in C:\projects\hangfire-525\src\Hangfire.Core\Server\BackgroundProcessingServer.cs:line 128
   at Hangfire.BackgroundJobServer.SendStop() in C:\projects\hangfire-525\src\Hangfire.Core\BackgroundJobServer.cs:line 150
   at Hangfire.BackgroundJobServerHostedService.StopAsync(CancellationToken cancellationToken) in C:\projects\hangfire-525\src\Hangfire.NetCore\BackgroundJobServerHostedService.cs:line 128
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.DisposeAsync()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.Dispose(Boolean disposing)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.Dispose()
```

I'd been using this [workaround](https://github.com/HangfireIO/Hangfire/issues/2097#issuecomment-1612259108) for over a year without incident, so was really surprised to see it rear its head again.

**Comment by odinserj** [comment]
I will add a workaround for this to Hangfire itself, but this bug relates to ASP.NET Core's `WebApplicationFactory` class that implements a test host and tracked here – https://github.com/dotnet/aspnetcore/issues/40271. I think a got the understanding on what happens, will try to write down the behavior in the referenced article and submit a PR in the ASP.NET Core's repository as well, since this is a general problem.

**Comment by odinserj** [comment]
Also, things getting worse because of these multiple `StopAsync` invocations happen from multiple threads, that may result in a race condition, when simple workaround is implemented, as it was in Hangfire.
