### ISSUE TITLE
Transaction not disposed upon Hangfire.States.StateChangeProcess.ApplyState

### ISSUE THREAD

**Issue by Atrejoe** [HangfireIO/Hangfire#252]
Using Hangfire Sql server storage, I get these failures from time to time:

```
The transaction associated with the current connection has completed but has not been disposed. The transaction must be disposed before the connection can be used to execute SQL statements.

System.InvalidOperationException: The transaction associated with the current connection has completed but has not been disposed.  The transaction must be disposed before the connection can be used to execute SQL statements.
   at System.Data.SqlClient.TdsParser.TdsExecuteRPC(_SqlRPC[] rpcArray, Int32 timeout, Boolean inSchema, SqlNotificationRequest notificationRequest, TdsParserStateObject stateObj, Boolean isCommandProc, Boolean sync, TaskCompletionSource`1 completion, Int32 startRpc, Int32 startParam)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in d:\Dev\dapper-dot-net\Dapper NET40\SqlMapper.cs:line 3310
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in d:\Dev\dapper-dot-net\Dapper NET40\SqlMapper.cs:line 1310
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in d:\Dev\dapper-dot-net\Dapper NET40\SqlMapper.cs:line 1185
   at Hangfire.SqlServer.SqlServerWriteOnlyTransaction.<>c__DisplayClass8.<SetJobState>b__7(SqlConnection x)
   at Hangfire.SqlServer.SqlServerWriteOnlyTransaction.Commit()
   at Hangfire.States.StateChangeProcess.ApplyState(ApplyStateContext context, IEnumerable`1 filters)
   at Hangfire.States.StateChangeProcess.ChangeState(StateContext context, IState toState, String oldStateName)
```

My code uses the same database, but on a different connection (and other tables), so I do not think my code interferes with Hangfire.

Anything I can do to determine the cause of this issue?

**Comment by terencebeck** [comment]
Just wonder if you managed to resolve this. We seem to have the same issue. Our Hangfire setup uses an entirely separate database and connection. Have tried using TransactionScope.Suppress and and also removed transaction entirely from our code but no success. With the state change unsuccessful, the job is retried by hangfire over and over indefinitely.
