### ISSUE TITLE
Hangfire nuget installation failure

### ISSUE THREAD

**Issue by vinnytheviking** [HangfireIO/Hangfire#260]
Hi,

I'm trying to load Hangfire into an mvc 6 asp.net 5 website. However when I try and install the Hangfire Nuget package it fails because case sensitive naming conventions.

I get the following
Unable to locate Hangfire.Core >= 1.2.2. Do you mean HangFire.Core?
Unable to locate Hangfire.SqlServer >= 1.2.2. Do you mean HangFire.SqlServer?

When trying to manually install HangFire.SqlServer I get the following

Show Details	Severity	Code	Description	Project	File	Line
	Error		System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Framework.Runtime.LibraryInformation..ctor(LibraryDescription description)
   at Microsoft.Framework.Runtime.LibraryManager.<>c__DisplayClass2.<GetLibraryInfoThunk>b__7(LibraryDescription library)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Microsoft.Framework.Runtime.LibraryManager.EnsureInitialized()
   at Microsoft.Framework.Runtime.LibraryManager.GetLibraryInformation(String name, String aspect)
   at Microsoft.Framework.Runtime.ProjectExportProviderHelper.GetExportsRecursive(ICache cache, ILibraryManager manager, ILibraryExportProvider libraryExportProvider, ILibraryKey target, Boolean dependenciesOnly)
   at Microsoft.Framework.Runtime.LibraryManager.<>c__DisplayClass0.<GetAllExports>b__1(CacheContext ctx)
   at Microsoft.Framework.Runtime.CacheExtensions.<>c__DisplayClass0`1.<Get>b__1(CacheContext ctx)
   at Microsoft.Framework.Runtime.Cache.CreateEntry(Object k, Func`2 acquire)
   at Microsoft.Framework.Runtime.Cache.<>c__DisplayClass3.<AddEntry>b__4()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Framework.Runtime.Cache.Get(Object key, Func`2 factory)
   at Microsoft.Framework.Runtime.CacheExtensions.Get[T](ICache cache, Object key, Func`2 factory)
   at Microsoft.Framework.Runtime.LibraryManager.GetAllExports(String name, String aspect)
   at Microsoft.Framework.Runtime.LibraryManager.GetAllExports(String name)
   at Microsoft.Framework.Runtime.ProjectMetadataProvider.GetProjectMetadata(String name)
   at Microsoft.Framework.DesignTimeHost.ApplicationContext.Initialize(String appPath, String configuration, Boolean triggerBuildOutputs)
   at Microsoft.Framework.DesignTimeHost.ApplicationContext.Calculate()
   at Microsoft.Framework.DesignTimeHost.ApplicationContext.DoProcessLoop()
   at Microsoft.Framework.DesignTimeHost.ApplicationContext.ProcessLoop(Object state)	

I think there's an issue with how HangFire is being packaged.

Do you have any suggestions on how to fix this ?

Thanks

Vinny

**Comment by killnine** [comment]
Yeah, similarly I tried installing on an ASP.NET vNext project and I see the reference in my project but it's not installed correctly (showing a yellow triangle as if the reference is missing). A rebuild doesn't fix it.

Not sure if HF is compatible with these newer versions of ASP.NET

**Comment by odinserj** [comment]
Currently Hangfire is not compatible with .NET Core, but I'm planning to support it ASAP. Especially because Windows Service option is not available on non-MS platforms ;) Keep an eye on the product blog.

**Comment by MarcosRamos** [comment]
Hello Odinserj!
I am trying to Install Hangfire in my Dot Net project and use it along with Enteprise library 6.0.0, but looks to me they are not compatible... Have any idea? Thanks in advance!

**Comment by odinserj** [comment]
Hi @MarcosRamos, please create a new topic on http://discuss.hangfire.io and provide more details: exact error messages, what are you using to install, etc.
