### ISSUE TITLE
Error logs while stepping down a server

### ISSUE THREAD

**Issue by Yalpe** [HangfireIO/Hangfire#338]
We are using Hangfire with Azure and our deployment process goes through a vip swap. During that time there is a bunch of jobs that fail to execute and get pushed to the retry queue. The system sends us an email everytime a log error occurs so it gets anoying fast. We are getting a bunch of errors like:

-Error occured during execution of 'Recurring Job Scheduler' component. Execution will be retried
-Error occured during execution of 'Sever Watchdog' component. Execution will be retried
-Error occured during execution of 'Worker #' component. Execution will be retried
-Error occured during execution of 'SQL Counter Table Aggregator' component. Execution will be retried
-Error occured during execution of 'Schedule Poller' component. Execution will be retried
-Error occured during execution of 'Server Heartbeat' component. Execution will be retried

Those errors occur on the machine that is stepping down (ie: the staging deployment, which gets deleted after the swap).

How can we get arround that? I have a couple of ideas myself but maybe there is already a way. Maybe if we could disable the server while deploying it would be the best because we also ran into a case where we had hangfire servers running with an old version of the binaries and servers running with the updated binaries which caused some mess.

Any help?

PS: I just installed 1.4.1 and it still happens.

**Comment by odinserj** [comment]
We should get the concrete exception messages. Loggers allow to record them as well as their stack traces. Can you configure you logger to do that?

**Comment by Yalpe** [comment]
So it looks like the errors are gone for now. I will report back if we get them again. For the record I can still give you the stack traces:

Error occurred during execution of 'Worker #1' component. Execution will be retried (attempt 1 of 10) in 00:00:01 seconds.



System.Data.SqlClient.SqlException (0x80131904): A transport-level error has occurred when receiving results from the server. (provider: Session Provider, error: 19 - Physical connection is not usable)
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
   at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
   at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
   at System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.<QueryImpl>d__11`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
   at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(CancellationToken cancellationToken)
   at Hangfire.Server.AutomaticRetryServerComponentWrapper.ExecuteWithAutomaticRetry(CancellationToken cancellationToken)

**Comment by odinserj** [comment]
:dancer: :dancer: :dancer: SqlAzure has a lot of transient exceptions, I've lowered LogLevel for first 3 retry attempts.
