### ISSUE TITLE
Error during execution of 'SQL Counter Table Aggregator'

### ISSUE THREAD

**Issue by chaoaretasty** [HangfireIO/Hangfire#362]
Having installed Hangfire my ELMAH logs are getting filled up with the following exception
```
System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near 'MERGE'. You may need to set the compatibility level of the current database to a higher value to enable this feature. See help for the SET COMPATIBILITY_LEVEL option of ALTER DATABASE.
Incorrect syntax near the keyword 'AS'.
Incorrect syntax near the keyword 'WHEN'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader)
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command)
   at Hangfire.SqlServer.CountersAggregator.Execute(CancellationToken cancellationToken)
   at Hangfire.Server.AutomaticRetryServerComponentWrapper.ExecuteWithAutomaticRetry(CancellationToken cancellationToken)
ClientConnectionId:2cca4716-4a3f-47bf-aff6-8cec4030e116
```

Some research on the incorrect syntax for merge has pointed to commonly being the need for a `;` at the end of the statement before the merge. I manually tried executing the statement from 'counteraggregator.cs` and putting a semicolojn after `set nocount on` did let it run fine.

Until this gets included and updated is there any way I can turn this aggregation off to prevent my logs being flooded with retries of this query?

**Comment by chaoaretasty** [comment]
I've got a Gist with my hack around this problem for anyone who wants a temporary fix. https://gist.github.com/chaoaretasty/aecc06b6fecf17276fe8

**Comment by odinserj** [comment]
Hmm, interesting. Would anyone like to add a semicolon before each `merge` statement in Hangfire.SqlServer project and create a PR agains the `master` branch?

**Comment by ilessa** [comment]
@odinserj  damn, beat me to it :)

**Comment by odinserj** [comment]
Ohh, sorry :frowning: Then I'll add some more "jump in" issues soon :)
