### ISSUE TITLE
Hangfire tables are not case-sensitive

### ISSUE THREAD

**Issue by ilessa** [HangfireIO/Hangfire#371]
Hi, we're using a bin collation MSSQL database (necessary to support our customers) and recently received the following error (below) which we have isolated to the CountersAggregator class.

We require the table names to match the ones created (including case) so:

```sql
DELETE TOP (@count) [Hangfire].[Counter] with (readpast)
OUTPUT DELETED.[Key], DELETED.[Value], DELETED.[ExpireAt] INTO @RecordsToAggregate
SET NOCOUNT ON
MERGE [Hangfire].[AggregatedCounter] AS [Target]
```

would become

```sql
DELETE TOP (@count) [HangFire].[Counter] with (readpast)
OUTPUT DELETED.[Key], DELETED.[Value], DELETED.[ExpireAt] INTO @RecordsToAggregate
SET NOCOUNT ON
MERGE [HangFire].[AggregatedCounter] AS [Target]
```

Thanks.

```
Error occurred during execution of 'SQL Counter Table Aggregator' component. Execution will be retried (attempt 10 of 2147483647) in 00:01:28 seconds.
System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Hangfire.Counter'.
Transaction count after EXECUTE indicates a mismatching number of BEGIN and COMMIT statements. Previous count = 0, current count = 1.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader)
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command)
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType)
   at Hangfire.SqlServer.CountersAggregator.Execute(CancellationToken cancellationToken)
   at Hangfire.Server.AutomaticRetryServerComponentWrapper.ExecuteWithAutomaticRetry(CancellationToken cancellationToken)
ClientConnectionId:c952f859-8022-4a46-b934-bd75ae507334
Error Number:208,State:1,Class:16
```

**Comment by odinserj** [comment]
Hi @ilessa, thank you for the reporting. Would you like to create a PR to fix this bug (against the `master` branch to ship the changes in 1.4.3)? Please note that there may be other methods that use the wrong casing, and it is better to check them also.

**Comment by ilessa** [comment]
Hi @odinserj I shall give this a try. Noted about other methods, seen case sensitivity problems before -  I'll change them all.

**Comment by ilessa** [comment]
Oops, meant to just comment, sorry

**Comment by odinserj** [comment]
Don't worry :smile:

**Comment by dradovic** [comment]
This of course is the same issue: http://discuss.hangfire.io/t/invalid-object-name-hangfire-set/960

**Comment by ilessa** [comment]
I run Hangfire on a case sensitive database and fixed it up using the same case sensitive database and can confirm that the issues in that discussion are also fixed - I checked every SQL command :)

**Comment by dradovic** [comment]
Great work!

**Comment by odinserj** [comment]
@ilessa, thank you for the hard work! I've merged the PR, changes will be shipped with 1.4.3.

**Comment by ilessa** [comment]
@odinserj Thanks! I'll keep an eye out for it

**Comment by odinserj** [comment]
Congrats with the first PR on GitHub! :tada:

**Comment by ilessa** [comment]
@odinserj Thanks! :dancers:
