### ISSUE TITLE
Send mail with attachment file

### ISSUE THREAD

**Issue by ngoctuan** [HangfireIO/Hangfire#403]
Hello,

I use Hangfire for send background email, but have error when mail has attachment file.

My bug as bellow, pls help to fix

message: "Newtonsoft.Json.JsonSerializationException: Error getting value from 'ReadTimeout' on 'System.IO.MemoryStream'. ---> System.InvalidOperationException: Timeouts are not supported on this stream.
↵ at System.IO.Stream.get_ReadTimeout()
↵ at GetReadTimeout(Object )
↵ at Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)
↵ --- End of inner exception stack trace ---
↵ at Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)
↵ at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
↵ at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
↵ at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
↵ at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
↵ at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
↵ at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
↵ at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
↵ at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
↵ at Astro.Hangfire.Common.JobHelper.ToJson(Object value) in

**Comment by IanYates** [comment]
I'd say you're serializing the stream for your attachments...  Try passing them as a byte array instead or pass some identifier which will let your Hangfire job retrieve the attachments from more permanent storage.  When JSON.Net is deserializing your stream it's trying to set properties that can't be set such as "ReadTimeout".

**Comment by ngoctuan** [comment]
Many thanks, I will test and feedback soon

**Comment by odinserj** [comment]
Please don't pass big argument values to Hangfire, keep them as simple as possible. Instead, save your attachments to your storage first and pass their identifiers to background job method.

**Comment by darjanbogdan** [comment]
I can confirm that the byte array instead of Stream works, thank you @IanYates!
