### ISSUE TITLE
Failed Can not change the state of a job to 'Processing': target method was not found.

### ISSUE THREAD

**Issue by S3NS4Ti0N** [HangfireIO/Hangfire#430]
I get this error when i try to enqueue a job.

In this lib are multiple jobs. All running fine, except this one.

```
System.TypeLoadException

Could not load type 'Cronlib.Cronjob.Metadata.CollectData' from assembly 'Cronlib.Cronjob, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

System.TypeLoadException: Could not load type 'Cronlib.Cronjob.Metadata.CollectData' from assembly 'Cronlib.Cronjob, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
   at Hangfire.Storage.InvocationData.Deserialize()
```

**Comment by kolic** [comment]
Hello, 

Have you got a solution for this problem?

It happens to me as well, as I schedule the task from another project of the solution, while the server is started from a different project. Is that the same case that you have?

Thank you

**Comment by S3NS4Ti0N** [comment]
Jep that is exacly the same case.

i resolved my problem, with ensuring every project, is using the same version of my library where my jobs are in. The problem was, the dashboard had a different version of my lib, than the actual BackgroundJobServer had.

**Comment by duoanfen** [comment]
me too
`
Failed 

Can not change the state to 'Enqueued': target method was not found.


System.TypeLoadException

Could not load type 'GeduService.Implement.JobService' from assembly 'GeduService'.
System.TypeLoadException: Could not load type 'GeduService.Implement.JobService' from assembly 'GeduService'.
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
   at Hangfire.Storage.InvocationData.Deserialize()

`
