### ISSUE TITLE
Could not load assembly..

### ISSUE THREAD

**Issue by ppumkin** [HangfireIO/Hangfire#439]
I get this error and not sure why.

The object seems to be serialised fine, proposalData, in the DB. But it cant load this method for some reason. The CRM service is a webservice to MSDynamics. The get  function there is also  static.

The class is as follows

```
using Web.UI.CRMDiscoveryService;
using Web.UI.CRMService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Web.UI.Libs.MsDynamicsCrm
{
    public class Proposals
    {

        public static void ConsumerSubmit(new_prop proposalData)
        {
            CrmService service = CrmHelper.GetService();
          
            service.Create(proposalData);
        }
    }
}
````

```
System.TypeLoadException

Could not load type 'Web.UI.Libs.MsDynamicsCrm.Proposals' from assembly 'Web.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

System.TypeLoadException: Could not load type 'Web.UI.Libs.MsDynamicsCrm.Proposals' from assembly 'Web.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
   at Hangfire.Storage.InvocationData.Deserialize()
```

**Comment by ppumkin** [comment]
I do have the live server and my dev server on the same HangFire server. Is it possible that its trying to use the live server to load this assembly and failing?

**Comment by gandarez** [comment]
I've done a PR to resolve this issue
https://github.com/HangfireIO/Hangfire/pull/486

**Comment by michalss** [comment]
same problem here 🚨

**Comment by michalss** [comment]
this is still happening... :(
