### ISSUE TITLE
Error occurred during execution of 'ServerWatchdog' process

### ISSUE THREAD

**Issue by gregorypilar** [HangfireIO/Hangfire#518]
Hi,

I'm getting this error and I dont know why. everything looks good. but whit this error Im not really sure 

```
System.ArgumentOutOfRangeException: The added or subtracted value results in an un-representable DateTime.
Parameter name: value
   at System.DateTime.AddTicks(Int64 value)
   at System.DateTime.Add(TimeSpan value)
   at Hangfire.SqlServer.SqlServerConnection.<>c__DisplayClass2d.<RemoveTimedOutServers>b__2c(SqlConnection connection)
   at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](Func`2 func)
   at Hangfire.SqlServer.SqlServerConnection.RemoveTimedOutServers(TimeSpan timeOut)
   at Hangfire.Server.ServerWatchdog.Execute(BackgroundProcessContext context)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)

```

I just remove this,

```
 //var options = new BackgroundJobServerOptions
           // {              
               // ServerTimeout = TimeSpan.MaxValue
           // };

```

And the exception just gone.  I dont dont if this is a problem or not.

**Comment by odinserj** [comment]
`TimeSpan.MaxValue` is a very dangerous setting anyway. `ServerTimeout` value may affect how fast background job is resumed after a process crash on some storages like Redis. I don't think that any value larger than 24 hours should be accepted.
