### ISSUE TITLE
when the clock is adjusted forward, any time in the period that is skipped is invalid Hangfire.Server.RecurringJobScheduler

### ISSUE THREAD

**Issue by nadeembs** [HangfireIO/Hangfire#530]
Hi

Due to DayLight Saving, i am getting System.ArgumentException.

Exception:
System.ArgumentException: The supplied DateTime represents an invalid time.  For example, when the clock is adjusted forward, any time in the period that is skipped is invalid.
Parameter name: dateTime

CallStack:
2016-03-15 10:31:00,583 [thread] ERROR Hangfire.Server.RecurringJobScheduler - [Hangfire.Logging.LogProviders.Log4NetLogProvider+Log4NetLogger] ERROR Error occurred during execution of 'RecurringJobScheduler' process. Execution will be retried (attempt 39 of 2147483647) in 00:05:00 seconds.
System.ArgumentException: The supplied DateTime represents an invalid time.  For example, when the clock is adjusted forward, any time in the period that is skipped is invalid.
Parameter name: dateTime
   at System.TimeZoneInfo.ConvertTime(DateTime dateTime, TimeZoneInfo sourceTimeZone, TimeZoneInfo destinationTimeZone, TimeZoneInfoOptions flags, CachedData cachedData)
   at System.TimeZoneInfo.ConvertTimeToUtc(DateTime dateTime, TimeZoneInfo sourceTimeZone)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Hangfire.Server.ScheduleInstant.GetNextInstants(Nullable`1 lastInstant)
   at Hangfire.Server.RecurringJobScheduler.TryScheduleJob(JobStorage storage, IStorageConnection connection, String recurringJobId, IReadOnlyDictionary`2 recurringJob)
   at Hangfire.Server.RecurringJobScheduler.Execute(BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)

**Comment by IanYates** [comment]
See #529 - probably related

**Comment by odinserj** [comment]
Yes, this duplicates #529. I've just fixed it, will release a new version today.
