### ISSUE TITLE
Hangfire failing after moving clock forward for daylight saving time

### ISSUE THREAD

**Issue by jlost** [HangfireIO/Hangfire#537]
https://discuss.hangfire.io/t/hangfire-failing-after-moving-clock-forward-for-the-daylight-saving-time/1866/1

> Firstly, thanks for creating hangfire..
Secondly, we started have issues today as we moved to daylight saving time (Central Standard time(CST) to Central Daylight time(CDT)) and none of the jobs are getting triggered after that. Please see the exception throw below. Could you please let me know how to fix this

```
2016-03-13 08:33:00.743 -05:00 [Error] Error occurred during execution of 'RecurringJobScheduler' process. Execution will be retried (attempt 12 of 2147483647) in 00:02:16 seconds.
System.ArgumentException: The supplied DateTime represents an invalid time. For example, when the clock is adjusted forward, any time in the period that is skipped is invalid.
Parameter name: dateTime
at System.TimeZoneInfo.ConvertTime(DateTime dateTime, TimeZoneInfo sourceTimeZone, TimeZoneInfo destinationTimeZone, TimeZoneInfoOptions flags, CachedData cachedData)
at Hangfire.Server.ScheduleInstant.b__0(DateTime x)
at System.Linq.Enumerable.WhereSelectEnumerableIterator2.MoveNext()
at System.Collections.Generic.List1..ctor(IEnumerable1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source)
at Hangfire.Server.ScheduleInstant.GetNextInstants(Nullable1 lastInstant)
at Hangfire.Server.RecurringJobScheduler.TryScheduleJob(JobStorage storage, IStorageConnection connection, String recurringJobId, IReadOnlyDictionary2 recurringJob)
at Hangfire.Server.RecurringJobScheduler.Execute(BackgroundProcessContext context)
at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)

```

Are there any plans to fix this bug?
Could this have been avoided by using Cron.Hourly rather than explicitly specifying a cron expression?
What can we do to prevent this from happening in the future?

**Comment by odinserj** [comment]
Duplicates #529. I've just fixed it, will release a new version today.
