### ISSUE TITLE
The operation is not valid for the state of the transaction

### ISSUE THREAD

**Issue by krzysztof-at-mp** [HangfireIO/Hangfire#565]
I found Hangfire not processing any enqueued job for few hours. The windows service worked for a while and then stopped. All further executions ended with this exception

```
Error occurred during execution of 'Worker #b8f96194' process. Execution will be retried (attempt 281 of 2147483647) in 00:05:00 seconds.
Exception logged in:
 at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
 at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
 at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
 at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
 at System.Threading.ThreadHelper.ThreadStart()
Raised exception:
The operation is not valid for the state of the transaction.
Exception of type System.Transactions.TransactionException
 at System.Transactions.TransactionState.EnlistPromotableSinglePhase(InternalTransaction tx, IPromotableSinglePhaseNotification promotableSinglePhaseNotification, Transaction atomicTransaction, Guid promoterType)
 at System.Transactions.Transaction.EnlistPromotableSinglePhase(IPromotableSinglePhaseNotification promotableSinglePhaseNotification, Guid promoterType)
 at System.Transactions.Transaction.EnlistPromotableSinglePhase(IPromotableSinglePhaseNotification promotableSinglePhaseNotification)
 at System.Data.SqlClient.SqlInternalConnection.EnlistNonNull(Transaction tx)
 at System.Data.SqlClient.SqlInternalConnection.Enlist(Transaction tx)
 at System.Data.SqlClient.SqlInternalConnectionTds.Activate(Transaction transaction)
 at System.Data.ProviderBase.DbConnectionInternal.ActivateConnection(Transaction transaction)
 at System.Data.ProviderBase.DbConnectionPool.PrepareConnection(DbConnection owningObject, DbConnectionInternal obj, Transaction transaction)
 at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
 at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
 at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
 at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
 at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
 at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
 at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
 at System.Data.SqlClient.SqlConnection.Open()
 at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
 at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
 at Hangfire.SqlServer.SqlServerConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
 at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
 at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
 at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
Inner exception:
Transaction Timeout
Exception of type System.TimeoutException
```
Is there anything I could do wrong? Any ideas where to search to find issue source?

**Comment by odinserj** [comment]
This is strange, since the connection isn't created in a `TransactionScope` block. Don't understand why the stack trace contains the `EnlishNonNull` method call, because it claims that `Transaction.Current` property isn't null. You can try to use the `enlist=false` option in the connection string, but we should know the reason before doing this.

I've found [this answer](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/075e6a05-c761-49a5-996d-5dff875139ab/bizarre-sql-connectionopen-exception?forum=sqldataaccess#a223fc8c-4859-46c8-9821-74cd47af3816) on MSDN forums with the same description – they aren't using transactions at all. He started an investigation, but didn't come back :frowning:

**Comment by odinserj** [comment]
@krzysztof-at-mp, any thoughts on this? Have you tried to google this exception (without relation to Hangfire)?

**Comment by krzysztof-at-mp** [comment]
I think I might found the source and it seems it's connected to not disposed TransactionScope. I need some time to prove it (still running tests).

**Comment by odinserj** [comment]
@krzysztof-at-mp, was the problem caused by an application code?

**Comment by krzysztof-at-mp** [comment]
Yes, I found some paths in our code was not disposing the transaction. I was unable to reproduce after the code was fixed.
