### ISSUE TITLE
An invalid application lock time-out was passed to xp_userlock.

### ISSUE THREAD

**Issue by rdlaitila** [HangfireIO/Hangfire#647]
Hello, 

When attempting to launch a Reoccurring Job async, I receive the following error:

```csharp

System.Data.SqlClient.SqlException

An invalid application lock time-out was passed to xp_userlock.

System.Data.SqlClient.SqlException (0x80131904): An invalid application lock time-out was passed to xp_userlock.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader)
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command)
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType)
   at Hangfire.SqlServer.SqlServerDistributedLock.Acquire(IDbConnection connection, String resource, TimeSpan timeout)
   at Hangfire.SqlServer.SqlServerDistributedLock..ctor(SqlServerStorage storage, String resource, TimeSpan timeout)
   at Hangfire.SqlServer.SqlServerConnection.AcquireDistributedLock(String resource, TimeSpan timeout)
   at Hangfire.DisableConcurrentExecutionAttribute.OnPerforming(PerformingContext filterContext)
   at Hangfire.Server.BackgroundJobPerformer.InvokePerformFilter(IServerFilter filter, PerformingContext preContext, Func`1 continuation)
```

Here is the Job Info from dashboard:

```csharp
var exampleJob = Activate<ExampleJob>();
await exampleJob.ExecuteAsync();
```

And the class impl:

```csharp
public class ExampleJob
{
    public async Task ExecuteAsync()
    {
        // does not matter if I have an await on a resource or even a blank method with no body, same behavior
    }

}
```
And here is how it is scheduled:

```csharp
RecurringJob.AddOrUpdate<ExampleJob>("ExampleJob", j => j.ExecuteAsync(), Cron.Minutely);
```

Any help would be greatly appreciated!

**Comment by rdlaitila** [comment]
Using Hangfire 1.6.2

**Comment by odinserj** [comment]
Something is wrong with the value for the `DisableConcurrentExecution`'s `timeoutInSeconds` parameter. Try to specify a lower value, `timeoutInSeconds * 1000` should be less than `Int32.MaxValue`, I've created #657 to handle this.
