### ISSUE TITLE
Cannot get powershell to work within Hangfire-job

### ISSUE THREAD

**Issue by itssimple** [HangfireIO/Hangfire#726]
I'm using powershell to connect to remote servers and check information.
But when I'm using the code inside a Hangfire-job, I always get "RPC Server Unavailable".

The code works locally on the servers I run the commands from. (If I run the command outside of Hangfire)

Example usage:

```csharp
public override void GetServerInfo(PerformContext context)
{
	using (PowerShell ps = PowerShell.Create())
	{
		var file = @"check-serverInfo.ps1";
		ps.AddScript(ReadEmbeddedResource(file));

		ps.AddParameter("computerName", HostName);
		ps.AddParameter("userName", UserName.Unprotect(ServerName));
		ps.AddParameter("passWord", PassWord.Unprotect(ServerName));
		var output = ps.Invoke<WindowsServerStatus>();
		var computerStatus = output.FirstOrDefault();
		if (computerStatus != null)
		{
			RestartRequired = computerStatus.RebootPending;
			OS = GetOSVersion(computerStatus.OSVersion);
			x64 = computerStatus.x64;
		}
	}
}
```

And the powershell script I'm running is:

```powershell
param([string] $computerName = $env:COMPUTERNAME, [string] $userName, [string] $passWord)
$isUp = Test-Connection $computerName -Quiet -Count 1 -ErrorAction Stop
$isLocal = ($computerName.ToLower().Contains($env:COMPUTERNAME.ToLower()))

$pass = $passWord | ConvertTo-SecureString -AsPlainText -Force
$cred = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $userName, $pass

$updates = Invoke-Command -ComputerName $computerName { 
    return New-Object -TypeName PSObject -Property @{
        x64 = if ([System.IntPtr]::Size -eq 4) { $false } else { $true }
    } | Select-Object
} -Credential $cred

## Setting pending values to false to cut down on the number of else statements 
$CompPendRen,$PendFileRename,$Pending,$SCCM = $false,$false,$false,$false 
       
## Setting CBSRebootPend to null since not all versions of Windows has this value 
$CBSRebootPend = $null 
             
## Querying WMI for build version 
if($isLocal) {
    $WMI_OS = Get-WmiObject -Class Win32_OperatingSystem -ComputerName $computerName -ErrorAction Stop
} else {
    $WMI_OS = Get-WmiObject -Class Win32_OperatingSystem -ComputerName $computerName -ErrorAction Stop -Credential $cred
}
 
## Making registry connection to the local/remote computer 
$HKLM = [UInt32] "0x80000002" 

if($isLocal) {
    $WMI_Reg = Get-WmiObject -List "StdRegProv" -Namespace root\default -ComputerName $computerName
} else {
    $WMI_Reg = Get-WmiObject -List "StdRegProv" -Namespace root\default -ComputerName $computerName -Credential $cred
}
             
## If Vista/2008 & Above query the CBS Reg Key 
If ([Int32]$WMI_OS.BuildNumber -ge 6001) { 
    $RegSubKeysCBS = $WMI_Reg.EnumKey($HKLM,"SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\")
    $CBSRebootPend = $RegSubKeysCBS.sNames -contains "RebootPending"     
} 
               
## Query WUAU from the registry 
$RegWUAURebootReq = $WMI_Reg.EnumKey($HKLM,"SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\") 
$WUAURebootReq = $RegWUAURebootReq.sNames -contains "RebootRequired" 
  
## Determine SCCM 2012 Client Reboot Pending Status 
## To avoid nested 'if' statements and unneeded WMI calls to determine if the CCM_ClientUtilities class exist, setting EA = 0 
$CCMClientSDK = $null 
$CCMSplat = @{ 
    NameSpace='ROOT\ccm\ClientSDK' 
    Class='CCM_ClientUtilities' 
    Name='DetermineIfRebootPending' 
    ComputerName=$computerName
    ErrorAction='Stop' 
} 
## Try CCMClientSDK 
Try { 
    if($isLocal) {
        $CCMClientSDK = Invoke-WmiMethod @CCMSplat
    } else {
        $CCMClientSDK = Invoke-WmiMethod @CCMSplat -Credential $cred
    }
} Catch [System.UnauthorizedAccessException] { 
    $CcmStatus = Get-Service -Name CcmExec -ComputerName $computerName -ErrorAction SilentlyContinue
    If ($CcmStatus.Status -ne 'Running') { 
        Write-Warning "$Computer`: Error - CcmExec service is not running." 
        $CCMClientSDK = $null 
    } 
} Catch { 
    $CCMClientSDK = $null 
} 
 
If ($CCMClientSDK) { 
    If ($CCMClientSDK.ReturnValue -ne 0) { 
        Write-Warning "Error: DetermineIfRebootPending returned error code $($CCMClientSDK.ReturnValue)"     
    } 
    If ($CCMClientSDK.IsHardRebootPending -or $CCMClientSDK.RebootPending) { 
        $SCCM = $true 
    } 
} 
       
Else { 
    $SCCM = $null 
} 
 
## Creating Custom PSObject and Select-Object Splat 
$SelectSplat = @{ 
    Property=( 
    'Computer', 
    'CBServicing', 
    'WindowsUpdate', 
    'CCMClientSDK', 
    'PendComputerRename', 
    'RebootPending' 
)} 
$pending = New-Object -TypeName PSObject -Property @{ 
    Computer=$WMI_OS.CSName 
    CBServicing=$CBSRebootPend 
    WindowsUpdate=$WUAURebootReq 
    CCMClientSDK=$SCCM 
    PendComputerRename=$CompPendRen 
    RebootPending=($CompPendRen -or $CBSRebootPend -or $WUAURebootReq -or $SCCM) 
} | Select-Object @SelectSplat 

return New-Object -TypeName PSObject -Property @{
    Host = $computerName
    Computer = $WMI_OS.CSName
    OSVersion = $WMI_OS.Version
    RebootPending = ($pending.CBSRebootPend -or $pending.WUAURebootReq -or $pending.SCCM)
    TotalUpdates = $updates.TotalUpdates
    HasUpdates = $updates.HasUpdates
    ImportantUpdates = $updates.TotalImportant
    CriticalUpdates = $updates.TotalCritical
    x64 = $updates.x64
} | Select-Object
```

And the complete exception text in Hangfire is:

```
System.Management.Automation.ActionPreferenceStopException

The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)

System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke[T](IEnumerable input, IList`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke[T]()
   at PatchBoard.WindowsServer.CheckUpdates(PerformContext context) in ..\WindowsServer.cs:line 29
   at PatchBoard.DataHandler.CheckServer(WLServer ws, PerformContext context) in ..\DataHandler.cs:line 119
   at PatchBoard.DataHandler.CheckWindowsServer(WindowsServer ws, PerformContext context) in ..\DataHandler.cs:line 174
```

**Comment by odinserj** [comment]
Hangfire simply runs your code in a background thread. It doesn't modify the execution logic of your PowerShell script – try to run it outside of Hangfire in your application, and you'll get the same results. Please consider getting the exact error message by examining the `PowerShell.Streams` property or something like that.

**Comment by ericmck2000** [comment]
FYI, a bit old, but, all of the powershell you are calling can be migrated to native c# quite easily.

I do a bunch of .net work with SCCM and WMI.
