### ISSUE TITLE
Hangfire 0 active servers after SQL Server outage, won't start servers again

### ISSUE THREAD

**Issue by tompazourek** [HangfireIO/Hangfire#796]
Yesterday, my SQL Server was offline for about 40 minutes.

I have 6 instances of Hangfire 1.6.4 running on various websites. When my SQL Server was down, Hangfire was throwing a lot of exceptions (which is expected), but after it came back, 5 out of 6 of those instances reported 0 active servers. I could go to the dashboard and go through everything, but even when the SQL Server was up again, the Hangfire servers wouldn't start.

Also, the exceptions from Hangfire were no longer being thrown. There were just no active servers.

I waited for like 20 minutes, and the Hangfire servers still didn't start, so I had to manually restart each of those 5 websites.

The exceptions thrown by Hangfire were about the SQL Server connectivity:

```
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
   at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](Func`2 func)
   at Hangfire.Server.ServerHeartbeat.Execute(BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
```

```
System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - An existing connection was forcibly closed by the remote host.) ---> System.ComponentModel.Win32Exception (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
   at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:f376a481-37e6-4c57-9ec8-9e201311846a
Error Number:10054,State:0,Class:20
```

Here's some screenshots from the log:
![snip4](https://cloud.githubusercontent.com/assets/370699/22098472/c62503ec-de26-11e6-8e38-0895f03a48e8.PNG)
![snip3](https://cloud.githubusercontent.com/assets/370699/22098475/c9ce8c84-de26-11e6-8717-8272d6452e93.PNG)
![snip2](https://cloud.githubusercontent.com/assets/370699/22098481/cdbed4fc-de26-11e6-872b-145c1763da63.PNG)
![snip1](https://cloud.githubusercontent.com/assets/370699/22098485/d10c8514-de26-11e6-81c2-c37a450b3177.PNG)

(I received about 1400 of those exceptions over the course of 40 minutes from each website)

**Comment by odinserj** [comment]
That's a lot of messages, and they are really annoying, understand. I found out a way how to limit their number in such cases, but this feature will be released only with Hangfire 1.7.0.

**Comment by odinserj** [comment]
Regarding zombie-servers, I think Hangfire Server should restart itself, if it is down more than `BackgroundJobServerOptions.ServerTimeout`, because other servers with active connection could remove it by a timeout.

**Comment by tompazourek** [comment]
Thanks for a quick reply. The number of logged exceptions isn't really a concern of mine, I'm alright with this failing.

I'm more worried about the active servers being 0. I haven't changed the `BackgroundJobServerOptions.ServerTimeout`, so it's configured to the default 5 minutes. But even after my database server was already up for 20 minutes, I still had 0 active servers.

I am not sure what processes in Hangfire are meant to ensure that there's always an active server (`ServerWatchdog` maybe?), but I think some part must have crashed there or is not behaving as it should. I stopped receiving any exceptions and there was still 0 active servers for at least 20 minutes.

**Comment by charla-n** [comment]
We have from time to time the same problem. 

We noticed the following:
- A problem with the connection between SQL Server and Hangfire occurs
- Hangfire shows 0 server(s) on the dashboard
- The connection is re-established
- Hangfire still shows 0 server(s) on the dashboard

A restart of our Hangfire console application fixes the problem. We also noticed something odd: when the connection is re-established with SQL Server, Hangfire is able to process jobs even if Hangfire Dashboard shows 0 server(s).

Hangfire: 1.5.9

**Comment by bjowes** [comment]
We have seen the same issue. In our case, we have a single hangfire instance. After the SQL Server is unavailable for a few minutes, it came back online. The dashboard then showed 0 servers. Our hangfire process resumed its jobs after about a minute, but the dashboard still showed 0 servers. All the jobs in the queue completed successfully. After about 5 minutes since the SQL Server came back online, the dashboard showed our server again. 
So there seems to be an intermediate state when the server is active but not showing up properly.

**Comment by odinserj** [comment]
Starting with 1.7.0 those servers will be restarted automatically with the new identifier. The only thing is that storage should throw the `BackgroundServerGoneException` when heartbeat was unsuccessful. Also there will be much fewer exceptions logged.

**Comment by colinwphillips** [comment]
@odinserj 	can there be an opportunity for an event to fire when the database is inaccessible? I'd envision this as part of the heartbeat, so that the developer can determine implementation, i.e. after 5 missed heartbeats perform some action? 
As it stands, there is no way to hook into the event unless you add an `IBackgroundProcess` to `additionalProcesses` and poll via a `checkInterval`.

**Comment by odinserj** [comment]
That's a tricky feature, because in some circumstances different workers even in the same process may report different results on whether database is accessible or not. In 1.7.0 you can hook the logging subsystem to react on ["{0} is in the Failed state now"](https://github.com/HangfireIO/Hangfire/blob/2ffdac9860fd3c62f92aa1f686df9b4b9577a2cb/src/Hangfire.Core/Processing/BackgroundExecution.cs#L440) and ["{0} recovered from the Failed state"](https://github.com/HangfireIO/Hangfire/blob/2ffdac9860fd3c62f92aa1f686df9b4b9577a2cb/src/Hangfire.Core/Processing/BackgroundExecution.cs#L382;L392) messages for individual processes. And there's also [a log message](https://github.com/HangfireIO/Hangfire/blob/2ffdac9860fd3c62f92aa1f686df9b4b9577a2cb/src/Hangfire.Core/Server/BackgroundServerProcess.cs#L72) when server is going for restart due to several missed heartbeats.
