### ISSUE TITLE
SQLException "Timeout" when calling Hangfire.RecurringJob.AddOrUpdate(...)

### ISSUE THREAD

**Issue by gentledepp** [HangfireIO/Hangfire#841]
Hi!
Since the last update to 
    "Hangfire.Console": "1.2.0",
    "Hangfire.Core": "1.6.8",
    "Hangfire.Dashboard.Authorization": "2.1.0",
    "Hangfire.SqlServer": "1.6.8"

We get a "SQLException: Timeout" twice a week when our IIS website wakes up again and (during its startup process) calls
`Hangfire.RecurringJob.AddOrUpdate(...)`

the full exception stacktrace is
```

[Win32Exception (0x80004005): The wait operation timed out]

[SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.  This failure occurred while attempting to connect to the routing destination. The duration spent while attempting to connect to the original server was - [Pre-Login] initialization=4; handshake=15; [Login] initialization=0; authentication=0; [Post-Login] complete=0;  ]
   System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) +388
   System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) +717
   System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) +4515
   System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString) +6558377
   System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds) +6561143
   System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite) +586
   System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite) +742
   System.Data.SqlClient.SqlCommand.ExecuteNonQuery() +287
   Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) +1348
   Hangfire.SqlServer.SqlServerWriteOnlyTransaction.<Commit>b__5_0(DbConnection connection, DbTransaction transaction) +468
   Hangfire.SqlServer.<>c__DisplayClass19_0.<UseTransaction>b__0(DbConnection connection, DbTransaction transaction) +15
   Hangfire.SqlServer.SqlServerStorage.UseConnection(Func`2 func) +80
   Hangfire.SqlServer.SqlServerStorage.UseTransaction(Func`3 func, Nullable`1 isolationLevel) +350
   Hangfire.SqlServer.SqlServerWriteOnlyTransaction.Commit() +197
   Hangfire.RecurringJobManager.AddOrUpdate(String recurringJobId, Job job, String cronExpression, RecurringJobOptions options) +596
   Hangfire.RecurringJob.AddOrUpdate(Expression`1 methodCall, String cronExpression, TimeZoneInfo timeZone, String queue) +275
   Abp.Zero.JobScheduling.<>c__DisplayClass14_0`1.<AddOrUpdate>b__0() +92
   Abp.Zero.JobScheduling.HangFireBackgroundJobScheduler.WrapException(Action action) +70
   MyApp.Reporting.Jobs.CleanTempFolderJobRegistrar.Run() +341
   MyApp.Web.Startup.Configuration(IAppBuilder app, HttpConfiguration config, IIocManager iocManager, Boolean skipConfigurators) +605
   MyApp.Web.Startup.Configuration(IAppBuilder app) +73
```

I remember that I was told once it would be an issue with the connection pool size, however this is our connection string:

`<add name="Default" connectionString="Server=tcp:MYDATABASE.server.net,1433;Database=MYDATABASE;User ID=MYDATABASE_admin@MYDATABASE.server;Password=********;Encrypt=True;TrustServerCertificate=False;Connection Timeout=500;Max Pool Size=200;" providerName="System.Data.SqlClient" />`

And calling sp_who on this database shows that output:
```
   spid	ecid	status	loginame	hostname	blk	dbname	cmd	request_id
85	0	sleeping                      	MYDATABASE_admin	MYDATABASE            	0    	MYDATABASE	AWAITING COMMAND	0
100	0	sleeping                      	MYDATABASE_admin	MYDATABASE            	0    	MYDATABASE	AWAITING COMMAND	0
104	0	sleeping                      	MYDATABASE_admin	MYDATABASE            	0    	MYDATABASE	AWAITING COMMAND	0
105	0	sleeping                      	MYDATABASE_admin	MYDATABASE            	0    	MYDATABASE	AWAITING COMMAND	0
106	0	sleeping                      	MYDATABASE_admin	MYDATABASE            	0    	MYDATABASE	AWAITING COMMAND	0
107	0	sleeping                      	MYDATABASE_admin	MYDATABASE            	0    	MYDATABASE	AWAITING COMMAND	0
108	0	sleeping                      	MYDATABASE_admin	MYDATABASE            	0    	MYDATABASE	AWAITING COMMAND	0
109	0	sleeping                      	MYDATABASE_admin	MYDATABASE            	0    	MYDATABASE	AWAITING COMMAND	0
110	0	sleeping                      	MYDATABASE_admin	MYDATABASE            	0    	MYDATABASE	AWAITING COMMAND	0
111	0	sleeping                      	MYDATABASE_admin	MYDATABASE            	0    	MYDATABASE	AWAITING COMMAND	0
112	0	sleeping                      	MYDATABASE_admin	MYDATABASE            	0    	MYDATABASE	AWAITING COMMAND	0
113	0	sleeping                      	MYDATABASE_admin	MYDATABASE            	0    	MYDATABASE	AWAITING COMMAND	0
114	0	sleeping                      	MYDATABASE_admin	MYDATABASE            	0    	MYDATABASE	AWAITING COMMAND	0
115	0	sleeping                      	MYDATABASE_admin	MYDATABASE            	0    	MYDATABASE	AWAITING COMMAND	0
116	0	sleeping                      	MYDATABASE_admin	MYDATABASE            	0    	MYDATABASE	AWAITING COMMAND	0
117	0	sleeping                      	MYDATABASE_admin	MYDATABASE            	0    	MYDATABASE	AWAITING COMMAND	0
118	0	sleeping                      	MYDATABASE_admin	MYDATABASE            	0    	MYDATABASE	AWAITING COMMAND	0
120	0	sleeping                      	MYDATABASE_admin	MYDATABASE            	0    	MYDATABASE	AWAITING COMMAND	0
122	0	suspended                     	MYDATABASE_admin	MYDATABASE            	112  	MYDATABASE	EXECUTE         	0
123	0	sleeping                      	MYDATABASE_admin	MYDATABASE            	0    	MYDATABASE	AWAITING COMMAND	0
124	0	sleeping                      	MYDATABASE_admin	MYDATABASE            	0    	MYDATABASE	AWAITING COMMAND	0
125	0	runnable                      	MYDATABASE_admin	LAPTOP-3M6KT9XX         0    	MYDATABASE	SELECT          	0
126	0	sleeping                      	MYDATABASE_admin	MYDATABASE            	0    	MYDATABASE	AWAITING COMMAND	0
127	0	sleeping                      	MYDATABASE_admin	MYDATABASE            	0    	MYDATABASE	AWAITING COMMAND	0
128	0	sleeping                      	MYDATABASE_admin	MYDATABASE            	0    	MYDATABASE	AWAITING COMMAND	0
129	0	sleeping                      	MYDATABASE_admin	MYDATABASE            	0    	MYDATABASE	AWAITING COMMAND	0
130	0	sleeping                      	MYDATABASE_admin	MYDATABASE            	0    	MYDATABASE	AWAITING COMMAND	0
132	0	sleeping                      	MYDATABASE_admin	MYDATABASE            	0    	MYDATABASE	AWAITING COMMAND	0
```

So there are only like 20 connections and most of them are sleeping. 
Any idea what this could be?

**Comment by jhallam3** [comment]
I get the same with 
hangfire 1.6.12
handfire.console 1.3.1
hangfire.postgressql.netcore 1.4.3

**Comment by ericmck2000** [comment]
Can also confirm this issue. Its happening a few times every day for me.

But, i have 6 nodes running.

**Comment by RichardSilveira** [comment]
any news on it..?

**Comment by gentledepp** [comment]
Unfortunately not.
We have removed the "Hangfire.RecurringJob.AddOrUpdate(...)" part by adding a web.config setting, which allows us to skip it in case the jobs are already registered

**Comment by tjackadams** [comment]
I am also experiencing the same issue on my local dev machine.

Hangfire.AspNetCore 1.6.19
Hangfire.SqlServer 1.6.19
Hangfire.Console 1.3.10

Here is the stack trace 

> System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (258): The wait operation timed out
>    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
>    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
>    at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
>    at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
>    at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
>    at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
>    at Hangfire.SqlServer.SqlCommandBatch.ExecuteNonQuery()
>    at Hangfire.SqlServer.SqlServerWriteOnlyTransaction.<Commit>b__7_0(DbConnection connection, DbTransaction transaction)
>    at Hangfire.SqlServer.SqlServerStorage.<>c__DisplayClass26_0.<UseTransaction>b__0(DbConnection connection, DbTransaction transaction)
>    at Hangfire.SqlServer.SqlServerStorage.<>c__DisplayClass27_0`1.<UseTransaction>b__0(DbConnection connection)
>    at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](DbConnection dedicatedConnection, Func`2 func)
>    at Hangfire.SqlServer.SqlServerStorage.UseTransaction[T](DbConnection dedicatedConnection, Func`3 func, Nullable`1 isolationLevel)
>    at Hangfire.SqlServer.SqlServerStorage.UseTransaction(DbConnection dedicatedConnection, Action`2 action)
>    at Hangfire.SqlServer.SqlServerWriteOnlyTransaction.Commit()
>    at Hangfire.RecurringJobManager.AddOrUpdate(String recurringJobId, Job job, String cronExpression, RecurringJobOptions options)
>    at Portal.BackgroundJobs.RecurringJobHelper.AddOrUpdate() in C:\Users\tom.adams\Source\Repos\portal\src\Portal.Core\BackgroundJobs\RecurringJobHelper.cs:line 48
>    at Portal.BackgroundJobs.RecurringJobHelper.Setup() in C:\Users\tom.adams\Source\Repos\portal\src\Portal.Core\BackgroundJobs\RecurringJobHelper.cs:line 757
>    at Portal.Web.Startup.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in C:\Users\tom.adams\Source\Repos\portal\src\Portal.Web.Mvc\Startup\Startup.cs:line 145
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
> ClientConnectionId:8c7811a7-3f51-486f-9122-1aca6ae3e8a0
> Error Number:-2,State:0,Class:11


any ideas how i can troubleshoot this further?

**Comment by gentledepp** [comment]
Honestly, we are living with this bug since one year using the following workaround:
* we have a setting that tells our webapp whether to register recurring jobs at startup ('cause that is what causes the deadlock)
* when the deadlock happens, we restart the webapp and configure it to not register those jobs
then everything works fine
* one day afterwards, we try to reset that setting to "register all recurring jobs" again and see if it works. Most of the time it does.

Honestly, this is far from an ideal solution, but we do neither have the time nor the knowledge to dig into this further.

**Comment by ericmck2000** [comment]
We have implemented a similar solution. Another piece of software attempts
to en-queue a "Hello world" job every 2 minutes, When it times out, it
restarts the application.
