### ISSUE TITLE
Cannot delete a recurring job through Dashboard

### ISSUE THREAD

**Issue by majoy** [HangfireIO/Hangfire#862]
Hello,

When I try to use the Dashboard to delete a recurring job, the job does not get removed. 

Here are the steps I follow to reproduce the issue:

1) Go to the hangfire dashboard and click the Recurring Jobs menu link
2) Select a recurring job to be deleted and click the Delete icon
3) Click yes on the Alert confirmation message that shows up on the page

After executing step 3 I see the "Delete icon" gets disabled and the text is automatically changed to "Deleting..." but nothing else happens afterwards even if I wait a minute or two after I clicked the "Delete" icon. 

I tried refreshing the page after this and the job is still shown. I'm using Hangfire.Core v.1.6.8.0

I also noticed that the documentation page that deals with recurring tasks mentions that a recurring job can be removed by calling the RemoveIfExists function which I did try. This did work successfully. However, the existing documentation doesn't confirm that we can Delete a recurring job through the Dashboard.

Thanks

**Comment by majoy** [comment]
Hi,

After some debugging, I was able to get the exception that's happening when I try to delete a recurring job through the dashboard:
**Message**
 _The invoked member is not supported in a dynamic assembly._

**Stack Trace**
   _at System.Reflection.Emit.InternalAssemblyBuilder.get_Location()
   at log4net.Util.SystemInfo.AssemblyLocationInfo(Assembly myAssembly)
   at log4net.Core.DefaultRepositorySelector.GetInfoForAssembly(Assembly assembly, String& repositoryName, Type& repositoryType)
   at log4net.Core.DefaultRepositorySelector.CreateRepository(Assembly repositoryAssembly, Type repositoryType, String repositoryName, Boolean readAssemblyAttributes)
   at log4net.Core.DefaultRepositorySelector.CreateRepository(Assembly repositoryAssembly, Type repositoryType)
   at log4net.Core.DefaultRepositorySelector.GetRepository(Assembly repositoryAssembly)
   at log4net.Core.LoggerManager.GetLogger(Assembly repositoryAssembly, String name)
   at log4net.LogManager.GetLogger(Assembly repositoryAssembly, String name)
   at log4net.LogManager.GetLogger(String name)
   at lambda_method(Closure , String )
   at Hangfire.Logging.LogProviders.Log4NetLogProvider.GetLogger(String name)
   at Hangfire.Logging.LogProvider.GetLogger(String name)
   at Hangfire.Logging.LogProvider.For[T]()
   at Hangfire.AutomaticRetryAttribute..cctor()_

If I add the following line of code in the Startup.Configuration method for the web project that exposes the Hangfire dashboard I do not see the above issue:

_LogProvider.SetCurrentLogProvider(new ColouredConsoleLogProvider());_

That said, the exception I'm seeing due to not having the LogProvider.SetCurrentLogProvider line isn't expected and shouldn't be a required in order for users to be able to delete a recurring job through the dashboard so I'm leaving this issue open.

**Comment by burningice2866** [comment]
@majoy Are you using log4net in your project for normal logging?

**Comment by majoy** [comment]
Yeah, I am using log4net but this reminded me of something I came across when I was evaluating Hangfire in my system. 

We have a dependency on using an old version of log4net (v1.2.9.0) which Hangfire does not seem to support based on what I found in this [thread](https://discuss.hangfire.io/t/the-invoked-member-is-not-supported-in-a-dynamic-assembly/526/4)

I'm going to close this ticket since I don't expect Hangfire to support older versions of log4net and I'm pretty positive that if I were to upgrade my log4net dependency this issue would most likely go away.

Thanks again

**Comment by burningice2866** [comment]
Yeah, if you're using log4net already Hangfire will pick that up automatically and in case of an old log4net version, you would need to tell Hangfire explicitly to use another log provider or just log into dev/null
