### ISSUE TITLE
Dashboard System.NullReferenceException

### ISSUE THREAD

**Issue by knopa** [HangfireIO/Hangfire#883]
Object reference not set to an instance of an object.

System.NullReferenceException: Object reference not set to an instance of an object.
   at Hangfire.Dashboard.HtmlHelper.ServerId(String serverId)
   at Hangfire.Dashboard.Pages.ProcessingJobsPage.Execute()
   at Hangfire.Dashboard.RazorPage.TransformText(String body)
   at Hangfire.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context)
   at Hangfire.Dashboard.MiddlewareExtensions.<>c__DisplayClass1_2.<UseHangfireDashboard>b__1(IDictionary`2 env)
   at Microsoft.Owin.Mapping.MapMiddleware.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage.<RunApp>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.<DoFinalWork>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar)
   at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

/jobs/processing - redis

**Comment by odinserj** [comment]
@knopa, thanks for reporting this issue! Fixed in commit cd2c07f7dab71e9bed1aa5552eefeb64f89c56aa, closing this issue.

**Comment by danpak6** [comment]
We are having the same issue on HangFire version 1.6.17 and Pro version 2.1.0

[NullReferenceException: Object reference not set to an instance of an object.]    Hangfire.Dashboard.Pages.FailedJobsPage.Execute() +2639    Hangfire.Dashboard.RazorPage.TransformText(String body) +30    Hangfire.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context) +85    Hangfire.Dashboard.<>c__DisplayClass1_2.<UseHangfireDashboard>b__1(IDictionary`2 env) +465    Microsoft.Owin.Mapping.<Invoke>d__0.MoveNext() +460    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62    Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__5.MoveNext() +203    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62    Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<DoFinalWork>d__2.MoveNext() +193    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31    Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar) +119    System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +365    System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +134
--
