### ISSUE TITLE
Hangfire.CreateBatchFailedException

### ISSUE THREAD

**Issue by dcorbett-fivebridgesllc** [HangfireIO/Hangfire#905]
Hangfire.CreateBatchFailedException

An exception occurred while creating the batch. See the inner exception for details.

Hangfire.CreateBatchFailedException: An exception occurred while creating the batch. See the inner exception for details. ---> System.Data.SqlClient.SqlException: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_HangFire_State_Job". The conflict occurred in database "JMA_BatchQueues", table "HangFire.Job", column 'Id'.
The statement has been terminated.

This happened while adding 1290 jobs to one batch ( taking an hour to do so ).   Any ideas of what went wrong?   It failed to actually start any new jobs due to this error.   It took about 3 seconds per batch in this loop.

Not sure why this fails to format correctly:

```cs
  var batchJobId = BatchJob.StartNew(parent =>
                {
                    foreach (var request in expandedRequests)
                    {
                        // code for updating our db with info

                        var createdJobId =
                            parent.StartNew(analysisBatch =>
                                    analysisBatch.Enqueue<IHangFireEngineBatch>(
                                        x => x.CreatePortfolioAnalysisBatch(request, JobCancellationToken.Null, null)),
                                $"Create portfolio batch for {request.BatchName} Portfolio: {request.PortfolioName} ScenarioSetId: {request.ScenarioSetId} RunId: {request.AnalysisRunId}");

                        performContext.WriteLine($"Queued sub-batch {createdJobId}");
                        progressBar.SetValue(++count * 100 / expandedRequests.Count);
                       
                        // more code for updating our db with info                  
                    }
                }, $"Create Portfolio Analysis Batches for {batch.BatchName}");
```

   - Daniel

**Comment by odinserj** [comment]
@dcorbett-fivebridgesllc, could you show me the whole details page of the background job that's execute the code above?

**Comment by dcorbett-fivebridgesllc** [comment]
![image](https://cloud.githubusercontent.com/assets/26471190/26579081/5ac1a88a-4500-11e7-907d-b45bfa7180c1.png)

The full exception is here:

Hangfire.CreateBatchFailedException

An exception occurred while creating the batch. See the inner exception for details.

Hangfire.CreateBatchFailedException: An exception occurred while creating the batch. See the inner exception for details. ---> System.Data.SqlClient.SqlException: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_HangFire_State_Job". The conflict occurred in database "JMA_BatchQueues", table "HangFire.Job", column 'Id'.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader)
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command)
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType)
   at Hangfire.SqlServer.SqlServerWriteOnlyTransaction.<>c__DisplayClass8_0.<SetJobState>b__0(DbConnection connection, DbTransaction transaction)
   at Hangfire.SqlServer.SqlServerWriteOnlyTransaction.<Commit>b__5_0(DbConnection connection, DbTransaction transaction)
   at Hangfire.SqlServer.SqlServerStorage.<>c__DisplayClass21_0.<UseTransaction>b__0(DbConnection connection, DbTransaction transaction)
   at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](Func`2 func)
   at Hangfire.SqlServer.SqlServerStorage.UseTransaction[T](Func`3 func, Nullable`1 isolationLevel)
   at Hangfire.SqlServer.SqlServerStorage.UseTransaction(Action`2 action)
   at Hangfire.SqlServer.SqlServerWriteOnlyTransaction.Commit()
   at Hangfire.BatchJobClient.Create(Action`1 createAction, IBatchState state, String description)
   --- End of inner exception stack trace ---
   at Hangfire.BatchJobClient.Create(Action`1 createAction, IBatchState state, String description)
   at Javelin.MultiAsset.Batch.BatchService.StartPortfolioBatch(BatchRequestModel batchRequestModel, BatchRun batchRun, IJobCancellationToken cancellationToken, PerformContext performContext) in Z:\TeamCity\BuildAgent2\work\15a46b9a78339ebc\Javelin.MultiAsset.Batch\BatchService.cs:line 339
   at Javelin.MultiAsset.Batch.BatchService.StartBatch(String json, IJobCancellationToken cancellationToken, PerformContext performContext) in Z:\TeamCity\BuildAgent2\work\15a46b9a78339ebc\Javelin.MultiAsset.Batch\BatchService.cs:line 106
   at Javelin.MultiAsset.BackendService.HangFireEngine.StartBatch(String json, IJobCancellationToken cancellationToken, PerformContext performContext) in Z:\TeamCity\BuildAgent2\work\15a46b9a78339ebc\Javelin.MultiAsset.BackendService\HangFireEngine.cs:line 268

**Comment by odinserj** [comment]
Thanks for the information! But could you also post here all the other states as well? I need to investigate the full workflow of a background job, especially its processing time.

**Comment by dcorbett-fivebridgesllc** [comment]
The page is huge...    Because I am outputing a fair amount of information to the Console..

This job took about 1 1/2 hours to get to the point it crashed -- and an hour of it was actually creating the 1290 jobs.   I plan to optimize that by reducing the number of jobs by increasing the work each one does from ( 20 sub-jobs each to 100 ), and not saving intermediate data on every loop but only once after I've created all the sub-jobs.

![image](https://cloud.githubusercontent.com/assets/26471190/26579394/9f2c83e0-4501-11e7-9dc1-5abdc8ac61b5.png)

**Comment by dcorbett-fivebridgesllc** [comment]
The previous failures were due to a database connection issue, that I fixed by making sure the database had the right login, and then requeued the job.

**Comment by dcorbett-fivebridgesllc** [comment]
Nothing else was going on...  but I did have 19 other servers running at the time, ready to process this huge set of jobs I was creating.

**Comment by odinserj** [comment]
Thanks, @dcorbett-fivebridgesllc, that information is enough!

> This job took about 1 1/2 hours to get to the point it crashed

Batch is created in two phases: initially it creates all the background jobs, and then, after calling the action method it commits the whole transaction. Background jobs are created outside of that transaction due to backward compatibility, and they are created with the expiration time set to 1 hour. I was already planned to increase it to 1 day or 1 month, and will release the change this week with 1.6.13.

But another question, why it took 1.5 hours to create such a small amount of background jobs?. Do you have any ideas?

**Comment by dcorbett-fivebridgesllc** [comment]
It could be the two SaveChanges() that I had in each loop ( saving to a different database about that job piece ).     I can certainly speed this up significantly by doing that only once outside the loop ( but inside the batch creation action method ).   In fact, that's better, as I'm trying to synchronize the two.

Good to know it's the one hour timeout, which means my performance enhancements will take care of my issue, even without hangfire bug fix.

**Comment by odinserj** [comment]
Great to hear, @dcorbett-fivebridgesllc. But I'll fix it anyway :-) Thanks for all of your information!
