### ISSUE TITLE
Hangfire fails on app.UseHangfireServer() during tests

### ISSUE THREAD

**Issue by savpek** [HangfireIO/Hangfire#917]
I am using net core TestHost which is re-created between acceptance tests. However very often when tests are run startup fails randomly on test at line 'app.UseHangfireServer()'. This smells issue where hangfire is using global static state.

Environment .Net core 1.1.2. (netcoreapp1.1)

Error and stack trace:
```
System.InvalidOperationException : JobStorage.Current property value has not been initialized. You must set it before using Hangfire Client or Server API.
   at Hangfire.JobStorage.get_Current()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Hangfire.HangfireApplicationBuilderExtensions.UseHangfireServer(IApplicationBuilder app, BackgroundJobServerOptions options, IEnumerable`1 additionalProcesses, JobStorage storage)
   at Pdf.Storage.Test.TestStartup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in C:\work\pdf-storage\Test\TestStartup.cs:line 39
```

Meaningfull lines on Startup:
```
Services:
    services.AddHangfire(config => config.UseMemoryStorage());
Configuration:
    app.UseHangfireServer(); // Error occurs here.
    app.UseHangfireDashboard();
```

**Comment by savpek** [comment]
https://github.com/HangfireIO/Hangfire/issues/808

**Comment by savpek** [comment]
#808

**Comment by VadimLopatkin** [comment]
@savpek We have the same issue with .NET Core 2.0. Were you able to find a workaround?

**Comment by savpek** [comment]
Only workaround i have found is retrying on error. I digged deeper down code level how startup is made but didn't find good solution. Writing own version of userHangFireServer() could work, but then theres high probability that it breaks when hangfire gets updated.

```
            // Workaround for hanfire instability issue during testing.
            Retry.Action(() => app.UseHangfireServer(), retryInterval: TimeSpan.FromMilliseconds(100), maxAttemptCount: 5);
```

```
public static class Retry
    {
        public static void Action(
            Action action,
            TimeSpan retryInterval,
            int maxAttemptCount = 3)
        {
            Func<object>(() =>
            {
                action();
                return null;
            }, retryInterval, maxAttemptCount);
        }

        public static T Func<T>(
            Func<T> action,
            TimeSpan retryInterval,
            int maxAttemptCount = 3)
        {
            var exceptions = new List<Exception>();

            for (int attempted = 0; attempted < maxAttemptCount; attempted++)
            {
                try
                {
                    if (attempted > 0)
                    {
                        Thread.Sleep(retryInterval);
                    }
                    return action();
                }
                catch (Exception ex)
                {
                    exceptions.Add(ex);
                }
            }
            throw new AggregateException(exceptions);
        }
```

**Comment by VadimLopatkin** [comment]
@savpek After a bit of googling and experimenting I came up with a solution that seems, maybe, a bit less hacky. In the Startup.cs:

`public class Startup
    {
        private static IGlobalConfiguration _hangfireConfig;

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddHangfire(config =>
            {
                config.UseMemoryStorage();
                _hangfireConfig = config;
            });
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            SetupHangfire(app);
        }

        private void SetupHangfire(IApplicationBuilder app)
        {
            var services = app.ApplicationServices;
            var logger = services.GetRequiredService<ILoggerFactory>();
            _hangfireConfig.UseLogProvider(new AspNetCoreLogProvider(logger));
            app.UseHangfireServer();
        }
    }`

**Comment by Alexxtheonly** [comment]
This also occurs with net core 2.1.0-preview

**Comment by AMerkuri** [comment]
Same problem with 2.1.0-rc1

**Comment by CodeMonkeyInit** [comment]
Same with 2.1.2
