### ISSUE TITLE
Hangfire failing to create large batches...  he transaction associated with the current connection has completed but has not been disposed

### ISSUE THREAD

**Issue by dcorbett-fivebridgesllc** [HangfireIO/Hangfire#922]
We are getting an exception when creating a batch.

I am pushing the batch heavily....    40 jobs running per machine on 10 machines backed by a SQL database.

The exception happens during the save of the created batch/sub-batches/jobs.    This doesn't happen when the batches are 1/2 the size...   In this case we are creating on the order of 2000 inter-related.

> Hangfire.CreateBatchFailedException: An exception occurred while creating the batch. See the inner exception for details. ---> Hangfire.BackgroundJobClientException: Background job creation failed. See inner exception for details. ---> System.InvalidOperationException: The transaction associated with the current connection has completed but has not been disposed.  The transaction must be disposed before the connection can be used to execute SQL statements.
   at System.Data.SqlClient.TdsParser.TdsExecuteRPC(SqlCommand cmd, _SqlRPC[] rpcArray, Int32 timeout, Boolean inSchema, SqlNotificationRequest notificationRequest, TdsParserStateObject stateObj, Boolean isCommandProc, Boolean sync, TaskCompletionSource`1 completion, Int32 startRpc, Int32 startParam)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command)
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType)
   at Hangfire.SqlServer.SqlServerWriteOnlyTransaction.<>c__DisplayClass21_0.<SetRangeInHash>b__0(DbConnection connection, DbTransaction transaction)
   at Hangfire.SqlServer.SqlServerWriteOnlyTransaction.<Commit>b__5_0(DbConnection connection, DbTransaction transaction)
   at Hangfire.SqlServer.SqlServerStorage.<>c__DisplayClass21_0.<UseTransaction>b__0(DbConnection connection, DbTransaction transaction)
   at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](Func`2 func)
   at Hangfire.SqlServer.SqlServerStorage.UseTransaction[T](Func`3 func, Nullable`1 isolationLevel)
   at Hangfire.SqlServer.SqlServerStorage.UseTransaction(Action`2 action)
   at Hangfire.SqlServer.SqlServerWriteOnlyTransaction.Commit()
   at Hangfire.Batches.AwaitingBatchContinuationSupport.OnStateElection(ElectStateContext context)
   at Hangfire.States.StateMachine.ApplyState(ApplyStateContext initialContext)
   at Hangfire.Client.CoreBackgroundJobFactory.Create(CreateContext context)
   at Hangfire.Client.BackgroundJobFactory.<>c__DisplayClass7_0.<CreateWithFilters>b__0()
   at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation)
   at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation)
   at Hangfire.Client.BackgroundJobFactory.Create(CreateContext context)
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
   --- End of inner exception stack trace ---
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
   at Javelin.MultiAsset.Batch.BatchService.<>c__DisplayClass49_2.<CreatePortfolioAnalysisBatch>b__10(IBatchAction batch) in Y:\TeamCity\BuildAgent3\work\15a46b9a78339ebc\Javelin.MultiAsset.Batch\BatchService.cs:line 805
   at Hangfire.BatchJobClient.Create(Action`1 createAction, IBatchState state, String description)
   --- End of inner exception stack trace ---
   at Hangfire.BatchJobClient.Create(Action`1 createAction, IBatchState state, String description)
   at Hangfire.BatchJob.AwaitBatch(String antecedentId, Action`1 createAction, String description, BatchContinuationOptions options)
   at Javelin.MultiAsset.Batch.BatchService.CreatePortfolioAnalysisBatch(AnalysisBatchRequest analysisBatchRequest, IJobCancellationToken cancellationToken, PerformContext performContext) in Y:\TeamCity\BuildAgent3\work\15a46b9a78339ebc\Javelin.MultiAsset.Batch\BatchService.cs:line 759
   at Javelin.MultiAsset.BackendService.HangFireEngine.CreatePortfolioAnalysisBatch(AnalysisBatchRequest analysisBatchRequest, IJobCancellationToken cancellationToken, PerformContext performContext) in Y:\TeamCity\BuildAgent3\work\15a46b9a78339ebc\Javelin.MultiAsset.BackendService\HangFireEngine.cs:line 272
>

**Comment by dcorbett-fivebridgesllc** [comment]
( the overall # of jobs we have to run are on the order of 7 million items, with three steps per item -- one step per X ( 1000 in this case ) to organize them seems like the right approach, but maybe not? ).

**Comment by dcorbett-fivebridgesllc** [comment]
Also got this, perhaps the continuation batch failed to be created because of the previous error?   
Is this an artifact of running 40 jobs per server?  

I'm using HangFire versions v1.6.14 with SQL Storage, and my config string has a timeout of 300ms, and poolsize of 600.

> System.InvalidOperationException
> 
> Could not start a continuation batch '30466665-b0da-404a-98ca-c367fd1e18a3': it does not exist
> 
> System.InvalidOperationException: Could not start a continuation batch '30466665-b0da-404a-98ca-c367fd1e18a3': it does not exist
>    at Hangfire.Batches.BatchContinuationsSupportAttribute.ExecuteContinuationsIfExist(ApplyBatchStateContext context)
>    at Hangfire.Batches.BatchContinuationsSupportAttribute.OnStateApplied(ApplyBatchStateContext context)
>    at Hangfire.Batches.States.BatchStateMachine.ApplyState(ApplyBatchStateContext context)
>    at Hangfire.Batches.States.BatchStateChanger.ChangeState(BatchStateChangeContext context)
>    at Hangfire.Batches.BatchJobSupportAttribute.TryFinishBatch(JobStorage storage, JobStorageConnection connection, JobStorageTransaction transaction, String batchId, String setToExpire)
>    at Hangfire.Batches.BatchJobSupportAttribute.OnStateApplied(ApplyStateContext context, IWriteOnlyTransaction outerTransaction)
>    at Hangfire.States.StateMachine.ApplyState(ApplyStateContext initialContext)
>    at Hangfire.States.BackgroundJobStateChanger.ChangeState(StateChangeContext context, BackgroundJob backgroundJob, IState toState, String oldStateName)

**Comment by dcorbett-fivebridgesllc** [comment]
Upgraded to latest Hangfire release, using the slidingInvisibilityTimeout and things seemed to work better during the first phase, but still running into some serious limits around 35,000+ jobs in the active queue(s).

  new SqlServerStorageOptions
                    {
                        QueuePollInterval = TimeSpan.FromSeconds(30),
                        CommandTimeout = TimeSpan.FromMinutes(10),
                        TransactionTimeout = TimeSpan.FromMinutes(10),
                        SlidingInvisibilityTimeout = TimeSpan.FromMinutes(10)
                    })

The console has become non-responsive much of the time.

Still getting CreateBatchFailedException exceptions:

>Hangfire.CreateBatchFailedException
>
> An exception occurred while creating the batch. See the inner exception for details.
> 
> Hangfire.CreateBatchFailedException: An exception occurred while creating the batch. See the inner exception for details. ---> Hangfire.CreateBatchFailedException: An exception occurred while creating the batch. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Cannot release the application lock (Database Principal: 'public', Resource: 'HangFire:batch:5db947d7-44e6-420b-9731-ea6a4c8c3055:lock') because it is not currently held.
>    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
>    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
>    at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
>    at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
>    at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
>    at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
>    at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
>    at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader)
>    at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command)
>    at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType)
>    at Hangfire.SqlServer.SqlServerDistributedLock.Release(IDbConnection connection, String resource)
>    at Hangfire.SqlServer.SqlServerDistributedLock.Dispose()
>    at Hangfire.BatchJobClient.Create(Action`1 createAction, IBatchState state, String description)
>    --- End of inner exception stack trace ---
>    at Hangfire.BatchJobClient.Create(Action`1 createAction, IBatchState state, String description)
>    at Hangfire.BatchJob.AwaitJob(String antecedentId, Action`1 createAction, String description, BatchContinuationOptions options)
>    at Javelin.MultiAsset.Batch.BatchService.<>c__DisplayClass53_2.<CreatePortfolioAnalysisBatch>b__10(IBatchAction batch) in Z:\TeamCity\BuildAgent2\work\15a46b9a78339ebc\Javelin.MultiAsset.Batch\BatchService.cs:line 788
>    at Hangfire.BatchJobClient.Create(Action`1 createAction, IBatchState state, String description)
>    --- End of inner exception stack trace ---
>    at Hangfire.BatchJobClient.Create(Action`1 createAction, IBatchState state, String description)
>    at Hangfire.BatchJob.AwaitBatch(String antecedentId, Action`1 createAction, String description, BatchContinuationOptions options)
>    at Javelin.MultiAsset.Batch.BatchService.CreatePortfolioAnalysisBatch(String json, IJobCancellationToken cancellationToken, PerformContext performContext) in Z:\TeamCity\BuildAgent2\work\15a46b9a78339ebc\Javelin.MultiAsset.Batch\BatchService.cs:line 764
>    at Javelin.MultiAsset.BackendService.HangFireEngine.CreatePortfolioAnalysisBatch(String json, IJobCancellationToken cancellationToken, PerformContext performContext) in Z:\TeamCity\BuildAgent2\work\15a46b9a78339ebc\Javelin.MultiAsset.BackendService\HangFireEngine.cs:line 272

**Comment by aidmsu** [comment]
Hi, @dcorbett-fivebridgesllc! 

Thanks for a bugreport. Could you share more details about `HangFireEngine.CreatePortfolioAnalysisBatch` method? Also I need Hangfire.Pro version you use.

**Comment by dcorbett-fivebridgesllc** [comment]
Hangfire.Pro is 2.0.1     I will cut out the pieces of CreatePortfolioAnalysisBatch that are relevant to creating jobs/batches, and post that in the next comment:

I'm now seeing additional errors when it tries to make jobs as succeeded.   

> 
> System.InvalidOperationException
> 
> The transaction associated with the current connection has completed but has not been disposed. The transaction must be disposed before the connection can be used to execute SQL statements.
> 
> System.InvalidOperationException: The transaction associated with the current connection has completed but has not been disposed.  The transaction must be disposed before the connection can be used to execute SQL statements.
>    at System.Data.SqlClient.TdsParser.TdsExecuteRPC(SqlCommand cmd, _SqlRPC[] rpcArray, Int32 timeout, Boolean inSchema, SqlNotificationRequest notificationRequest, TdsParserStateObject stateObj, Boolean isCommandProc, Boolean sync, TaskCompletionSource`1 completion, Int32 startRpc, Int32 startParam)
>    at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
>    at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
>    at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
>    at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
>    at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command)
>    at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType)
>    at Hangfire.SqlServer.SqlServerWriteOnlyTransaction.<Commit>b__5_0(DbConnection connection, DbTransaction transaction)
>    at Hangfire.SqlServer.SqlServerStorage.<>c__DisplayClass24_0.<UseTransaction>b__0(DbConnection connection, DbTransaction transaction)
>    at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](Func`2 func)
>    at Hangfire.SqlServer.SqlServerStorage.UseTransaction[T](Func`3 func, Nullable`1 isolationLevel)
>    at Hangfire.SqlServer.SqlServerStorage.UseTransaction(Action`2 action)
>    at Hangfire.SqlServer.SqlServerWriteOnlyTransaction.Commit()
>    at Hangfire.States.BackgroundJobStateChanger.ChangeState(StateChangeContext context, BackgroundJob backgroundJob, IState toState, String oldStateName)
>

**Comment by dcorbett-fivebridgesllc** [comment]
` 
	        // var batchJobId = BatchJob.StartNew(batch =>
	        var batchJobId = BatchJob.AwaitBatch(parentBatchId, batch =>
	        {
	            foreach (var asset in analysisBatchRequest.Assets)
	            {
	                foreach (var scenario in assetToScenarioDict[asset.ReferenceId])
	                {
	                    var relatedAssetsDealEngineRequestDocumentIds = new List<string>();
	                    var dealEngineRequestDocumentId = Guid.NewGuid().ToString();
	                    var relatedAssetsBatchId = string.Empty;

	                    performContext.WriteLine($@"Creating job chain for asset {asset?.AssetIdentifierType} {asset?.AssetIdentifer} scenario: {scenario.Name} - Count: {count}");
                        
	                    var populateJobId = batch.Enqueue<IHangFireEngineBatch>(x => x.BatchPopulateAssumptions(
	                        analysisBatchRequestJson, asset.ReferenceId, scenario.ReferenceGuid,
	                        dealEngineRequestDocumentId, JobCancellationToken.Null, null));

	                    progressBar.SetValue(count++ * 100 / total);

	                    if (asset?.RelatedAssets?.Any() ?? false)
	                    {
	                        relatedAssetsBatchId = BatchJob.AwaitJob(populateJobId, relatedAssetsBatch =>
	                            {
	                                foreach (var relatedAsset in asset?.RelatedAssets)
	                                {
	                                    var relatedDealEngineRequestDocumentId = Guid.NewGuid().ToString();
	                                    relatedAssetsDealEngineRequestDocumentIds.Add(relatedDealEngineRequestDocumentId);

	                                    var relatedJobId = relatedAssetsBatch.Enqueue<IHangFireEngineBatch>(
	                                        x => x.BatchPopulateAssumptionsRelated(analysisBatchRequestJson,
	                                            relatedAsset.ReferenceId,
	                                            scenario.ReferenceGuid, relatedDealEngineRequestDocumentId,
	                                            JobCancellationToken.Null, null));

	                                    progressBar.SetValue(count++ * 100 / total);
	                                }
	                            },
	                            $"Related Assets: {asset.RelatedAssets.Count} - {asset.RelatedAssets.Select(ra => ra.AssetIdentifer).Aggregate((s1, s2) => $"{s1},{s2}")}");
	                    }
	                    if (!analysisBatchRequest.DoRun)
	                        performContext.WriteLine("Skipping queuing of  run jobs");

	                    if (!string.IsNullOrWhiteSpace(relatedAssetsBatchId))  // Continue from batch of related assets.
	                    {
	                        var backgroundJob = new BackgroundJobClient();

	                        backgroundJob.AwaitBatch<IHangFireEngineBatch>(relatedAssetsBatchId,
	                            z => z.BatchRunAnalysis(analysisBatchRequestJson,
	                                asset.ReferenceId,
	                                scenario.ReferenceGuid,
	                                dealEngineRequestDocumentId,
	                                JobCancellationToken.Null, null, relatedAssetsDealEngineRequestDocumentIds), null,
	                            BatchContinuationOptions.OnlyOnSucceededState);
	                    }
	                    else
	                    {
	                        var runJobId = BackgroundJob.ContinueWith<IHangFireEngineBatch>(populateJobId,
	                            x =>
	                                x.BatchRunAnalysis(analysisBatchRequestJson, asset.ReferenceId,
	                                    scenario.ReferenceGuid,
	                                    dealEngineRequestDocumentId,
	                                    JobCancellationToken.Null, null, null),
	                            JobContinuationOptions.OnlyOnSucceededState);
	                    }
	                }
	            }
	        }, $"Populate & Run for all assets & scenarios for RunId: {analysisBatchRequest.AnalysisRunId}");

	        BatchJob.AwaitBatch(batchJobId, continuewith =>
	        {
	            continuewith.StartNew(
	                inner =>
	                    inner.Enqueue<IHangFireEngineBatch>(x => x.BatchAnalysisComplete(analysisBatchRequestJson,
	                        JobCancellationToken.Null, null)));
	        }, $"Completion of populate & assumption batch for RunId: {analysisBatchRequest.AnalysisRunId}");
`

**Comment by dcorbett-fivebridgesllc** [comment]
sp_who2 produces a report of the SQL requests in progress.   There are many that are blocked by other jobs.   I suspect the blocking is what is stopping this from scaling the way we need it too.   Am I somehow at the limit of what Hangfire can do with SQL Server?

I deleted background rows and both the username and hostname columns.

[Hangfire.Spwho.xlsx](https://github.com/HangfireIO/Hangfire/files/1092004/Hangfire.Spwho.xlsx)

**Comment by dcorbett-fivebridgesllc** [comment]
@aidmsu - I couldn't wait for assistance... and have moved to Redis with great success so far.    I'm not out of the woods in terms of getting things to scale, but Hangfire seems to perform very well on Redis instead of SQL Server.    I was very pleased at how relatively easy it was to make the switch!  :)

**Comment by aidmsu** [comment]
@dcorbett-fivebridgesllc you should configure multiple Hangfire servers to switch to Redis storage. First server will be resposnsible for handling old jobs storing in MS SQL Server. When the latter finish its work (you can see this in Dashboard – your SQL Server queues will be removed), you can remove it safely. Second will handle new jobs storing in Redis:
```csharp
/* This server will process only SQL Server table queues, i.e. old jobs */
var oldStorage = new SqlServerStorage("<connection string or its name>");
var oldOptions = new BackgroundJobServerOptions
{
    ServerName = "OldQueueServer" // Pass this to differentiate this server from the next one
};

app.UseHangfireServer(oldOptions, oldStorage);

/* This server will process only Redis queues, i.e. new jobs */
GlobalConfiguration.Configuration
    .UseRedisStorage("<connection string or its name>");

app.UseHangfireServer();
```

**Comment by dcorbett-fivebridgesllc** [comment]
We had no need to keep the original jobs in the old storage.   This is a batch process, and I ran this size batch to completion for the first time overnight... :)    Redis is a success.   Still need to up performance more, but progress is being made.

Thanks for the awesome product, that I could make this change ( from SQL to Redis ) with ~10 lines of code per process!  :)
