### ISSUE TITLE
DistributedLockTimeoutException...

### ISSUE THREAD

**Issue by dcorbett-fivebridgesllc** [HangfireIO/Hangfire#925]
We are having some great success with Hangfire & Redis, but we still need to improve our performance.

Looking at our logs, we are seeing quite a few RedisDistributedLock timeout expired messages.   It appears the error is handled, as I'm not seeing corresponding retries.

This may be expected behavior...   So wanted to check to see..

Thanks,

   - Daniel

**Comment by odinserj** [comment]
@dcorbett-fivebridgesllc, could you tell me more details on this, i.e. where do you see such messages, could you show me your log messages and tell what component is causing them?

**Comment by dcorbett-fivebridgesllc** [comment]
I see these messages in my logs.   The queue varies, but the actual timeout error seems to be the same in each one.

10:51:32.1397    BATCH-0c14b47822aae190a3c0957db2db232b 073879SJ8 ERROR Error occurred during execution of 'Hangfire.Pro.Redis.FetchedJobsWatcher' process. Execution will be retried (attempt #6) in 00:00:33 seconds. 
<no type>.CallSite.Target0 
Hangfire.Storage.DistributedLockTimeoutException: Timeout expired. The timeout elapsed prior to obtaining a distributed lock on the 'queue:priority6_batch_run:dequeued:lock' resource.
   at Hangfire.Pro.Redis.RedisDistributedLock.RetryUntilTrue(Func`1 action, Nullable`1 timeOut)
   at Hangfire.Pro.Redis.RedisDistributedLock..ctor(Func`1 databaseFactory, String resource, String lockToken, TimeSpan timeout)
   at Hangfire.Pro.Redis.RedisConnection.DistributedLockWrapper..ctor(RedisConnection connection, String resource, TimeSpan timeout)
   at Hangfire.Pro.Redis.RedisConnection.AcquireDistributedLock(String resource, TimeSpan timeout)
   at Hangfire.Pro.Redis.FetchedJobsWatcher.ProcessQueue(String queue, RedisConnection connection)
   at Hangfire.Pro.Redis.FetchedJobsWatcher.Execute(CancellationToken cancellationToken)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)

**Comment by odinserj** [comment]
`FetchedJobsWatcher` is an internal process that re-queues background jobs, whose processing has been terminated in a non-graceful way. This process runs on each server, and for each queue it acquires a distributed lock to prevent other processing servers to get into the process. And if you have a lot of servers, some of them are inevitably will fail to acquire a lock, causing this exception.

I've just committed a fix, where I've decreased severity level from `error` to `debug`. I'll release it a bit later (maybe there will be other fixes as well). Do you see other problems with Hangfire.Pro.Redis?
