### ISSUE TITLE
System.Globalization.CultureNotFoundException. Culture is not supported.

### ISSUE THREAD

**Issue by mspace** [HangfireIO/Hangfire#964]
I'm using:
- HangFire.Core v1.4.6
- Hangfire.SqlServer v1.4.6
- Windows 10 x64
- IIS 10.0 (not important probably but still)

Suddenly I got failed jobs containing next exception:

```
System.Globalization.CultureNotFoundException

Culture is not supported. Parameter name: name en-SI is an invalid culture identifier.

System.Globalization.CultureNotFoundException: Culture is not supported.
Parameter name: name
en-SI is an invalid culture identifier.
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at Hangfire.CaptureCultureAttribute.OnPerforming(PerformingContext filterContext)
   at Hangfire.Server.BackgroundJobPerformer.InvokePerformFilter(IServerFilter filter, PerformingContext preContext, Func`1 continuation)
```

Hangfire was using two servers if that makes any difference. After deleting all Hangfire tables it now works, but still don't know why this happened.

But why does CultureNotFoundException occurs? Thread is always running under valid culturename. I found next post: https://stackoverflow.com/questions/38690850/disable-preservecultureattribute-in-hangfire

**Comment by odinserj** [comment]
I just found, that the `en-SI` culture identifier appeared only in Windows 10 v1607 operating system and Windows Server 2016, according to [MSDN](https://msdn.microsoft.com/en-us/library/cc233982.aspx). So looks like the other server know nothing about this culture. Culture may play very important role, so let's think which solution is acceptable for the most cases:

1. Fail a background job, when we can't find appropriate culture.
2. Try to find a base culture based on two-letter code, if still not found – go to 3.
3. Ignore the exception, but log it as a warning message.

Meanwhile you can use the following methods to remove the filter:

```csharp
var captureCulture = GlobalJobFilters.Filters.Where(x => x.Instance is CaptureCultureAttribute);
GlobalJobFilters.Filters.Remove(captureCulture);
```
