### ISSUE TITLE
Hangfire.Storage.DistributedLockTimeoutException: Timeout expired.

### ISSUE THREAD

**Issue by dcorbett-fivebridgesllc** [HangfireIO/Hangfire#998]
I updated my hangfire version to use the very latest update to Pro.Redis (v2.1.2), and now, I'm getting a new symptom.

My jobs ( 4300 simultaneous jobs running on ~170 machines ) ground to a halt...  for a period of time - didn't measure how long, but
Based on the one job which aborted, it must have been due to a deadlock due to this RedisDistributedLock hanging.

Hangfire.CreateBatchFailedException
An exception occurred while creating the batch. See the inner exception for details.
Hangfire.CreateBatchFailedException: An exception occurred while creating the batch. See the inner exception for details. ---> Hangfire.Storage.DistributedLockTimeoutException: Timeout expired. The timeout elapsed prior to obtaining a distributed lock on the 'batch:0a6ac48e-a0f7-4040-9195-0b6a6dcd4ffc:lock' resource.
   at Hangfire.Pro.Redis.RedisDistributedLock.RetryUntilTrue(Func`1 action, Nullable`1 timeOut)
   at Hangfire.Pro.Redis.RedisDistributedLock..ctor(Func`1 databaseFactory, String resource, String lockToken, TimeSpan timeout)
   at Hangfire.Pro.Redis.RedisConnection.DistributedLockWrapper..ctor(RedisConnection connection, String resource, TimeSpan timeout)
   at Hangfire.Pro.Redis.RedisConnection.AcquireDistributedLock(String resource, TimeSpan timeout)
   at Hangfire.Batches.CachedStateConnection.AcquireDistributedLock(String resource, TimeSpan timeout)
   at Hangfire.Batches.BatchJobStorageExtensions.AcquireDistributedBatchLock(IStorageConnection connection, String batchId, TimeSpan timeout)
   at Hangfire.Batches.BatchContinuationsSupportAttribute.AddContinuation(ElectBatchStateContext context, BatchAwaitingState awaitingState)
   at Hangfire.Batches.BatchContinuationsSupportAttribute.OnStateElection(ElectBatchStateContext context)
   at Hangfire.Batches.States.BatchStateMachine.ApplyState(ApplyBatchStateContext context)
   at Hangfire.Batches.Client.BatchFactory.Create(BatchCreateContext context)
   at Hangfire.BatchJobClient.Create(Action`1 createAction, IBatchState state, String description)
   --- End of inner exception stack trace ---
   at Hangfire.BatchJobClient.Create(Action`1 createAction, IBatchState state, String description)
   at Hangfire.BatchJob.AwaitBatch(String antecedentId, Action`1 createAction, String description, BatchContinuationOptions options)
   at Javelin.MultiAsset.Batch.BatchService.CreatePortfolioAnalysisBatchJobs(String parentBatchId, AnalysisBatchRequest analysisBatchRequest, PerformContext performContext, IJobCancellationToken cancellationToken) in Z:\TeamCity\BuildAgent2\work\15a46b9a78339ebc\Javelin.MultiAsset.Batch\BatchService.cs:line 1292

Hangfire.Console v 1.3.6
Hangfire.Core v1.6.16
Hangfire.Pro v2.1.0
Hangfire.Pro.redis v2.1.2
Hangfire.SqlServer v1.6.16
Hangfire.Unity v1.3.0

**Comment by odinserj** [comment]
Distributed locks shouldn't be deadlocked, because they are either gracefully removed, or expired after 1 minute of inactivity by Redis itself. Time synchronization issues described in #997 shouldn't cause this, because in this case only time on Redis server matters.

170 machines with 4300 simultaneous jobs is a massive workload, and overloaded Redis instance definitely can cause timeouts, because commands are delayed. What is the CPU usage for your Redis instance?

Also, the exception above tells us that the batch creation has failed. Could you tell me from where the `BatchService.CreatePortfolioAnalysisBatchJobs` method is called, from background job or request handling logic? Is it the only exception you have, or there are others as well?

**Comment by dcorbett-fivebridgesllc** [comment]
CPU Usage was a max of 8% and appeared to drop to nearly zero at this point:

![image](https://user-images.githubusercontent.com/26471190/30600908-a1e21bb0-9d2e-11e7-809a-af56221d1338.png)

BatchService.CreatePortfolioAnalysisBatchJobs  is called from:

'
public void CreatePortfolioAnalysisBatchJobs(string parentBatchId, AnalysisBatchRequest analysisBatchRequest, PerformContext performContext, IJobCancellationToken cancellationToken)
        {
            cancellationToken = new JMAJobCancellationToken(performContext, cancellationToken);
            performContext.SetJobParameter("Batch", true);
            GetMachineInfo.OutputMachineInfo(performContext, "CreatePortfolioAnalysisBatch");
            BatchService.CreatePortfolioAnalysisBatchJobs(parentBatchId, analysisBatchRequest, performContext, cancellationToken);
        }
'

which is called by Hangfire.

The job re-ran and successfully completed after that.   I did notice that batch creation was slow the rest of the time ( it would take upwards of 20 minutes to create each batch ).

There were two differences in this run and previous runs that seem relevant:

1.  Updating the hangfire which has a change to the exception handling.
2.  We scaled the servers much faster than previously.

**Comment by odinserj** [comment]
Hm, 8% is fine, and it's not overloaded.

> My jobs ( 4300 simultaneous jobs running on ~170 machines ) ground to a halt... for a period of time - didn't measure how long, but
Based on the one job which aborted, it must have been due to a deadlock due to this RedisDistributedLock hanging.

Could you give more details on this? All of them were failed with the same exception as above? If yes, were all of them failed almost simultaneously? And what's your current status? Also, could you tell me more about the `JMAJobCancellationToken` class?

**Comment by dcorbett-fivebridgesllc** [comment]
No..   I only noticed this exception once, and it appeared in the Retry queue while I was trying to figure out why the batch stopped.   The job automatically retried, and everything completed - with the exception of the long running jobs I'm having an issue with due to invisibility.

JMAJobCancellationToken is simply a replacement for JobCancellationToken that gets replaced when the job is started, with the intention of logging when it happens.   That's all:

'
class JMAJobCancellationToken : IJobCancellationToken
    {
        private static readonly Logger SystemLogger = LogManager.GetCurrentClassLogger();
        private IJobCancellationToken HangfireJobCancellationToken { get; }
        private PerformContext PerformContext { get; }

        public JMAJobCancellationToken(PerformContext performContext, IJobCancellationToken jobCancellationToken)
        {
            HangfireJobCancellationToken = jobCancellationToken;
            PerformContext = performContext;
        }

        public CancellationToken ShutdownToken => HangfireJobCancellationToken.ShutdownToken;
        
        public void ThrowIfCancellationRequested()
        {
            try
            {
                SystemLogger.Trace("JMAJobCancellationToken:   Checking cancellation Token. ");
                HangfireJobCancellationToken.ThrowIfCancellationRequested();
            }
            catch (JobAbortedException ex)
            {
                SystemLogger.Error(ex, "JMAJobCancellationToken:   JobAbortedException...");
                PerformContext.WriteLine($@"JMAJobCancellationToken = JobAbortedException at {DateTime.Now}.");
                PerformContext.WriteLine($@"StackTrace: {ex.StackTrace}");
                throw;
            }
            catch (OperationCanceledException ex)
            {
                SystemLogger.Error(ex, "JMAJobCancellationToken:   OperationCanceledException...");
                PerformContext.WriteLine($@"JMAJobCancellationToken = JobAbortedException at {DateTime.Now}.");
                PerformContext.WriteLine($@"StackTrace: {ex.StackTrace}");
                throw;
            }
            catch (Exception ex)
            {
                SystemLogger.Error(ex, "JMAJobCancellationToken:  ShutdownToken throws... ");
                PerformContext.WriteLine($@"ShutdownToken throws at {DateTime.Now}.");
                PerformContext.WriteLine($@"StackTrace: {ex.StackTrace}");
                throw;
            }
        }
    }
'

**Comment by dcorbett-fivebridgesllc** [comment]
It's actually not been especially useful yet, unfortunately.

**Comment by knopa** [comment]
I just got same issue 
Hangfire.Storage.DistributedLockTimeoutException
Could it cause if job running more than 15 minutes?

**Comment by dcorbett-fivebridgesllc** [comment]
I only got this once.   I run 1000s of jobs that run in over 15 minutes in 140 AWS Instances.   In fact, I have some that take hours to run.

Once I got the RedisTimeout to be set identically on all machines, then things ran well.

**Comment by odinserj** [comment]
@knopa, are you using the `DisableConcurrencyAttribute`? Could you provide more exception details on this?

**Comment by knopa** [comment]
@odinserj correct for that Job use disable concurrency

**Comment by knopa** [comment]
I got again that issue.

I have now on another project 

RecurringJob.AddOrUpdate(jobName, methodCall, jobSettings.Schedule, new RecurringJobOptions()
{
    TimeZone = timezoneInfo ?? TimeZoneInfo.Utc
});

When any recurring job was in execution - after restart server - i failes with next exception

Hangfire.Storage.DistributedLockTimeoutException: 'Timeout expired. The timeout elapsed prior to obtaining a distributed lock on the 'lock:recurring-job:UserActivityJob' resource.'
